#!/usr/bin/env bash
# Port the erasure T1 proof onto the complete Session translation unit.
set -euo pipefail

cd "$(dirname "$0")/../.."

check=0
if [ "${1:-}" = "--check" ]; then
  check=1
elif [ $# -ne 0 ]; then
  echo "usage: port-session-erasure-proof.sh [--check]" >&2
  exit 1
fi

src=tacenta-proofs/translation/Translation/ErasureT1.lean
dest=tacenta-proofs/translation/Translation/SessionUnitErasureT1.lean
tmp=$(mktemp)
cleanup() { rm -f "$tmp"; }
trap cleanup EXIT INT TERM

python3 - "$src" "$tmp" <<'PY'
from pathlib import Path
import sys

src, dest = map(Path, sys.argv[1:3])
text = src.read_text()
substitutions = [
    ("Translation.TacentaErasure", "Translation.TacentaSessionUnit", 1),
    ("Tacenta.ErasureT1", "Tacenta.SessionUnitErasureT1", 5),
    ("open tacenta_erasure", "open tacenta_session_unit.tacenta_erasure", 1),
    ("core.num.Usize.div_ceil", "tacenta_session_unit.core.num.Usize.div_ceil", 1),
    ("alloc.vec.Vec.truncate", "tacenta_session_unit.alloc.vec.Vec.truncate", 2),
]
for old, new, expected in substitutions:
    found = text.count(old)
    if found != expected:
        raise SystemExit(
            f"port-session-erasure-proof: {old!r} occurs {found} time(s), "
            f"expected {expected}; inspect the source proof before changing this count")
    text = text.replace(old, new)

# The longer generated/proof namespace makes Lean's canonical `#print axioms`
# rendering wrap this one guard. Keep the guard exact rather than weakening it.
old_guard = (
    "info: 'Tacenta.SessionUnitErasureT1.message_no_panic' depends on axioms: "
    "[propext, Classical.choice, Quot.sound, "
    "tacenta_session_unit.alloc.vec.Vec.truncate]")
new_guard = (
    "info: 'Tacenta.SessionUnitErasureT1.message_no_panic' depends on axioms: [propext,\n"
    " Classical.choice,\n Quot.sound,\n"
    " tacenta_session_unit.alloc.vec.Vec.truncate]")
if text.count(old_guard) != 1:
    raise SystemExit("port-session-erasure-proof: expected axiom guard changed")
text = text.replace(old_guard, new_guard)

note = (
    "-- Generated by tacenta-proofs/scripts/port-session-erasure-proof.sh from\n"
    "-- Translation/ErasureT1.lean. Do not edit: `port-session-erasure-proof.sh --check`\n"
    "-- regenerates this file and fails on any difference. This count-checked\n"
    "-- port changes only imports, namespaces and the exact axiom-guard wrapping.\n\n"
)
dest.write_text(note + text)
PY

if [ "$check" -eq 0 ]; then
  mv "$tmp" "$dest"
  echo "port-session-erasure-proof: wrote SessionUnitErasureT1.lean"
  exit 0
fi

if ! diff -u "$dest" "$tmp" >/dev/null; then
  diff -u "$dest" "$tmp" | head -40 >&2
  echo "port-session-erasure-proof: committed copy differs; regenerate and rebuild" >&2
  exit 1
fi
echo "port-session-erasure-proof: the committed copy is deterministic"
