#!/usr/bin/env bash
# Generate the complete Session unit's copies of the four ratchet T1/T3 files,
# the composed Triple T1 file and the wire decoder's T1/T3 files.
#
# The source files are themselves deterministic copies made by
# port-unit-proofs.sh.  That gate is run first, so this second port remains a
# checked composition of the leaf proof and two explicit namespace rewrites.
# No theorem statement or proof body is otherwise edited.
set -euo pipefail

cd "$(dirname "$0")/../.."

check=0
if [ "${1:-}" = "--check" ]; then
  check=1
elif [ $# -ne 0 ]; then
  echo "usage: port-session-unit-proofs.sh [--check]" >&2
  exit 1
fi

bash tacenta-proofs/scripts/port-unit-proofs.sh --check >/dev/null

src=tacenta-proofs/translation/Translation
out="$src"
tmp=""
cleanup() { [ -n "$tmp" ] && rm -rf "$tmp"; return 0; }
trap cleanup EXIT INT TERM
if [ "$check" -eq 1 ]; then
  tmp=$(mktemp -d)
  out="$tmp"
fi

python3 - "$src" "$out" <<'PY'
from pathlib import Path
import sys

src, out = map(Path, sys.argv[1:3])

jobs = [
    ("UnitT1.lean", "SessionUnitT1.lean", {
        "Tacenta.UnitT1": ("Tacenta.SessionUnitT1", 1),
    }),
    ("UnitSpqrT1.lean", "SessionUnitSpqrT1.lean", {
        "Translation.UnitT1": ("Translation.SessionUnitT1", 1),
        "Tacenta.UnitSpqrT1": ("Tacenta.SessionUnitSpqrT1", 2),
    }),
    ("UnitT3.lean", "SessionUnitT3.lean", {
        "Translation.UnitT1": ("Translation.SessionUnitT1", 1),
        "Tacenta.UnitT1": ("Tacenta.SessionUnitT1", 48),
        "Tacenta.UnitT3": ("Tacenta.SessionUnitT3", 2),
    }),
    ("UnitSpqrT3.lean", "SessionUnitSpqrT3.lean", {
        "Translation.UnitSpqrT1": ("Translation.SessionUnitSpqrT1", 1),
        "Tacenta.UnitT1": ("Tacenta.SessionUnitT1", 1),
        "Tacenta.UnitSpqrT1": ("Tacenta.SessionUnitSpqrT1", 44),
        "Tacenta.UnitSpqrT3": ("Tacenta.SessionUnitSpqrT3", 2),
        "port-unit-proofs.sh": ("port-session-unit-proofs.sh", 1),
    }),
]

def replace_exact(text, old, new, expected, origin):
    found = text.count(old)
    if found != expected:
        raise SystemExit(
            f"port-session-unit-proofs: {origin}: {old!r} occurs {found} "
            f"time(s), expected {expected}; inspect the source port before "
            "changing this count")
    return text.replace(old, new)

for origin, dest, substitutions in jobs:
    text = (src / origin).read_text()
    marker = "\n\nimport "
    if not text.startswith("-- Generated by tacenta-proofs/scripts/port-unit-proofs.sh"):
        raise SystemExit(f"port-session-unit-proofs: {origin} lost its generated header")
    split = text.find(marker)
    if split < 0:
        raise SystemExit(f"port-session-unit-proofs: {origin} has no import after its header")
    text = text[split + 2:]
    text = replace_exact(text, "Translation.TacentaTripleUnit",
                         "Translation.TacentaSessionUnit", 1, origin)
    text = replace_exact(text, "tacenta_triple_unit", "tacenta_session_unit", 2, origin)
    three_leaf = text.count("three-leaf translation unit")
    text = text.replace("three-leaf translation unit", "eight-leaf Session translation unit")
    for old, (new, expected) in substitutions.items():
        text = replace_exact(text, old, new, expected, origin)
    note = (
        "-- Generated by tacenta-proofs/scripts/port-session-unit-proofs.sh from\n"
        f"-- Translation/{origin}. Do not edit: `port-session-unit-proofs.sh --check`\n"
        "-- regenerates this file and fails on any difference. The source is itself\n"
        "-- held byte-for-byte to its leaf proof by port-unit-proofs.sh. This port\n"
        "-- changes only imports and the generated unit/proof namespaces.\n"
        f"-- Reworded {three_leaf} explanatory reference(s) to name this unit.\n\n"
    )
    (out / dest).write_text(note + text)
print(f"port-session-unit-proofs: {dest} (from {origin})")

# UnitTripleT1 is already a hand-written composition proof over the three-leaf
# unit.  The complete Session unit embeds those same three leaves, so its proof
# body is reusable after exact generated/proof namespace rewrites.  Unlike the
# four jobs above, this source is not itself generated by port-unit-proofs.sh.
origin = "UnitTripleT1.lean"
dest = "SessionUnitTripleT1.lean"
text = (src / origin).read_text()
for old, new, expected in [
    ("Translation.TacentaTripleUnit", "Translation.TacentaSessionUnit", 1),
    ("tacenta_triple_unit", "tacenta_session_unit", 3),
    ("UnitTripleT1", "SessionUnitTripleT1", 2),
    ("UnitSpqrT1", "SessionUnitSpqrT1", 46),
    ("UnitT1", "SessionUnitT1", 39),
    ("three-leaf translation unit", "eight-leaf Session translation unit", 1),
    ("Translation/TacentaTripleUnit.lean", "Translation/TacentaSessionUnit.lean", 1),
    ("tacenta-core/triple-unit", "tacenta-core/session-unit", 1),
]:
    text = replace_exact(text, old, new, expected, origin)
note = (
    "-- Generated by tacenta-proofs/scripts/port-session-unit-proofs.sh from\n"
    f"-- Translation/{origin}. Do not edit: `port-session-unit-proofs.sh --check`\n"
    "-- regenerates this file and fails on any difference. This port changes\n"
    "-- only the generated unit and proof namespaces.\n\n"
)
(out / dest).write_text(note + text)
print(f"port-session-unit-proofs: {dest} (from {origin})")

# UnitTripleT3 is the hand-written composition of the classical and sparse
# refinement proofs over UnitTripleT1.  The Session unit embeds the same three
# leaves, so keep a count-checked namespace-only port beside its T1 twin.
origin = "UnitTripleT3.lean"
dest = "SessionUnitTripleT3.lean"
text = (src / origin).read_text()
for old, new, expected in [
    ("Translation.TacentaTripleUnit", "Translation.TacentaSessionUnit", 1),
    ("Translation.UnitTripleT1", "Translation.SessionUnitTripleT1", 1),
    ("Translation.UnitT3", "Translation.SessionUnitT3", 1),
    ("Translation.UnitSpqrT3", "Translation.SessionUnitSpqrT3", 1),
    ("tacenta_triple_unit", "tacenta_session_unit", 2),
    ("Tacenta.UnitTripleT3", "Tacenta.SessionUnitTripleT3", 3),
    ("Tacenta.UnitTripleT1", "Tacenta.SessionUnitTripleT1", 4),
    ("Tacenta.UnitT3", "Tacenta.SessionUnitT3", 30),
    ("Tacenta.UnitSpqrT3", "Tacenta.SessionUnitSpqrT3", 40),
    ("Tacenta.UnitT1", "Tacenta.SessionUnitT1", 9),
    ("Tacenta.UnitSpqrT1", "Tacenta.SessionUnitSpqrT1", 10),
    ("three-leaf translation unit", "eight-leaf Session translation unit", 1),
]:
    text = replace_exact(text, old, new, expected, origin)
note = (
    "-- Generated by tacenta-proofs/scripts/port-session-unit-proofs.sh from\n"
    f"-- Translation/{origin}. Do not edit: `port-session-unit-proofs.sh --check`\n"
    "-- regenerates this file and fails on any difference. This port changes\n"
    "-- only the generated unit and proof namespaces.\n\n"
)
(out / dest).write_text(note + text)
print(f"port-session-unit-proofs: {dest} (from {origin})")

# WireT1 is a hand-written leaf proof rather than a generated three-leaf port.
# Its proof body is still reusable byte-for-byte because the Session unit
# embeds the same wire source.  Keep the three namespace rewrites exact.
origin = "WireT1.lean"
dest = "SessionUnitWireT1.lean"
text = (src / origin).read_text()
text = replace_exact(text, "Translation.TacentaWire",
                     "Translation.TacentaSessionUnit", 1, origin)
text = replace_exact(text, "Tacenta.WireT1",
                     "Tacenta.SessionUnitWireT1", 10, origin)
text = replace_exact(text, "open tacenta_wire",
                     "open tacenta_session_unit.tacenta_wire", 1, origin)
note = (
    "-- Generated by tacenta-proofs/scripts/port-session-unit-proofs.sh from\n"
    f"-- Translation/{origin}. Do not edit: `port-session-unit-proofs.sh --check`\n"
    "-- regenerates this file and fails on any difference. This port changes\n"
    "-- only the generated unit and proof namespaces.\n\n"
)
(out / dest).write_text(note + text)
print(f"port-session-unit-proofs: {dest} (from {origin})")

# WireT3 proves exact decoder behaviour over the same generated wire source.
# Port it with the T1 dependency so lifecycle receive can reuse the canonical
# decoder relation without hand-copying any proof.
origin = "WireT3.lean"
dest = "SessionUnitWireT3.lean"
text = (src / origin).read_text()
for old, new, expected in [
    ("Translation.TacentaWire", "Translation.TacentaSessionUnit", 1),
    ("Translation.WireT1", "Translation.SessionUnitWireT1", 1),
    ("Tacenta.WireT3", "Tacenta.SessionUnitWireT3", 6),
    ("Tacenta.WireT1", "Tacenta.SessionUnitWireT1", 7),
    ("open tacenta_wire", "open tacenta_session_unit.tacenta_wire", 1),
]:
    text = replace_exact(text, old, new, expected, origin)
note = (
    "-- Generated by tacenta-proofs/scripts/port-session-unit-proofs.sh from\n"
    f"-- Translation/{origin}. Do not edit: `port-session-unit-proofs.sh --check`\n"
    "-- regenerates this file and fails on any difference. This port changes\n"
    "-- only imports and the generated unit/proof namespaces.\n\n"
)
(out / dest).write_text(note + text)
print(f"port-session-unit-proofs: {dest} (from {origin})")

# WireInitialT3 reuses WireT3's arithmetic and canonical-key lemmas to prove
# exact successful initial-message decoding.  The Session unit embeds the same
# wire source, so this is another namespace-only, count-checked port.
origin = "WireInitialT3.lean"
dest = "SessionUnitWireInitialT3.lean"
text = (src / origin).read_text()
for old, new, expected in [
    ("Translation.WireT3", "Translation.SessionUnitWireT3", 1),
    ("Tacenta.WireInitialT3", "Tacenta.SessionUnitWireInitialT3", 4),
    ("Tacenta.WireT3", "Tacenta.SessionUnitWireT3", 3),
    ("Tacenta.WireT1", "Tacenta.SessionUnitWireT1", 4),
    ("tacenta_wire", "tacenta_session_unit.tacenta_wire", 2),
]:
    text = replace_exact(text, old, new, expected, origin)
note = (
    "-- Generated by tacenta-proofs/scripts/port-session-unit-proofs.sh from\n"
    f"-- Translation/{origin}. Do not edit: `port-session-unit-proofs.sh --check`\n"
    "-- regenerates this file and fails on any difference. This port changes\n"
    "-- only imports and the generated unit/proof namespaces.\n\n"
)
(out / dest).write_text(note + text)
print(f"port-session-unit-proofs: {dest} (from {origin})")
PY

files=(SessionUnitT1.lean SessionUnitSpqrT1.lean SessionUnitT3.lean SessionUnitSpqrT3.lean SessionUnitTripleT1.lean SessionUnitTripleT3.lean SessionUnitWireT1.lean SessionUnitWireT3.lean SessionUnitWireInitialT3.lean)
if [ "$check" -eq 0 ]; then
  echo "port-session-unit-proofs: wrote the Session unit ratchet proof copies"
  exit 0
fi

fail=0
for file in "${files[@]}"; do
  if ! diff -u "$src/$file" "$tmp/$file" >/dev/null; then
    fail=1
    diff -u "$src/$file" "$tmp/$file" | head -40 >&2
  fi
done
if [ "$fail" -ne 0 ]; then
  echo "port-session-unit-proofs: committed copies differ; regenerate and rebuild" >&2
  exit 1
fi
echo "port-session-unit-proofs: the committed copies are deterministic"
