#!/usr/bin/env bash
# Port ImportInv's classical and sparse ratchet sections onto the Session unit.
# The Braid section has a different concrete-erasure obligation and is excluded.
set -euo pipefail

cd "$(dirname "$0")/../.."

check=0
if [ "${1:-}" = "--check" ]; then
  check=1
elif [ $# -ne 0 ]; then
  echo "usage: port-session-ratchet-import-proof.sh [--check]" >&2
  exit 1
fi

src=tacenta-proofs/translation/Translation/ImportInv.lean
dest=tacenta-proofs/translation/Translation/SessionUnitRatchetImportInv.lean
tmp=$(mktemp)
cleanup() { rm -f "$tmp"; }
trap cleanup EXIT INT TERM

python3 - "$src" "$tmp" <<'PY'
from pathlib import Path
import sys

src, dest = map(Path, sys.argv[1:3])
text = src.read_text()
marker = '/-! # `tacenta-braid`'
if text.count(marker) != 1:
    raise SystemExit("port-session-ratchet-import-proof: Braid section marker changed")
text = text[:text.index(marker)]

substitutions = [
    ("import Translation.T3", "import Translation.SessionUnitT3", 1),
    ("import Translation.SpqrT3", "import Translation.SessionUnitSpqrT3", 1),
    ("import Translation.BraidT3\n", "", 1),
    ("Tacenta.ImportInv", "Tacenta.SessionUnitRatchetImportInv", 1),
    ("Tacenta.SpqrT1", "Tacenta.SessionUnitSpqrT1", 8),
    ("Tacenta.SpqrT3", "Tacenta.SessionUnitSpqrT3", 2),
    ("Tacenta.T3", "Tacenta.SessionUnitT3", 17),
    ("Tacenta.T1", "Tacenta.SessionUnitT1", 20),
    ("open tacenta_ratchet", "open tacenta_session_unit.tacenta_ratchet", 1),
    ("open tacenta_spqr", "open tacenta_session_unit.tacenta_spqr", 1),
]
for old, new, expected in substitutions:
    found = text.count(old)
    if found != expected:
        raise SystemExit(
            f"port-session-ratchet-import-proof: {old!r} occurs {found} "
            f"time(s), expected {expected}; inspect the source proof before changing this count")
    text = text.replace(old, new)

note = (
    "-- Generated by tacenta-proofs/scripts/port-session-ratchet-import-proof.sh from\n"
    "-- the pre-Braid sections of Translation/ImportInv.lean. Do not edit:\n"
    "-- `port-session-ratchet-import-proof.sh --check` regenerates this file and\n"
    "-- fails on any difference. The Braid section is deliberately separate because\n"
    "-- erasure operations are concrete, rather than opaque, in the Session unit.\n\n"
)
dest.write_text(note + text + "\nend Tacenta.SessionUnitRatchetImportInv\n")
PY

if [ "$check" -eq 0 ]; then
  mv "$tmp" "$dest"
  echo "port-session-ratchet-import-proof: wrote SessionUnitRatchetImportInv.lean"
  exit 0
fi

if ! diff -u "$dest" "$tmp" >/dev/null; then
  diff -u "$dest" "$tmp" | head -40 >&2
  echo "port-session-ratchet-import-proof: committed copy differs; regenerate and rebuild" >&2
  exit 1
fi
echo "port-session-ratchet-import-proof: the committed copy is deterministic"
