#!/usr/bin/env bash
# Port ImportInv's Braid section onto the complete Session unit.
set -euo pipefail

cd "$(dirname "$0")/../.."

check=0
if [ "${1:-}" = "--check" ]; then
  check=1
elif [ $# -ne 0 ]; then
  echo "usage: port-session-braid-import-proof.sh [--check]" >&2
  exit 1
fi

src=tacenta-proofs/translation/Translation/ImportInv.lean
dest=tacenta-proofs/translation/Translation/SessionUnitBraidImportInv.lean
tmp=$(mktemp)
cleanup() { rm -f "$tmp"; }
trap cleanup EXIT INT TERM

python3 - "$src" "$tmp" <<'PY'
from pathlib import Path
import sys

src, dest = map(Path, sys.argv[1:3])
text = src.read_text()
start_marker = '/-! # `tacenta-braid`'
end_marker = '\nend Braid'
if text.count(start_marker) != 1:
    raise SystemExit("port-session-braid-import-proof: Braid section marker changed")
start = text.index(start_marker)
end = text.index(end_marker, start) + len(end_marker)
body = text[start:end]
substitutions = [
    ("Tacenta.BraidT1", "Tacenta.SessionUnitBraidT1", 5),
    ("open tacenta_braid", "open tacenta_session_unit.tacenta_braid", 1),
]
for old, new, expected in substitutions:
    found = body.count(old)
    if found != expected:
        raise SystemExit(
            f"port-session-braid-import-proof: {old!r} occurs {found} "
            f"time(s), expected {expected}; inspect the source proof before changing this count")
    body = body.replace(old, new)

header = """-- Generated by tacenta-proofs/scripts/port-session-braid-import-proof.sh
-- from the Braid section of Translation/ImportInv.lean. Do not edit: the
-- script's `--check` mode regenerates this count-checked aggregate proof.

import Translation.SessionUnitBraidT3
import Translation.SessionUnitRatchetImportInv

open Aeneas Aeneas.Std Result

namespace Tacenta.SessionUnitBraidImportInv

-- Reuse only the generic Result-bind peeling lemmas from the ratchet import
-- port. The Braid declarations below are all in this file's namespace.
open Tacenta.SessionUnitRatchetImportInv

"""

guards = r'''

/-!
The complete unit makes the erasure implementation concrete. These exact
pins therefore omit the standalone Braid translation's opaque erasure
declarations and expose only the generated unit's remaining boundaries.
-/

/--
info: 'Tacenta.SessionUnitBraidImportInv.Braid.from_bytes_establishes_inv' depends on axioms: [propext,
 Classical.choice,
 Quot.sound,
 tacenta_session_unit.tacenta_kem.CT1_LEN,
 tacenta_session_unit.tacenta_kem.CT2_LEN,
 tacenta_session_unit.tacenta_kem.EK_VECTOR_LEN,
 tacenta_session_unit.tacenta_kem.EncapsState,
 tacenta_session_unit.tacenta_kem.HEADER_LEN,
 tacenta_session_unit.tacenta_kem.IncrementalKeyPair,
 tacenta_session_unit.tacenta_kem.validate_ek,
 tacenta_session_unit.tacenta_kem.EncapsState.from_bytes,
 tacenta_session_unit.tacenta_kem.IncrementalKeyPair.ek_vector,
 tacenta_session_unit.tacenta_kem.IncrementalKeyPair.from_bytes,
 tacenta_session_unit.tacenta_kem.IncrementalKeyPair.header,
 tacenta_session_unit.core.num.Usize.div_ceil]
-/
#guard_msgs in
#print axioms Tacenta.SessionUnitBraidImportInv.Braid.from_bytes_establishes_inv

/--
info: 'Tacenta.SessionUnitBraidImportInv.Braid.decoded_receive_no_panic' depends on axioms: [propext,
 Classical.choice,
 Quot.sound,
 tacenta_session_unit.tacenta_kdf.hkdf_sha256,
 tacenta_session_unit.tacenta_kdf.hmac_sha256,
 tacenta_session_unit.tacenta_kem.CT1_LEN,
 tacenta_session_unit.tacenta_kem.CT2_LEN,
 tacenta_session_unit.tacenta_kem.EK_VECTOR_LEN,
 tacenta_session_unit.tacenta_kem.EncapsState,
 tacenta_session_unit.tacenta_kem.HEADER_LEN,
 tacenta_session_unit.tacenta_kem.IncrementalKeyPair,
 tacenta_session_unit.tacenta_kem.encapsulate2,
 tacenta_session_unit.tacenta_kem.validate_ek,
 tacenta_session_unit.zeroize.Zeroizing,
 tacenta_session_unit.tacenta_kem.EncapsState.from_bytes,
 tacenta_session_unit.tacenta_kem.IncrementalKeyPair.decapsulate,
 tacenta_session_unit.tacenta_kem.IncrementalKeyPair.ek_vector,
 tacenta_session_unit.tacenta_kem.IncrementalKeyPair.from_bytes,
 tacenta_session_unit.tacenta_kem.IncrementalKeyPair.header,
 tacenta_session_unit.zeroize.Zeroizing.new,
 tacenta_session_unit.Array.Insts.ZeroizeZeroize.zeroize,
 tacenta_session_unit.alloc.vec.Vec.truncate,
 tacenta_session_unit.core.num.Usize.div_ceil,
 tacenta_session_unit.zeroize.Zeroize.Blanket.zeroize,
 tacenta_session_unit.tacenta_kem.EncapsState.Insts.CoreCloneClone.clone,
 tacenta_session_unit.tacenta_kem.IncrementalKeyPair.Insts.CoreCloneClone.clone,
 tacenta_session_unit.zeroize.Zeroizing.Insts.CoreOpsDerefDeref.deref,
 tacenta_session_unit.core.option.Option.Insts.CoreCloneClone.clone,
 tacenta_session_unit.core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.get,
 tacenta_session_unit.core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.get_mut,
 tacenta_session_unit.core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.get_unchecked,
 tacenta_session_unit.core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.get_unchecked_mut,
 tacenta_session_unit.core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.index,
 tacenta_session_unit.core.ops.range.RangeFull.Insts.CoreSliceIndexSliceIndexSliceSlice.index_mut]
-/
#guard_msgs in
#print axioms Tacenta.SessionUnitBraidImportInv.Braid.decoded_receive_no_panic

end Tacenta.SessionUnitBraidImportInv
'''
dest.write_text(header + body + guards)
PY

if [ "$check" -eq 0 ]; then
  mv "$tmp" "$dest"
  echo "port-session-braid-import-proof: wrote SessionUnitBraidImportInv.lean"
  exit 0
fi

if ! diff -u "$dest" "$tmp" >/dev/null; then
  diff -u "$dest" "$tmp" | head -40 >&2
  echo "port-session-braid-import-proof: committed copy differs; regenerate and rebuild" >&2
  exit 1
fi
echo "port-session-braid-import-proof: the committed copy is deterministic"
