#!/usr/bin/env bash
# Generate the three-leaf unit's copies of the two leaf panic-freedom proofs.
#
# `Translation/T1.lean` proves the Double Ratchet panic-free and
# `Translation/SpqrT1.lean` the sparse ratchet, both about the constants in
# `Translation/TacentaRatchet.lean` and `Translation/TacentaSpqr.lean` -- the
# translations of those crates on their own. The three-leaf unit
# (`Translation/TacentaTripleUnit.lean`, assembled by
# `assemble-triple-unit.sh`) translates the same Rust as one crate, so it
# declares different constants with the same shape, one namespace deeper. A
# theorem about `tacenta_ratchet.State.send` says nothing about
# `tacenta_triple_unit.tacenta_ratchet.State.send`; Lean has no reason to
# connect them, and there is no import that would let one stand for the other.
# The proofs have to exist twice.
#
# That is a duplication we cannot remove, so this script makes it one that
# cannot drift instead. The copies are derived, not maintained: every
# difference between a leaf proof and its unit copy is one of the rewrites
# below, and `--check` regenerates and diffs so that an edit to either side
# fails CI.
#
# ## What the rewrites are
#
# Fewer than the duplication suggests. The leaf proofs never write a
# translated name in qualified form -- they `open` the crate's namespace and
# use short names throughout -- so pointing them at the unit is:
#
#   1. the import: the leaf translation becomes the unit's;
#   2. the namespace: `Tacenta.T1` becomes `Tacenta.UnitT1`, so both can be
#      built in one package without colliding;
#   3. the `open`: the crate namespace becomes the unit's outer namespace plus
#      the crate namespace inside it. The outer one is needed on its own too,
#      for the trusted key-derivation names, which sit beside the leaves rather
#      than inside either.
#
# Every proof body, every hypothesis, every stated bound is copied unchanged.
# That is the point: if a body needed changing, the two translations would not
# be of the same Rust, and the whole exercise would be unsound.
#
# ## What is deliberately not copied
#
# The `#print axioms` pins. Their expected text names the leaves' constants,
# and the wrapping of a pinned axiom list is Lean's pretty-printer's business,
# not something to reproduce with a substitution. The unit's pins are written
# by hand in `Translation/UnitPins.lean`, which is where the claim that the
# port preserved each theorem's trust base exactly is made and checked. How
# many pins each leaf file carries is asserted here, so that adding one to a
# leaf and not to the unit fails rather than passing quietly.
#
# ## Usage
#
#   port-unit-proofs.sh            regenerate the copies
#   port-unit-proofs.sh --check    regenerate into a temporary directory and
#                                  diff; exit non-zero on any difference
#
# ## That `--check` can fail
#
# Checked rather than assumed, last on 2026-09-10, three ways: a hand edit
# appended to a generated copy, an edit appended to a leaf proof with the copy
# left alone, and a rewrite target moved in a leaf so that its pattern matches
# nothing. All three exit non-zero, the third naming the rewrite and telling
# the reader to update the rule rather than the count. Redo this after changing
# the script.
#
# Run from any directory. Needs no toolchain.
set -euo pipefail

cd "$(dirname "$0")/../.."

check=0
if [ "${1:-}" = "--check" ]; then
  check=1
elif [ $# -ne 0 ]; then
  echo "port-unit-proofs: unknown argument: $1" >&2
  echo "usage: port-unit-proofs.sh [--check]" >&2
  exit 1
fi

src=tacenta-proofs/translation/Translation
out="$src"
tmp=""
cleanup() { [ -n "$tmp" ] && rm -rf "$tmp"; return 0; }
trap cleanup EXIT INT TERM
if [ "$check" -eq 1 ]; then
  tmp=$(mktemp -d)
  out="$tmp"
fi

python3 - "$src" "$out" <<'PYEOF'
import sys, os, re

src, out = sys.argv[1:3]

NOTE = """\
-- Generated by tacenta-proofs/scripts/port-unit-proofs.sh from
-- Translation/{origin}. Do not edit: `port-unit-proofs.sh --check`
-- regenerates this file and fails on any difference.
--
-- This is {origin} restated about the three-leaf translation unit, whose
-- constants are different constants from the ones {origin} is about. Only the
-- imports, the namespace and the `open` differ, plus any stepping-rule erasure
-- this script inserts and explains beside it; every proof body is the same text.
-- The `#print axioms` pins are in Translation/UnitPins.lean.

"""


def rewrite(text, subs, origin):
    """Apply each (pattern, replacement, expected count). A rewrite that
    matches a different number of times than expected is a failure, not
    something to paper over: it means the leaf proof moved in a way this
    script does not understand, and the copy would silently stop being the
    same theorem."""
    for pattern, repl, expected in subs:
        text, n = re.subn(pattern, repl, text, flags=re.M)
        if n != expected:
            sys.stderr.write(
                f"port-unit-proofs: ERROR: in {origin}, the rewrite "
                f"{pattern!r} matched {n} time(s), expected {expected}. The "
                f"leaf proof has changed in a way this script does not "
                f"understand; read it and update the rewrite rather than the "
                f"count.\n")
            sys.exit(1)
    return text


def strip_pins(text, origin, expected):
    """Remove the `#print axioms` pins. They are re-stated by hand in
    UnitPins.lean, against the unit's own names.

    `expected` is how many this file carries. `T1.lean` pins its three
    headline theorems; `SpqrT1.lean` pins none of its own -- its
    `receive_no_panic` is pinned in `ImportInv.lean`, through the composed
    `decoded_receive_no_panic`. Either number changing is a change to what the
    repository treats as load-bearing, so it fails here and the author decides
    where the unit's version of the new pin belongs."""
    text, n_block = re.subn(
        r"/--\s*\ninfo:.*?-/\n#guard_msgs in\n#print axioms [^\n]*\n",
        "", text, flags=re.S)
    text, n_line = re.subn(
        r"/-- info:[^\n]*-/\n#guard_msgs in\n#print axioms [^\n]*\n",
        "", text)
    found = n_block + n_line
    if found != expected:
        sys.stderr.write(
            f"port-unit-proofs: ERROR: {origin} carries {found} `#print "
            f"axioms` pin(s), expected {expected}. A pin added or removed "
            f"changes what is claimed; UnitPins.lean has to be updated to "
            f"match, and then this count.\n")
        sys.exit(1)
    # Only a line that begins with the command is a pin. Prose may name
    # `#print axioms` -- both refinement files do, at T3.lean:1691 and
    # SpqrT3.lean:1998 -- and a substring test refused them as leftover pins.
    # Anchoring on the start of the line still catches a real pin in a format
    # the strip patterns above do not match, which is what this check is for.
    if re.search(r"^[ \t]*(?:#guard_msgs|#print axioms)\b", text, re.M):
        sys.stderr.write(
            f"port-unit-proofs: ERROR: {origin} still has a `#guard_msgs` or "
            f"`#print axioms` after the pins were removed.\n")
        sys.exit(1)
    # Removing a trailing pin block can leave the section comment above it
    # dangling; collapse runs of blank lines it opens up.
    return re.sub(r"\n{3,}", "\n\n", text)


JOBS = [
    # `T1.lean` opens `Tacenta.T1` at the top and never closes it, so there is
    # no `end` to rewrite; `SpqrT1.lean` closes its own on the last line.
    dict(
        origin="T1.lean",
        dest="UnitT1.lean",
        pins=3,
        subs=[
            (r"^import Translation\.TacentaRatchet$",
             "import Translation.TacentaTripleUnit", 1),
            (r"^namespace Tacenta\.T1$", "namespace Tacenta.UnitT1", 1),
            (r"^open tacenta_ratchet$",
             "open tacenta_triple_unit tacenta_triple_unit.tacenta_ratchet", 1),
        ],
    ),
    dict(
        origin="SpqrT1.lean",
        dest="UnitSpqrT1.lean",
        pins=0,
        subs=[
            (r"^import Translation\.TacentaSpqr$",
             "import Translation.TacentaTripleUnit", 1),
            (r"^import Translation\.T1$", "import Translation.UnitT1", 1),
            (r"^namespace Tacenta\.SpqrT1$", "namespace Tacenta.UnitSpqrT1", 1),
            (r"^end Tacenta\.SpqrT1$", "end Tacenta.UnitSpqrT1", 1),
            (r"^open tacenta_spqr$",
             "open tacenta_triple_unit tacenta_triple_unit.tacenta_spqr", 1),
        ],
    ),
    # `T3.lean` is the classical ratchet's refinement of the model. It opens one
    # name from the panic-freedom namespace, which moves with it; its other 45
    # references to `Tacenta.T1.` are qualified and follow the global rename
    # below, four of them `attribute [-step]` erasures of rules `UnitT1.lean`
    # also registers. Its three pins are restated in `UnitPins.lean`.
    dict(
        origin="T3.lean",
        dest="UnitT3.lean",
        pins=3,
        subs=[
            (r"^import Translation\.TacentaRatchet$",
             "import Translation.TacentaTripleUnit", 1),
            (r"^import Translation\.T1$", "import Translation.UnitT1", 1),
            (r"^namespace Tacenta\.T3$", "namespace Tacenta.UnitT3", 1),
            (r"^end Tacenta\.T3$", "end Tacenta.UnitT3", 1),
            (r"^open tacenta_ratchet$",
             "open tacenta_triple_unit tacenta_triple_unit.tacenta_ratchet", 1),
            (r"^open Tacenta\.T1 \(DerivedKeysModel\)$",
             "open Tacenta.UnitT1 (DerivedKeysModel)", 1),
        ],
    ),
    # `SpqrT3.lean` is the sparse ratchet's refinement. It pins nothing of its
    # own. Its eight qualified `tacenta_spqr.*` names are left as written: under
    # `open tacenta_triple_unit` they resolve to the unit's constants, as the 49
    # qualified names in `UnitTripleT1.lean` did.
    dict(
        origin="SpqrT3.lean",
        dest="UnitSpqrT3.lean",
        pins=0,
        subs=[
            (r"^import Translation\.TacentaSpqr$",
             "import Translation.TacentaTripleUnit", 1),
            (r"^import Translation\.SpqrT1$", "import Translation.UnitSpqrT1", 1),
            (r"^namespace Tacenta\.SpqrT3$", "namespace Tacenta.UnitSpqrT3", 1),
            (r"^end Tacenta\.SpqrT3$", "end Tacenta.UnitSpqrT3", 1),
            (r"^open tacenta_spqr$",
             "open tacenta_triple_unit tacenta_triple_unit.tacenta_spqr\n"
             "\n"
             "-- Inserted by port-unit-proofs.sh: the one line here that is neither\n"
             "-- SpqrT3.lean's own text nor a rename. On the unit the classical and\n"
             "-- sparse ratchets share one set of `zeroize` constants, so two stepping\n"
             "-- rules UnitT1.lean registers for them now match goals in this file that,\n"
             "-- in the leaf island, they could never reach. Both demand\n"
             "-- `UnitT1.ZeroizingTotal`, which no hypothesis here provides, and both say\n"
             "-- only that the call returned -- the reason T3.lean already removes the\n"
             "-- projection rule for itself. Removing them restores the stepping\n"
             "-- environment SpqrT3.lean was proved in. No statement and no proof body\n"
             "-- changes.\n"
             "attribute [-step] Tacenta.UnitT1.zeroizing_new_step "
             "Tacenta.UnitT1.zeroizing_deref_step", 1),
        ],
    ),
]

for job in JOBS:
    origin, dest = job["origin"], job["dest"]
    text = open(os.path.join(src, origin)).read()
    text = rewrite(text, job["subs"], origin)
    # Qualified references to the leaf namespace, in prose and in terms.
    text = re.sub(r"(?<![\w.])Tacenta\.T1\.", "Tacenta.UnitT1.", text)
    text = re.sub(r"(?<![\w.])Tacenta\.SpqrT1\.", "Tacenta.UnitSpqrT1.", text)
    # The refinement namespaces. Neither pattern matches inside the other, nor
    # inside `Tacenta.TripleT3.`, since none of those contains the other's text.
    text = re.sub(r"(?<![\w.])Tacenta\.T3\.", "Tacenta.UnitT3.", text)
    text = re.sub(r"(?<![\w.])Tacenta\.SpqrT3\.", "Tacenta.UnitSpqrT3.", text)
    text = strip_pins(text, origin, job["pins"])
    open(os.path.join(out, dest), "w").write(NOTE.format(origin=origin) + text)
    print(f"port-unit-proofs: {dest} (from {origin})")
PYEOF

if [ "$check" -eq 0 ]; then
  echo "port-unit-proofs: wrote the unit's copies of the leaf panic-freedom proofs"
  echo "port-unit-proofs: next, build the translation package; UnitPins.lean holds"
  echo "port-unit-proofs: the axiom pins and will fail if a trust base moved"
  exit 0
fi

fail=0
for f in UnitT1.lean UnitSpqrT1.lean UnitT3.lean UnitSpqrT3.lean; do
  if ! diff -u "$src/$f" "$tmp/$f" > /dev/null; then
    if [ "$fail" -eq 0 ]; then
      echo "port-unit-proofs: ERROR: the committed copies are not what the leaf" >&2
      echo "  proofs port to. Either a copy was edited by hand, or a leaf proof" >&2
      echo "  changed and nobody re-ported. Regenerate with" >&2
      echo "  tacenta-proofs/scripts/port-unit-proofs.sh and rebuild." >&2
    fi
    fail=1
    diff -u "$src/$f" "$tmp/$f" | head -40 >&2
  fi
done
if [ "$fail" -ne 0 ]; then
  exit 1
fi
echo "port-unit-proofs: the committed copies are what the leaf proofs port to"
