#!/usr/bin/env bash
# Port Braid T1 onto the complete Session translation unit.
set -euo pipefail

cd "$(dirname "$0")/../.."

check=0
if [ "${1:-}" = "--check" ]; then
  check=1
elif [ $# -ne 0 ]; then
  echo "usage: port-session-braid-proof.sh [--check]" >&2
  exit 1
fi

src=tacenta-proofs/translation/Translation/BraidT1.lean
dest=tacenta-proofs/translation/Translation/SessionUnitBraidT1.lean
tmp=$(mktemp)
cleanup() { rm -f "$tmp"; }
trap cleanup EXIT INT TERM

python3 - "$src" "$tmp" <<'PY'
from pathlib import Path
import sys

src, dest = map(Path, sys.argv[1:3])
text = src.read_text()
substitutions = [
    ("import Translation.TacentaBraid\nimport Translation.SessionT1", """import Translation.TacentaSessionUnit
import Translation.SessionUnitSessionT1
import Translation.SessionUnitErasureT1

-- The complete unit imports proof modules whose global `step` rules target
-- the same generated primitives. These rules are intentionally narrower
-- than Braid's calls: the erasure decoder appends exactly 32-byte slices and
-- the ratchet uses its own `ZeroizingTotal` boundary. Leaving them registered
-- makes `step*` select an inapplicable side condition in this aggregate proof.
attribute [-step] Tacenta.SessionUnitErasureT1.extend_slice32_spec
attribute [-step] Tacenta.SessionUnitT1.zeroizing_new_step
attribute [-step] Tacenta.SessionUnitT1.zeroizing_deref_step""", 1),
    ("Tacenta.BraidT1", "Tacenta.SessionUnitBraidT1", 6),
    ("open tacenta_braid", "open tacenta_session_unit.tacenta_braid", 1),
    ("tacenta_erasure.", "tacenta_session_unit.tacenta_erasure.", 28),
    ("tacenta_kem.", "tacenta_session_unit.tacenta_kem.", 39),
    ("tacenta_kdf.", "tacenta_session_unit.tacenta_kdf.", 6),
    ("rand_core_1.", "tacenta_session_unit.rand_core_1.", 10),
    ("zeroize.", "tacenta_session_unit.zeroize.", 24),
    ("Array.Insts.", "tacenta_session_unit.Array.Insts.", 9),
    ("U8.Insts.", "tacenta_session_unit.U8.Insts.", 7),
    ("core.option.", "tacenta_session_unit.core.option.", 2),
    ("core.ops.range.", "tacenta_session_unit.core.ops.range.", 15),
]
for old, new, expected in substitutions:
    found = text.count(old)
    if found != expected:
        raise SystemExit(
            f"port-session-braid-proof: {old!r} occurs {found} time(s), "
            f"expected {expected}; inspect the source proof before changing this count")
    text = text.replace(old, new)

# The erasure operations are concrete inside the complete unit, so the Braid
# entry points no longer depend on the standalone translation's opaque erasure
# declarations. The generated unit exposes two concrete library operations in
# their place. Keep the kernel's exact audit output pinned.
for name, remove, add in [
    ("send_no_panic", [
        "tacenta_session_unit.tacenta_erasure.Decoder",
        "tacenta_session_unit.tacenta_erasure.Encoder",
        "tacenta_session_unit.tacenta_erasure.Encoder.new",
        "tacenta_session_unit.tacenta_erasure.Encoder.next_chunk",
        "tacenta_session_unit.tacenta_erasure.Decoder.Insts.CoreCloneClone.clone",
        "tacenta_session_unit.tacenta_erasure.Encoder.Insts.CoreCloneClone.clone",
    ], ["tacenta_session_unit.core.num.Usize.div_ceil"]),
    ("receive_no_panic", [
        "tacenta_session_unit.tacenta_erasure.Decoder",
        "tacenta_session_unit.tacenta_erasure.Encoder",
        "tacenta_session_unit.tacenta_erasure.Decoder.add_chunk",
        "tacenta_session_unit.tacenta_erasure.Decoder.message",
        "tacenta_session_unit.tacenta_erasure.Decoder.new",
        "tacenta_session_unit.tacenta_erasure.Encoder.new",
        "tacenta_session_unit.tacenta_erasure.Decoder.Insts.CoreCloneClone.clone",
        "tacenta_session_unit.tacenta_erasure.Encoder.Insts.CoreCloneClone.clone",
    ], [
        "tacenta_session_unit.alloc.vec.Vec.truncate",
        "tacenta_session_unit.core.num.Usize.div_ceil",
    ]),
]:
    marker = f"info: 'Tacenta.SessionUnitBraidT1.Braid.{name}' depends on axioms: ["
    start = text.index(marker)
    end = text.index("]\n-/", start)
    block = text[start:end + 1]
    lines = block.splitlines()
    for item in remove:
        target = f" {item},"
        target_last = f" {item}]"
        matches = [i for i, line in enumerate(lines) if line in (target, target_last)]
        if len(matches) != 1:
            raise SystemExit(f"port-session-braid-proof: audit item {item!r} changed")
        lines.pop(matches[0])
    insert_at = next(i for i, line in enumerate(lines)
                     if "zeroize.Zeroize.Blanket.zeroize" in line)
    for item in reversed(add):
        lines.insert(insert_at, f" {item},")
    new_block = "\n".join(lines)
    text = text[:start] + new_block + text[end + 1:]

note = (
    "-- Generated by tacenta-proofs/scripts/port-session-braid-proof.sh from\n"
    "-- Translation/BraidT1.lean. Do not edit: `port-session-braid-proof.sh --check`\n"
    "-- regenerates this file and fails on any difference. This count-checked\n"
    "-- port changes namespaces, pins aggregate tactic rules and audits the\n"
    "-- complete unit's concrete erasure dependencies.\n\n"
)
dest.write_text(note + text)
PY

if [ "$check" -eq 0 ]; then
  mv "$tmp" "$dest"
  echo "port-session-braid-proof: wrote SessionUnitBraidT1.lean"
  exit 0
fi

if ! diff -u "$dest" "$tmp" >/dev/null; then
  diff -u "$dest" "$tmp" | head -40 >&2
  echo "port-session-braid-proof: committed copy differs; regenerate and rebuild" >&2
  exit 1
fi
echo "port-session-braid-proof: the committed copy is deterministic"
