#!/usr/bin/env bash
# Port the PQXDH/session leaf T1 proof onto the complete Session unit.
#
# This is a literal, count-checked namespace port. No theorem statement or
# proof body is otherwise edited. Exact replacement counts make upstream proof
# drift fail closed instead of silently producing a partial port.
set -euo pipefail

cd "$(dirname "$0")/../.."

check=0
if [ "${1:-}" = "--check" ]; then
  check=1
elif [ $# -ne 0 ]; then
  echo "usage: port-session-pqxdh-proof.sh [--check]" >&2
  exit 1
fi

src=tacenta-proofs/translation/Translation/SessionT1.lean
dest=tacenta-proofs/translation/Translation/SessionUnitSessionT1.lean
tmp=$(mktemp)
cleanup() { rm -f "$tmp"; }
trap cleanup EXIT INT TERM

python3 - "$src" "$tmp" <<'PY'
from pathlib import Path
import sys

src, dest = map(Path, sys.argv[1:3])
text = src.read_text()
substitutions = [
    ("Translation.TacentaSession", "Translation.TacentaSessionUnit", 1),
    ("Translation.T1", "Translation.SessionUnitT1", 2),
    ("Tacenta.SessionT1", "Tacenta.SessionUnitSessionT1", 4),
    ("Tacenta.T1", "Tacenta.SessionUnitT1", 1),
    ("open tacenta_session", "open tacenta_session_unit.tacenta_session", 1),
    ("tacenta_kdf.", "tacenta_session_unit.tacenta_kdf.", 3),
    ("zeroize.", "tacenta_session_unit.zeroize.", 22),
    ("alloc.vec.Vec.Insts.ZeroizeZeroize.zeroize",
     "tacenta_session_unit.alloc.vec.Vec.Insts.ZeroizeZeroize.zeroize", 1),
]
for old, new, expected in substitutions:
    found = text.count(old)
    if found != expected:
        raise SystemExit(
            f"port-session-pqxdh-proof: {old!r} occurs {found} time(s), "
            f"expected {expected}; inspect the source proof before changing this count")
    text = text.replace(old, new)
note = (
    "-- Generated by tacenta-proofs/scripts/port-session-pqxdh-proof.sh from\n"
    "-- Translation/SessionT1.lean. Do not edit: `port-session-pqxdh-proof.sh --check`\n"
    "-- regenerates this file and fails on any difference. This count-checked\n"
    "-- port changes only imports and generated/proof namespaces.\n\n"
)
dest.write_text(note + text)
PY

if [ "$check" -eq 0 ]; then
  mv "$tmp" "$dest"
  echo "port-session-pqxdh-proof: wrote SessionUnitSessionT1.lean"
  exit 0
fi

if ! diff -u "$dest" "$tmp" >/dev/null; then
  diff -u "$dest" "$tmp" | head -40 >&2
  echo "port-session-pqxdh-proof: committed copy differs; regenerate and rebuild" >&2
  exit 1
fi
echo "port-session-pqxdh-proof: the committed copy is deterministic"
