#!/bin/sh
# Translate tacenta-core to Lean via Charon and Aeneas, the first stage of the
# T1 (panic-freedom) verification path.
#
# Charon extracts the crate to LLBC, driving the exact rustc nightly it was
# built against; Aeneas translates the LLBC to Lean. The external crates (the
# trusted primitive boundary) are opaque.
#
# It translates the *leaf crate* tacenta-ratchet, not all of tacenta-core: the
# verified zone is isolated there precisely so the translated surface is exactly
# the surface we intend to prove. Translating the whole of tacenta-core pulled
# in orchestration code (closures, slice patterns) that Aeneas does not model,
# failing the run for reasons unrelated to the ratchet. The ratchet itself is
# written to the subset Aeneas models (index loops over Vec, no iterator
# adaptors).
#
# Toolchain: prebuilt nightly binaries in $AENEAS_TOOLS (default
# ~/tools/aeneas-nightly). The scratch output under Generated/aeneas-output is
# gitignored; the translation the proofs are about is *committed* under
# translation/Translation/ and the verification workflow fails if regenerating it here
# produces different files. T1 and T3 are done for all seven crates (see
# CLAIMS.md).
set -eu
# **The pin, and it must match the verification workflow.** Keeping the
# release name here rather than only in the workflow is what makes a local run
# comparable to CI's; a translation produced by a different Aeneas is a
# different translation, and the proofs are about particular generated bytes.
AENEAS_RELEASE="${AENEAS_RELEASE:-nightly-2026.07.22-b1214ca}"
tools="${AENEAS_TOOLS:-$HOME/tools/aeneas-$AENEAS_RELEASE}"

# The default names the pin, and an unpinned directory is refused rather than
# used: two Aeneas builds can differ in the shape of the standard library they
# emit against (`Array.make`'s proof argument, for one), and a translation
# regenerated with a different build differs from the committed one by
# thousands of lines that have nothing to do with the Rust, so the T1 proofs
# fail against it. Override `AENEAS_TOOLS` deliberately if you mean to.
for bin in charon aeneas; do
  if [ ! -x "$tools/$bin" ]; then
    echo "missing $tools/$bin" >&2
    echo "" >&2
    echo "This script needs the *pinned* Aeneas release, $AENEAS_RELEASE," >&2
    echo "the one the verification workflow downloads and checksums." >&2
    echo "A different build produces a different translation, which the" >&2
    echo "proofs are not about." >&2
    echo "" >&2
    echo "The release ships linux-x86_64 only, so on another platform the" >&2
    echo "honest answer is to let CI do this: the verification workflow runs on every" >&2
    echo "push against a dedicated runner." >&2
    exit 1
  fi
done

here=$(cd "$(dirname "$0")/.." && pwd)
core="$here/../tacenta-core"
out="$here/Generated/aeneas-output"
# Stage the results where the translation lake package builds them (see
# tacenta-proofs/translation/lakefile.toml).
staged="$here/translation/Translation"
mkdir -p "$out" "$staged"

# Each verified zone is a leaf crate: the crate directory, the package name, and
# the Lean module Aeneas writes for it. They are translated independently, so a
# construct one of them cannot express never reaches the other.
translate() {
  leaf_dir="$1"
  package="$2"
  llbc="$3"
  module="$4"

  echo "run-aeneas: charon extracting $package (a verified zone) to LLBC"
  # The leaf crate is a workspace member, so charon runs there but writes the
  # LLBC to the workspace root.
  ( cd "$core/$leaf_dir" && "$tools/charon" cargo --preset=aeneas -- --package "$package" )

  echo "run-aeneas: aeneas translating $llbc to Lean"
  "$tools/aeneas" -backend lean -dest "$out" "$core/$llbc"

  # Aeneas exits non-zero when it cannot translate a body, so `set -e` above has
  # already stopped us. This is defence in depth for the case where it has not:
  # it emits a *partial* file, with `sorry` in place of the body it gave up on,
  # at the same path as a good one. Nothing about the file on disk distinguishes
  # the two. Refuse to stage one.
  #
  # A failure here leaves the previously staged translation in place, so a
  # local `lake build` after a failed run builds against the last translation
  # that was staged, not against the code just changed; CI regenerates from a
  # fresh checkout. Confirm the staged file changed before relying on a local
  # build.
  if grep -qn "sorry" "$out/$module.lean"; then
    echo "run-aeneas: ERROR: $module.lean contains 'sorry', so Aeneas could not" >&2
    echo "  translate at least one body. Refusing to stage it. Re-run the" >&2
    echo "  translation and read its output for the function it gave up on." >&2
    grep -n "sorry" "$out/$module.lean" >&2
    exit 1
  fi

  cp "$out/$module.lean" "$staged/$module.lean"
  echo "run-aeneas: staged $staged/$module.lean"
}

translate ratchet tacenta-ratchet tacenta_ratchet.llbc TacentaRatchet
translate session tacenta-session tacenta_session.llbc TacentaSession
translate erasure tacenta-erasure tacenta_erasure.llbc TacentaErasure
# The bounded wire-format reader. The verified-core design's first branch puts
# it inside the verified core so that refinement *can* begin at received bytes
# rather than after a trusted parser -- but it does not yet. Today
# `tacenta-protobuf` has no caller outside its own crate and the fuzz target:
# the bytes a peer actually sends are parsed by `decode_message`,
# `decode_composite` and `decode_initial` in the root crate's `serialization`
# module, which this script deliberately does not translate. So what the
# protobuf proofs establish is a verified reader that the live path does not
# use; CLAIMS.md and LIMITATIONS.md say the same. If this stops translating,
# that decision reopens rather than the crate quietly moving out.
translate protobuf tacenta-protobuf tacenta_protobuf.llbc TacentaProtobuf

# The post-quantum stack, on the shipping path since the triple-ratchet
# integration.
translate spqr tacenta-spqr tacenta_spqr.llbc TacentaSpqr
translate braid tacenta-braid tacenta_braid.llbc TacentaBraid

# The composition, `tacenta-triple`, depends on both `tacenta-ratchet` and
# `tacenta-spqr`. Charon translates it as a self-contained unit, so the two
# inner crates' `State` types come out as bare opaque axioms here and their
# error enums are re-emitted as this crate's own copies
# (`tacenta_ratchet.RatchetError` inside `namespace tacenta_triple`, beside
# the real one inside `namespace tacenta_ratchet`). The namespaced names do
# not collide; the anonymous instances Aeneas's `@[discriminant isize]`
# generates for those enums do, since they are named from the short type
# name alone and land outside either crate's namespace
# (`instDiscriminantRatchetErrorIsize`, `instDiscriminantSpqrErrorIsize`):
# importing `Translation.TacentaTriple`
# together with `Translation.TacentaRatchet` or `Translation.TacentaSpqr`
# fails on them. `lake build` passes over the whole package only because
# lakefile.toml builds every module under Translation/ on its own (the note
# on its `globs` line) and nothing imports both sides; `TripleT1.lean` and
# `TripleT3.lean` cannot cite the inner crates' theorems for the same
# reason, which `TripleT3.lean`'s header records. Do not add a root import
# of this module.
translate triple tacenta-triple tacenta_triple.llbc TacentaTriple

echo "run-aeneas: next, record what was just generated:"
echo "run-aeneas:   python3 tacenta-proofs/scripts/attest.py --refresh-translation"
echo "run-aeneas: which rewrites manifests/translation-attestation.json (per-file"
echo "run-aeneas: SHA-256, axiom names, and the hash of the Rust each file came"
echo "run-aeneas: from). Run it now and at no other time: attest.py --check holds"
echo "run-aeneas: the tree to that record. Then, in tacenta-proofs/translation:"
echo "run-aeneas:   lake exe cache get && lake build"
