#!/bin/sh
# Translate tacenta-core to Lean via Charon and Aeneas, the first stage of the
# T1 (panic-freedom) verification path.
#
# Charon extracts the crate to LLBC, driving the exact rustc nightly it was
# built against; Aeneas translates the LLBC to Lean. The external crates (the
# trusted primitive boundary) are opaque.
#
# It translates the *leaf crate* tacenta-ratchet, not all of tacenta-core: the
# verified zone is isolated there precisely so the translated surface is exactly
# the surface we intend to prove. Translating the whole of tacenta-core pulled
# in orchestration code (closures, slice patterns) that Aeneas does not model,
# failing the run for reasons unrelated to the ratchet. The ratchet itself is
# written to the subset Aeneas models (index loops over Vec, no iterator
# adaptors).
#
# Toolchain: prebuilt nightly binaries in $AENEAS_TOOLS (default
# ~/tools/aeneas-nightly). The scratch output under Generated/aeneas-output is
# gitignored; the translation the proofs are about is *committed* under
# translation/Translation/ and the verification workflow fails if regenerating it here
# produces different files. T1 and T3 are done for the seven crates translated
# on their own below (see CLAIMS.md).
#
# An eighth translation comes from a crate nobody wrote: `tacenta-core/triple-unit`,
# the Triple Ratchet and both inner ratchets compiled as one crate, assembled
# from the three leaf sources by `scripts/assemble-triple-unit.sh` (run below,
# before anything is translated) so that Charon sees the composition together
# with its leaves rather than over opaque axioms. It is the only translation of
# the Triple Ratchet, and the Triple's T1 and T3 proofs are about it. Read that
# script's header for what the unit is and, just as importantly, what it is not.
set -eu
# **The pin, and it must match the verification workflow.** Keeping the
# release name here rather than only in the workflow is what makes a local run
# comparable to CI's; a translation produced by a different Aeneas is a
# different translation, and the proofs are about particular generated bytes.
AENEAS_RELEASE="${AENEAS_RELEASE:-nightly-2026.07.22-b1214ca}"
tools="${AENEAS_TOOLS:-$HOME/tools/aeneas-$AENEAS_RELEASE}"

# The default names the pin, and an unpinned directory is refused rather than
# used: two Aeneas builds can differ in the shape of the standard library they
# emit against (`Array.make`'s proof argument, for one), and a translation
# regenerated with a different build differs from the committed one by
# thousands of lines that have nothing to do with the Rust, so the T1 proofs
# fail against it. Override `AENEAS_TOOLS` deliberately if you mean to.
for bin in charon aeneas; do
  if [ ! -x "$tools/$bin" ]; then
    echo "missing $tools/$bin" >&2
    echo "" >&2
    echo "This script needs the *pinned* Aeneas release, $AENEAS_RELEASE," >&2
    echo "the one the verification workflow downloads and checksums." >&2
    echo "A different build produces a different translation, which the" >&2
    echo "proofs are not about." >&2
    echo "" >&2
    echo "The release ships linux-x86_64 only, so on another platform the" >&2
    echo "honest answer is to let CI do this: the verification workflow runs on every" >&2
    echo "push against a dedicated runner." >&2
    exit 1
  fi
done

here=$(cd "$(dirname "$0")/.." && pwd)
core="$here/../tacenta-core"

# Assemble the three-leaf translation unit first, so that what is translated
# below is the unit the leaves say it is rather than whatever was left in the
# tree. The script is deterministic and rewrites in place; a tree that was
# already current is unchanged, and `attest.py --check` would have failed
# beforehand if it were not.
echo "run-aeneas: assembling the three-leaf translation unit"
sh "$here/scripts/assemble-triple-unit.sh"
out="$here/Generated/aeneas-output"
# Stage the results where the translation lake package builds them (see
# tacenta-proofs/translation/lakefile.toml).
staged="$here/translation/Translation"
mkdir -p "$out" "$staged"

# Each verified zone is a leaf crate: the crate directory, the package name, and
# the Lean module Aeneas writes for it. They are translated independently, so a
# construct one of them cannot express never reaches the other.
translate() {
  leaf_dir="$1"
  package="$2"
  llbc="$3"
  module="$4"

  echo "run-aeneas: charon extracting $package (a verified zone) to LLBC"
  # The leaf crate is a workspace member, so charon runs there but writes the
  # LLBC to the workspace root.
  ( cd "$core/$leaf_dir" && "$tools/charon" cargo --preset=aeneas -- --package "$package" )

  echo "run-aeneas: aeneas translating $llbc to Lean"
  "$tools/aeneas" -backend lean -dest "$out" "$core/$llbc"

  # Aeneas exits non-zero when it cannot translate a body, so `set -e` above has
  # already stopped us. This is defence in depth for the case where it has not:
  # it emits a *partial* file, with `sorry` in place of the body it gave up on,
  # at the same path as a good one. Nothing about the file on disk distinguishes
  # the two. Refuse to stage one.
  #
  # A failure here leaves the previously staged translation in place, so a
  # local `lake build` after a failed run builds against the last translation
  # that was staged, not against the code just changed; CI regenerates from a
  # fresh checkout. Confirm the staged file changed before relying on a local
  # build.
  if grep -qn "sorry" "$out/$module.lean"; then
    echo "run-aeneas: ERROR: $module.lean contains 'sorry', so Aeneas could not" >&2
    echo "  translate at least one body. Refusing to stage it. Re-run the" >&2
    echo "  translation and read its output for the function it gave up on." >&2
    grep -n "sorry" "$out/$module.lean" >&2
    exit 1
  fi

  cp "$out/$module.lean" "$staged/$module.lean"
  echo "run-aeneas: staged $staged/$module.lean"
}

translate ratchet tacenta-ratchet tacenta_ratchet.llbc TacentaRatchet
translate session tacenta-session tacenta_session.llbc TacentaSession
translate erasure tacenta-erasure tacenta_erasure.llbc TacentaErasure
# The bounded wire-format reader. The verified-core design's first branch puts
# it inside the verified core so that refinement *can* begin at received bytes
# rather than after a trusted parser -- but it does not yet. Today
# `tacenta-protobuf` has no caller outside its own crate and the fuzz target:
# the bytes of a ratchet message are parsed by `decode_message` and
# `decode_composite`, translated below as `tacenta-wire`, and a prekey message
# by `decode_initial` in the root crate's `serialization` module, which this
# script does not translate. So what the protobuf proofs establish is a
# verified reader that the live path does not use; CLAIMS.md and LIMITATIONS.md
# say the same. If this stops translating,
# that decision reopens rather than the crate quietly moving out.
translate protobuf tacenta-protobuf tacenta_protobuf.llbc TacentaProtobuf
# The composite header and the ratchet-message decoder, `decode_composite` and
# `decode_message`: the first code the bytes of a ratchet message reach on the
# live receive path, moved out of the root crate's `serialization` module into a
# leaf crate so that they are translated. `decode_initial` is still in the root
# crate and still untranslated.
translate wire tacenta-wire tacenta_wire.llbc TacentaWire

# The post-quantum stack, on the shipping path since the triple-ratchet
# integration.
translate spqr tacenta-spqr tacenta_spqr.llbc TacentaSpqr
translate braid tacenta-braid tacenta_braid.llbc TacentaBraid

# The composition, `tacenta-triple`, is not translated on its own. Charon
# translates one crate at a time, so on its own the Triple sees both inner
# ratchets as bare opaque axioms, and nothing proved about the inner crates can
# be cited against it. It is translated inside the three-leaf unit below, where
# the inner ratchets are real code. A standalone translation and the proofs
# about it were in the tree until the commit after 2a89a7f.

# The same three crates' source, compiled as one crate: the composition with
# its leaves in one translation unit, where `tacenta_ratchet.State` is a type
# with fields and `tacenta_ratchet.send` is a body with a precondition rather
# than the bare axioms a translation of the Triple on its own is forced to
# invent. This is what
# a panic-freedom proof for the shipping composition has to be about;
# `scripts/assemble-triple-unit.sh` says what the unit is and is not, and
# LIMITATIONS.md records the crate boundary as the gap it leaves, under "The
# three-leaf translation unit is an eighth zone, and it ships to nobody".
#
# Its axiom set must be exactly the union of the three leaves': the leaves'
# opaque externals are the trusted primitive boundary, and the unit crosses no
# boundary they do not. An axiom here that appears in none of the three is a
# finding, not a detail -- it would mean the unit reaches something none of the
# leaves does.
#
# This module cannot share an environment with `TacentaRatchet` or
# `TacentaSpqr`. Aeneas names the instances it generates for the inner crates'
# error enums (`instDiscriminantRatchetErrorIsize`,
# `instDiscriminantSpqrErrorIsize`) from the short type name alone, outside any
# crate namespace, so the unit and the leaves both declare them. It is imported
# neither by the root module nor by `Translation/AxiomAudit.lean`;
# `Translation/AxiomAuditTripleUnit.lean` walks it.
translate triple-unit tacenta-triple-unit tacenta_triple_unit.llbc TacentaTripleUnit

echo "run-aeneas: next, record what was just generated:"
echo "run-aeneas:   python3 tacenta-proofs/scripts/attest.py --refresh-translation"
echo "run-aeneas: which rewrites manifests/translation-attestation.json (per-file"
echo "run-aeneas: SHA-256, axiom names, and the hash of the Rust each file came"
echo "run-aeneas: from). Run it now and at no other time: attest.py --check holds"
echo "run-aeneas: the tree to that record. Then, in tacenta-proofs/translation:"
echo "run-aeneas:   lake exe cache get && lake build"
