//! Replay the Double Ratchet protocol vectors against tacenta-core. The vectors
//! are generated from the model (tacenta-model, `lake exe genvectors`), so this
//! checks the implementation reproduces the model's message keys byte for byte,
//! and, on every model-generated step, the expansion of each message key into
//! the AEAD key, the MAC key and the IV (`ratchet::message_keys`), so that the
//! expansion's label, salt and split order are pinned by bytes as well as by
//! the refinement theorem.

use std::path::Path;

#[test]
fn ratchet_vectors_pass() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    // Model-generated scenarios plus the hand-authored malformed-input rejection.
    let mut files = tacenta_vectors_rust::load_ratchet_dir(&root.join("../../vectors/ratchet"))
        .expect("load ratchet vectors");
    files.extend(
        tacenta_vectors_rust::load_ratchet_dir(&root.join("../../vectors/malformed-input"))
            .expect("load malformed-input vectors"),
    );
    assert!(!files.is_empty(), "expected ratchet vector files");

    let mut total = 0;
    let mut vectors = 0;
    for file in &files {
        vectors += file.vectors.len();
        total += tacenta_vectors_rust::check_ratchet_file(file)
            .unwrap_or_else(|e| panic!("{}: {e}", file.algorithm));
    }

    assert!(vectors >= 4, "checked {vectors} ratchet vectors");
    // Every model-generated step must carry the expansion, so that the check
    // above cannot quietly become optional.
    let expansions: usize = files
        .iter()
        .filter(|f| f.source.starts_with("generated by tacenta-model"))
        .flat_map(|f| f.vectors.iter())
        .flat_map(|v| v.steps.iter())
        .filter(|s| s.expect != "reject")
        .map(|s| {
            assert!(
                s.message_keys.is_some(),
                "a model-generated step records no message_keys"
            );
            1
        })
        .sum();
    assert!(
        expansions >= 12,
        "checked {expansions} message-key expansions"
    );
    eprintln!(
        "checked {total} ratchet steps across {vectors} vectors in {} files",
        files.len()
    );
}
