/-
Translation.SessionT3: the PQXDH derivation refines the model (proof tier T3).

The second zone's refinement tier. Where `Translation.T3` relates the ratchet's
state machine to `Model.Ratchet`, this relates the session derivation to
`Model.SessionEstablishment`: the same bytes go in, the same bytes come out.

It is short, and that is the point. `Translation.SessionT1` stated every
specification with the value it produces rather than only that it returned, so
there is nothing here to unpick: the facts the refinement needs are already the
facts panic-freedom was proved with. The ratchet's tier, built on
totality-only specs, spends much of its length removing and restating
stepping rules.

The same two limits stand as for the ratchet, and neither is a formality.
Refinement is modulo agreement of the opaque key derivation: if the Rust HKDF
and the model's disagreed, everything here would still hold and the code would
still be wrong. The model-generated byte vectors are what covers that, outside
Lean.
-/
import Translation.SessionT1
import Translation.T3
import Model.SessionEstablishment

namespace Tacenta.SessionT3

open Aeneas Aeneas.Std Result
open tacenta_session
open Tacenta.T3 (u8 keyOf sliceOf)

/-! ## The constants agree

Both sides fix the domain separator and the parameter label. They are written
independently -- one as a Rust byte string, one as a list of code points -- so
that they agree is a fact to check, not an arrangement to assume. -/

theorem fPrefix_agrees : keyOf F_PREFIX = Model.SessionEstablishment.fPrefix := by
  first | rfl | decide | native_decide

theorem skInfo_agrees : sliceOf SK_INFO = Model.SessionEstablishment.skInfo := by
  first | rfl | decide | native_decide

/-! ## The keying material refines the model's

Nothing is assumed here: this is the ordering of the components, which is the
whole content of this step, and it is settled by structure alone. Both shapes,
because the code branches on the one-time output and so does the model. -/

theorem km_refines_none (dh1 dh2 dh3 ss : Array Std.U8 32#usize) :
    km dh1 dh2 dh3 none ss ⦃ fun r =>
      sliceOf ⟨r.val, r.property⟩
        = Model.SessionEstablishment.km (keyOf dh1) (keyOf dh2) (keyOf dh3) none
            (keyOf ss) ⦄ := by
  refine Std.WP.spec_mono (Tacenta.SessionT1.km_spec_none dh1 dh2 dh3 ss) ?_
  intro r hr
  simp only [sliceOf, hr, Model.SessionEstablishment.km, keyOf, List.map_append]

theorem km_refines_some (dh1 dh2 dh3 d4 ss : Array Std.U8 32#usize) :
    km dh1 dh2 dh3 (some d4) ss ⦃ fun r =>
      sliceOf ⟨r.val, r.property⟩
        = Model.SessionEstablishment.km (keyOf dh1) (keyOf dh2) (keyOf dh3)
            (some (keyOf d4)) (keyOf ss) ⦄ := by
  refine Std.WP.spec_mono (Tacenta.SessionT1.km_spec_some dh1 dh2 dh3 d4 ss) ?_
  intro r hr
  simp only [sliceOf, hr, Model.SessionEstablishment.km, keyOf, List.map_append]

/-! ## The derivation refines the model's

The one place an assumption is needed. The key derivation is opaque on both
sides, so that the two agree is stated rather than proved, exactly as for the
ratchet's chain and root steps. Everything else here is structure.

**This is the limit that matters.** If the Rust HKDF and the model's disagreed,
every theorem in this file would still hold and the implementation would still
be wrong. What covers that is the model-generated byte vectors, checked outside
Lean. -/

/-- The opaque key derivation agrees with the model's, at the length this
derivation uses. -/
def HkdfAgrees : Prop :=
  ∀ (salt ikm info : Slice Std.U8),
    tacenta_kdf.hkdf_sha256 32#usize salt ikm info ⦃ fun r =>
      keyOf r = Model.Kdf.hkdf (sliceOf salt) (sliceOf ikm) (sliceOf info) 32 ⦄

@[step]
theorem hkdf_agrees_step (h : HkdfAgrees) (salt ikm info : Slice Std.U8) :
    tacenta_kdf.hkdf_sha256 32#usize salt ikm info ⦃ fun r =>
      keyOf r = Model.Kdf.hkdf (sliceOf salt) (sliceOf ikm) (sliceOf info) 32 ⦄ :=
  h salt ikm info

/-- A translated zero byte is the model's zero byte. Needed because the salt
reaches the goal as a literal of translated bytes on one side and a `replicate`
on the other; with this the two normalise to the same list. -/
theorem u8_zero : u8 0#u8 = 0 := by first | rfl | decide | native_decide

/-- The all-zero salt is the model's, which is a fact about two independently
written constants rather than an arrangement. -/
theorem zeroSalt_agrees :
    List.map u8 (Array.repeat 32#usize (0#u8)).val = List.replicate 32 0 := by
  first | rfl | decide | native_decide

theorem kdf_sk_refines (h : HkdfAgrees) [Tacenta.SessionT1.ZeroizingModel]
    (km_bytes : Slice Std.U8)
    (hb : km_bytes.val.length + 32 ≤ Usize.max) :
    kdf_sk km_bytes ⦃ fun r =>
      keyOf r = Model.SessionEstablishment.kdf (sliceOf km_bytes) ⦄ := by
  unfold kdf_sk
  have hpre := fPrefix_agrees
  have hinfo := skInfo_agrees
  step*
  -- The bounds first, in the shape panic-freedom left them; the value goal only
  -- afterwards, because unfolding the model's derivation into the bound goals
  -- is what loses them.
  all_goals simp_all
  all_goals first
    | omega
    | exact Tacenta.SessionT1.small_le_usize_max (by omega)
    | simp_all [Model.SessionEstablishment.kdf, sliceOf, keyOf,
        alloc.vec.Vec.deref, List.map_append, zeroSalt_agrees, u8_zero]

-- T1's rule for `kdf_sk` says only that it returned, which is all panic-freedom
-- needed and too little here: it would walk past the call and lose what was
-- derived. The one below carries the value instead. This is the only place in
-- this file that has to do it, where the ratchet's tier had to do it six times.
attribute [-step] Tacenta.SessionT1.kdf_sk_step

@[step]
theorem kdf_sk_refines_step (h : HkdfAgrees) [Tacenta.SessionT1.ZeroizingModel]
    (km_bytes : Slice Std.U8)
    (hb : km_bytes.val.length + 32 ≤ Usize.max) :
    kdf_sk km_bytes ⦃ fun r =>
      keyOf r = Model.SessionEstablishment.kdf (sliceOf km_bytes) ⦄ :=
  kdf_sk_refines h km_bytes hb

/-- The shared secret refines the model's, in both shapes.

The headline of this file: given the same agreement outputs, the implementation
and the model produce the same thirty-two bytes, modulo the key derivation
agreeing. No precondition, because the keying material's size is fixed and the
bound `kdf_sk` asks for is discharged from `km`'s value. -/
theorem shared_secret_refines_none (h : HkdfAgrees)
    [Tacenta.SessionT1.ZeroizingModel] (dh1 dh2 dh3 ss : Array Std.U8 32#usize) :
    shared_secret dh1 dh2 dh3 none ss ⦃ fun r =>
      keyOf r = Model.SessionEstablishment.sharedSecret
        (keyOf dh1) (keyOf dh2) (keyOf dh3) none (keyOf ss) ⦄ := by
  unfold shared_secret
  have l1 := Tacenta.SessionT1.array32_length dh1
  have l2 := Tacenta.SessionT1.array32_length dh2
  have l3 := Tacenta.SessionT1.array32_length dh3
  have ls := Tacenta.SessionT1.array32_length ss
  step*
  all_goals simp_all [alloc.vec.Vec.deref]
  all_goals first
    | exact Tacenta.SessionT1.small_le_usize_max (by omega)
    | simp_all [Model.SessionEstablishment.sharedSecret,
        Model.SessionEstablishment.km, sliceOf, keyOf, alloc.vec.Vec.deref,
        List.map_append]

theorem shared_secret_refines_some (h : HkdfAgrees)
    [Tacenta.SessionT1.ZeroizingModel]
    (dh1 dh2 dh3 d4 ss : Array Std.U8 32#usize) :
    shared_secret dh1 dh2 dh3 (some d4) ss ⦃ fun r =>
      keyOf r = Model.SessionEstablishment.sharedSecret
        (keyOf dh1) (keyOf dh2) (keyOf dh3) (some (keyOf d4)) (keyOf ss) ⦄ := by
  unfold shared_secret
  have l1 := Tacenta.SessionT1.array32_length dh1
  have l2 := Tacenta.SessionT1.array32_length dh2
  have l3 := Tacenta.SessionT1.array32_length dh3
  have l4 := Tacenta.SessionT1.array32_length d4
  have ls := Tacenta.SessionT1.array32_length ss
  step*
  all_goals simp_all [alloc.vec.Vec.deref]
  all_goals first
    | exact Tacenta.SessionT1.small_le_usize_max (by omega)
    | simp_all [Model.SessionEstablishment.sharedSecret,
        Model.SessionEstablishment.km, sliceOf, keyOf, alloc.vec.Vec.deref,
        List.map_append]

/-! ## The identity binding and the encodings refine the model's

Also assumption-free. `associated_data` keeps its length bound, which is a
precondition of the code rather than of the refinement: without it the append
fails, and a failed call refines nothing. -/

theorem associated_data_refines (a b : Slice Std.U8)
    (h : a.val.length + b.val.length ≤ Usize.max) :
    associated_data a b ⦃ fun r =>
      sliceOf ⟨r.val, r.property⟩
        = Model.SessionEstablishment.associatedData (sliceOf a) (sliceOf b) ⦄ := by
  refine Std.WP.spec_mono (Tacenta.SessionT1.associated_data_spec a b h) ?_
  intro r hr
  simp only [sliceOf, hr, Model.SessionEstablishment.associatedData, List.map_append]

theorem associated_data_with_kem_refines (a b c : Slice Std.U8)
    (h : a.val.length + b.val.length + c.val.length ≤ Usize.max) :
    associated_data_with_kem a b c ⦃ fun r =>
      sliceOf ⟨r.val, r.property⟩
        = Model.SessionEstablishment.associatedDataWithKem
            (sliceOf a) (sliceOf b) (sliceOf c) ⦄ := by
  refine Std.WP.spec_mono
    (Tacenta.SessionT1.associated_data_with_kem_spec a b c h) ?_
  intro r hr
  simp only [sliceOf, hr, Model.SessionEstablishment.associatedDataWithKem,
    List.map_append]

/-! ## What the encodings guarantee

The model takes the encoded identity forms as given rather than defining them,
so there is nothing here to refine *against*. What can be settled is the
property the model's `associatedData` depends on and cannot state for itself:
the encoding is a fixed thirty-three bytes.

`Proofs.SessionEstablishment` proves the identities are recoverable from the
concatenation given that width, and carries the counterexample showing it fails
without it. This is the same fact on the implementation's side of the line, so
the two meet. -/

theorem encode_ec_is_fixed_width (pk : Array Std.U8 32#usize) :
    encode_ec pk ⦃ fun r => r.val.length = 33 ⦄ := by
  refine Std.WP.spec_mono (Tacenta.SessionT1.encode_ec_spec pk) ?_
  intro r hr
  simp only [hr, List.length_cons, Tacenta.SessionT1.array32_length pk]

/-- Reading an encoding back gives the bytes that were encoded: the round trip
holds, which is what makes `decode_ec` the inverse the name claims. -/
theorem decode_ec_after_encode_ec (pk : Array Std.U8 32#usize) :
    encode_ec pk ⦃ fun e =>
      ∀ (s : Slice Std.U8), s.val = e.val →
        decode_ec s ⦃ fun r => ∀ k, r = some k → keyOf k = keyOf pk ⦄ ⦄ := by
  refine Std.WP.spec_mono (Tacenta.SessionT1.encode_ec_spec pk) ?_
  intro e he s hs
  have hlen : s.val.length = 33 := by
    rw [hs, he, List.length_cons, Tacenta.SessionT1.array32_length pk]
  refine Std.WP.spec_mono (Tacenta.SessionT1.decode_ec_spec s) ?_
  intro r hr k hk
  have hpt := hr k hk
  -- Pointwise agreement plus equal lengths is list equality, and `keyOf` is a
  -- map, so it follows.
  have hklen : k.val.length = 32 := Tacenta.SessionT1.array32_length k
  have hpklen : pk.val.length = 32 := Tacenta.SessionT1.array32_length pk
  have : k.val = pk.val := by
    apply List.ext_getElem (by omega)
    intro n h1 h2
    -- The specification is pointwise in `getElem!`; both indices are in range,
    -- so each is the plain element.
    have hn := hpt n (by omega)
    rw [hs, he] at hn
    -- The right-hand index steps past the tag byte; reduce it to the array's
    -- own index, then both sides are plain elements.
    have hcons : (ENCODE_EC_CURVE25519 :: pk.val)[n + 1]! = pk.val[n]! := by
      first
        | rfl
        | simp [getElem!_def]
        | simp [List.getElem!_eq_getElem?_getD]
    rw [hcons] at hn
    first
      | rwa [getElem!_pos _ _ h1, getElem!_pos _ _ h2] at hn
      | (simp only [getElem!_pos, h1, h2] at hn
         exact hn)
      | (simpa [getElem!_pos, h1, h2, List.getElem?_eq_getElem] using hn)
  simp only [keyOf, this]

/-! ## The boundary, checked rather than asserted

Two things in this list deserve naming rather than passing.

`tacenta_kdf.hkdf_sha256` is the assumption that matters: it is opaque on both
sides, and `HkdfAgrees` says the two agree. If they did not, every theorem here
would still hold and the implementation would still be wrong. The
model-generated byte vectors are what covers that, outside Lean.

The two `native_decide` entries are the constant comparisons: that the domain
separator and the parameter label written as Rust byte strings are the ones the
model writes as lists of code points. They are decided by evaluation, which
trusts the compiler rather than only the kernel. That is the same tool the model
uses for its known-answer checks, and it is used here for the same kind of
thing -- two concrete constants -- but it is a wider trust base than the rest of
this file, and the axiom pin is where that becomes visible. -/

/--
info: 'Tacenta.SessionT3.shared_secret_refines_some' depends on axioms: [propext,
 Classical.choice,
 Quot.sound,
 tacenta_kdf.hkdf_sha256,
 zeroize.Zeroizing,
 zeroize.Zeroizing.new,
 zeroize.Zeroize.Blanket.zeroize,
 fPrefix_agrees._native.native_decide.ax_1_1,
 skInfo_agrees._native.native_decide.ax_1_1,
 zeroize.Zeroizing.Insts.CoreOpsDerefDeref.deref,
 zeroize.Zeroizing.Insts.CoreOpsDerefDerefMut.deref_mut,
 alloc.vec.Vec.Insts.ZeroizeZeroize.zeroize]
-/
#guard_msgs in
#print axioms Tacenta.SessionT3.shared_secret_refines_some

/-
## What T3 covers for this zone

The derivation refines the model in both shapes: given the same agreement
outputs, the implementation and the model produce the same thirty-two bytes.
So do the keying material's assembly, the identity binding, and the encodings,
and `decode_ec` inverts `encode_ec`.

This file is a third the length of the ratchet's, and the reason is the whole
argument for how `Translation.SessionT1` is written: panic-freedom is proved
with the values the refinement needs rather than with the weaker facts it could
have got away with, so exactly one stepping rule is restated here.

What is *not* here: the model takes the encoded identity forms as given rather
than defining them, so there is nothing to refine `encode_ec` against. What can
be said on this side of the line is that it is thirty-three bytes wide, which is
the fact `Proofs.SessionEstablishment` needs and cannot state for itself. The
two meet there.
-/

end Tacenta.SessionT3
