-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [tacenta_triple]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace tacenta_triple

/-- [tacenta_kdf::hkdf_sha256]:
    Source: 'kdf/src/lib.rs', lines 27:0-27:83
    Name pattern: [tacenta_kdf::hkdf_sha256]
    Visibility: public -/
@[rust_fun "tacenta_kdf::hkdf_sha256"]
axiom tacenta_kdf.hkdf_sha256
  (N : Std.Usize) :
  Slice Std.U8 → Slice Std.U8 → Slice Std.U8 → Result (Array Std.U8 N)

/-- [tacenta_ratchet::LabelSet]
    Source: 'ratchet/src/lib.rs', lines 68:0-68:17
    Name pattern: [tacenta_ratchet::LabelSet]
    Visibility: public -/
@[discriminant isize, rust_type "tacenta_ratchet::LabelSet"]
inductive tacenta_ratchet.LabelSet where
| Tacenta : tacenta_ratchet.LabelSet

/-- [tacenta_ratchet::Header]
    Source: 'ratchet/src/lib.rs', lines 105:0-105:17
    Name pattern: [tacenta_ratchet::Header]
    Visibility: public -/
@[rust_type "tacenta_ratchet::Header"]
structure tacenta_ratchet.Header where
  dh : Array Std.U8 32#usize
  pn : Std.U32
  n : Std.U32

/-- [tacenta_ratchet::{impl core::cmp::PartialEq<tacenta_ratchet::Header> for tacenta_ratchet::Header}::eq]:
    Source: 'ratchet/src/lib.rs', lines 104:22-104:31
    Name pattern: [tacenta_ratchet::{core::cmp::PartialEq<tacenta_ratchet::Header, tacenta_ratchet::Header>}::eq]
    Visibility: public -/
@[rust_fun
  "tacenta_ratchet::{core::cmp::PartialEq<tacenta_ratchet::Header, tacenta_ratchet::Header>}::eq"]
axiom tacenta_ratchet.Header.Insts.CoreCmpPartialEqHeader.eq
  : tacenta_ratchet.Header → tacenta_ratchet.Header → Result Bool

/-- [tacenta_ratchet::{impl core::fmt::Debug for tacenta_ratchet::Header}::fmt]:
    Source: 'ratchet/src/lib.rs', lines 104:37-104:42
    Name pattern: [tacenta_ratchet::{core::fmt::Debug<tacenta_ratchet::Header>}::fmt]
    Visibility: public -/
@[rust_fun "tacenta_ratchet::{core::fmt::Debug<tacenta_ratchet::Header>}::fmt"]
axiom tacenta_ratchet.Header.Insts.CoreFmtDebug.fmt
  :
  tacenta_ratchet.Header → core.fmt.Formatter → Result ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter)

/-- Trait implementation: [tacenta_ratchet::{impl core::fmt::Debug for tacenta_ratchet::Header}]
    Source: 'ratchet/src/lib.rs', lines 104:37-104:42
    Name pattern: [core::fmt::Debug<tacenta_ratchet::Header>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<tacenta_ratchet::Header>"]
def tacenta_ratchet.Header.Insts.CoreFmtDebug : core.fmt.Debug
  tacenta_ratchet.Header := {
  fmt := tacenta_ratchet.Header.Insts.CoreFmtDebug.fmt
}

/-- [tacenta_ratchet::State]
    Source: 'ratchet/src/lib.rs', lines 143:0-143:16
    Name pattern: [tacenta_ratchet::State]
    Visibility: public -/
@[rust_type "tacenta_ratchet::State"]
axiom tacenta_ratchet.State : Type

/-- [tacenta_ratchet::{impl core::clone::Clone for tacenta_ratchet::State}::clone]:
    Source: 'ratchet/src/lib.rs', lines 141:9-141:14
    Name pattern: [tacenta_ratchet::{core::clone::Clone<tacenta_ratchet::State>}::clone]
    Visibility: public -/
@[rust_fun
  "tacenta_ratchet::{core::clone::Clone<tacenta_ratchet::State>}::clone"]
axiom tacenta_ratchet.State.Insts.CoreCloneClone.clone
  : tacenta_ratchet.State → Result tacenta_ratchet.State

/-- [tacenta_ratchet::{tacenta_ratchet::State}::skipped_len]:
    Source: 'ratchet/src/lib.rs', lines 202:4-202:38
    Name pattern: [tacenta_ratchet::{tacenta_ratchet::State}::skipped_len]
    Visibility: public -/
@[rust_fun "tacenta_ratchet::{tacenta_ratchet::State}::skipped_len"]
axiom tacenta_ratchet.State.skipped_len
  : tacenta_ratchet.State → Result Std.Usize

/-- [tacenta_ratchet::{tacenta_ratchet::State}::evict_oldest]:
    Source: 'ratchet/src/lib.rs', lines 233:4-233:57
    Name pattern: [tacenta_ratchet::{tacenta_ratchet::State}::evict_oldest]
    Visibility: public -/
@[rust_fun "tacenta_ratchet::{tacenta_ratchet::State}::evict_oldest"]
axiom tacenta_ratchet.State.evict_oldest
  :
  tacenta_ratchet.State → Std.Usize → Result (Std.Usize ×
    tacenta_ratchet.State)

/-- [tacenta_ratchet::RatchetError]
    Source: 'ratchet/src/lib.rs', lines 253:0-253:21
    Name pattern: [tacenta_ratchet::RatchetError]
    Visibility: public -/
@[discriminant isize, rust_type "tacenta_ratchet::RatchetError"]
inductive tacenta_ratchet.RatchetError where
| TooManySkipped : tacenta_ratchet.RatchetError
| SkippedStoreFull : tacenta_ratchet.RatchetError
| NoSendingChain : tacenta_ratchet.RatchetError
| NoReceivingChain : tacenta_ratchet.RatchetError
| ChainExhausted : tacenta_ratchet.RatchetError

/-- [tacenta_ratchet::{impl core::cmp::PartialEq<tacenta_ratchet::RatchetError> for tacenta_ratchet::RatchetError}::eq]:
    Source: 'ratchet/src/lib.rs', lines 252:22-252:31
    Name pattern: [tacenta_ratchet::{core::cmp::PartialEq<tacenta_ratchet::RatchetError, tacenta_ratchet::RatchetError>}::eq]
    Visibility: public -/
@[rust_fun
  "tacenta_ratchet::{core::cmp::PartialEq<tacenta_ratchet::RatchetError, tacenta_ratchet::RatchetError>}::eq"]
axiom tacenta_ratchet.RatchetError.Insts.CoreCmpPartialEqRatchetError.eq
  :
  tacenta_ratchet.RatchetError → tacenta_ratchet.RatchetError → Result Bool

/-- Trait implementation: [tacenta_ratchet::{impl core::cmp::PartialEq<tacenta_ratchet::RatchetError> for tacenta_ratchet::RatchetError}]
    Source: 'ratchet/src/lib.rs', lines 252:22-252:31
    Name pattern: [core::cmp::PartialEq<tacenta_ratchet::RatchetError, tacenta_ratchet::RatchetError>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<tacenta_ratchet::RatchetError, tacenta_ratchet::RatchetError>"]
def tacenta_ratchet.RatchetError.Insts.CoreCmpPartialEqRatchetError :
  core.cmp.PartialEq tacenta_ratchet.RatchetError tacenta_ratchet.RatchetError
  := {
  eq := tacenta_ratchet.RatchetError.Insts.CoreCmpPartialEqRatchetError.eq
}

/-- [tacenta_ratchet::{impl core::fmt::Debug for tacenta_ratchet::RatchetError}::fmt]:
    Source: 'ratchet/src/lib.rs', lines 252:37-252:42
    Name pattern: [tacenta_ratchet::{core::fmt::Debug<tacenta_ratchet::RatchetError>}::fmt]
    Visibility: public -/
@[rust_fun
  "tacenta_ratchet::{core::fmt::Debug<tacenta_ratchet::RatchetError>}::fmt"]
axiom tacenta_ratchet.RatchetError.Insts.CoreFmtDebug.fmt
  :
  tacenta_ratchet.RatchetError → core.fmt.Formatter → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- Trait implementation: [tacenta_ratchet::{impl core::fmt::Debug for tacenta_ratchet::RatchetError}]
    Source: 'ratchet/src/lib.rs', lines 252:37-252:42
    Name pattern: [core::fmt::Debug<tacenta_ratchet::RatchetError>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<tacenta_ratchet::RatchetError>"]
def tacenta_ratchet.RatchetError.Insts.CoreFmtDebug : core.fmt.Debug
  tacenta_ratchet.RatchetError := {
  fmt := tacenta_ratchet.RatchetError.Insts.CoreFmtDebug.fmt
}

/-- [tacenta_ratchet::{tacenta_ratchet::State}::sending_public]:
    Source: 'ratchet/src/lib.rs', lines 273:4-273:39
    Name pattern: [tacenta_ratchet::{tacenta_ratchet::State}::sending_public]
    Visibility: public -/
@[rust_fun "tacenta_ratchet::{tacenta_ratchet::State}::sending_public"]
axiom tacenta_ratchet.State.sending_public
  : tacenta_ratchet.State → Result (Array Std.U8 32#usize)

/-- [tacenta_ratchet::{tacenta_ratchet::State}::send_count]:
    Source: 'ratchet/src/lib.rs', lines 278:4-278:35
    Name pattern: [tacenta_ratchet::{tacenta_ratchet::State}::send_count]
    Visibility: public -/
@[rust_fun "tacenta_ratchet::{tacenta_ratchet::State}::send_count"]
axiom tacenta_ratchet.State.send_count
  : tacenta_ratchet.State → Result Std.U32

/-- [tacenta_ratchet::{tacenta_ratchet::State}::receive_count]:
    Source: 'ratchet/src/lib.rs', lines 283:4-283:38
    Name pattern: [tacenta_ratchet::{tacenta_ratchet::State}::receive_count]
    Visibility: public -/
@[rust_fun "tacenta_ratchet::{tacenta_ratchet::State}::receive_count"]
axiom tacenta_ratchet.State.receive_count
  : tacenta_ratchet.State → Result Std.U32

/-- [tacenta_ratchet::RatchetDecodeError]
    Source: 'ratchet/src/lib.rs', lines 308:0-308:27
    Name pattern: [tacenta_ratchet::RatchetDecodeError]
    Visibility: public -/
@[discriminant isize, rust_type "tacenta_ratchet::RatchetDecodeError"]
inductive tacenta_ratchet.RatchetDecodeError where
| UnknownVersion : tacenta_ratchet.RatchetDecodeError
| TooShort : tacenta_ratchet.RatchetDecodeError
| Malformed : tacenta_ratchet.RatchetDecodeError

/-- [zeroize::Zeroizing]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 604:0-604:41
    Name pattern: [zeroize::Zeroizing]
    Visibility: public -/
@[rust_type "zeroize::Zeroizing"]
axiom zeroize.Zeroizing (Z : Type) : Type

/-- [tacenta_ratchet::{tacenta_ratchet::State}::to_bytes]:
    Source: 'ratchet/src/lib.rs', lines 452:4-452:48
    Name pattern: [tacenta_ratchet::{tacenta_ratchet::State}::to_bytes]
    Visibility: public -/
@[rust_fun "tacenta_ratchet::{tacenta_ratchet::State}::to_bytes"]
axiom tacenta_ratchet.State.to_bytes
  : tacenta_ratchet.State → Result (zeroize.Zeroizing (alloc.vec.Vec Std.U8))

/-- [tacenta_ratchet::{tacenta_ratchet::State}::from_bytes]:
    Source: 'ratchet/src/lib.rs', lines 477:4-477:72
    Name pattern: [tacenta_ratchet::{tacenta_ratchet::State}::from_bytes]
    Visibility: public -/
@[rust_fun "tacenta_ratchet::{tacenta_ratchet::State}::from_bytes"]
axiom tacenta_ratchet.State.from_bytes
  :
  Slice Std.U8 → Result (core.result.Result tacenta_ratchet.State
    tacenta_ratchet.RatchetDecodeError)

/-- [tacenta_ratchet::init_sender]:
    Source: 'ratchet/src/lib.rs', lines 723:0-723:98
    Name pattern: [tacenta_ratchet::init_sender]
    Visibility: public -/
@[rust_fun "tacenta_ratchet::init_sender"]
axiom tacenta_ratchet.init_sender
  :
  Array Std.U8 32#usize → Array Std.U8 32#usize → Array Std.U8 32#usize →
    Array Std.U8 32#usize → tacenta_ratchet.LabelSet → Result
    tacenta_ratchet.State

/-- [tacenta_ratchet::init_receiver]:
    Source: 'ratchet/src/lib.rs', lines 743:0-743:71
    Name pattern: [tacenta_ratchet::init_receiver]
    Visibility: public -/
@[rust_fun "tacenta_ratchet::init_receiver"]
axiom tacenta_ratchet.init_receiver
  :
  Array Std.U8 32#usize → Array Std.U8 32#usize → tacenta_ratchet.LabelSet
    → Result tacenta_ratchet.State

/-- [tacenta_ratchet::send]:
    Source: 'ratchet/src/lib.rs', lines 761:0-761:69
    Name pattern: [tacenta_ratchet::send]
    Visibility: public -/
@[rust_fun "tacenta_ratchet::send"]
axiom tacenta_ratchet.send
  :
  tacenta_ratchet.State → Result ((core.result.Result (tacenta_ratchet.Header
    × (Array Std.U8 32#usize)) tacenta_ratchet.RatchetError) ×
    tacenta_ratchet.State)

/-- [tacenta_ratchet::receive]:
    Source: 'ratchet/src/lib.rs', lines 907:0-913:30
    Name pattern: [tacenta_ratchet::receive]
    Visibility: public -/
@[rust_fun "tacenta_ratchet::receive"]
axiom tacenta_ratchet.receive
  :
  tacenta_ratchet.State → tacenta_ratchet.Header → Array Std.U8 32#usize
    → Array Std.U8 32#usize → Array Std.U8 32#usize → Result
    ((core.result.Result (Array Std.U8 32#usize) tacenta_ratchet.RatchetError)
    × tacenta_ratchet.State)

/-- [tacenta_spqr::Output]
    Source: 'spqr/src/lib.rs', lines 87:0-87:17
    Name pattern: [tacenta_spqr::Output]
    Visibility: public -/
@[rust_type "tacenta_spqr::Output"]
structure tacenta_spqr.Output where
  key_epoch : Std.U64
  key : Array Std.U8 32#usize

/-- [tacenta_spqr::SpqrError]
    Source: 'spqr/src/lib.rs', lines 114:0-114:18
    Name pattern: [tacenta_spqr::SpqrError]
    Visibility: public -/
@[discriminant isize, rust_type "tacenta_spqr::SpqrError"]
inductive tacenta_spqr.SpqrError where
| EpochOutOfOrder : tacenta_spqr.SpqrError
| NoChain : tacenta_spqr.SpqrError
| ChainRetired : tacenta_spqr.SpqrError
| TooManySkipped : tacenta_spqr.SpqrError
| SkippedStoreFull : tacenta_spqr.SpqrError
| OutOfOrder : tacenta_spqr.SpqrError
| ChainExhausted : tacenta_spqr.SpqrError

/-- [tacenta_spqr::{impl core::cmp::PartialEq<tacenta_spqr::SpqrError> for tacenta_spqr::SpqrError}::eq]:
    Source: 'spqr/src/lib.rs', lines 113:22-113:31
    Name pattern: [tacenta_spqr::{core::cmp::PartialEq<tacenta_spqr::SpqrError, tacenta_spqr::SpqrError>}::eq]
    Visibility: public -/
@[rust_fun
  "tacenta_spqr::{core::cmp::PartialEq<tacenta_spqr::SpqrError, tacenta_spqr::SpqrError>}::eq"]
axiom tacenta_spqr.SpqrError.Insts.CoreCmpPartialEqSpqrError.eq
  : tacenta_spqr.SpqrError → tacenta_spqr.SpqrError → Result Bool

/-- Trait implementation: [tacenta_spqr::{impl core::cmp::PartialEq<tacenta_spqr::SpqrError> for tacenta_spqr::SpqrError}]
    Source: 'spqr/src/lib.rs', lines 113:22-113:31
    Name pattern: [core::cmp::PartialEq<tacenta_spqr::SpqrError, tacenta_spqr::SpqrError>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<tacenta_spqr::SpqrError, tacenta_spqr::SpqrError>"]
def tacenta_spqr.SpqrError.Insts.CoreCmpPartialEqSpqrError : core.cmp.PartialEq
  tacenta_spqr.SpqrError tacenta_spqr.SpqrError := {
  eq := tacenta_spqr.SpqrError.Insts.CoreCmpPartialEqSpqrError.eq
}

/-- [tacenta_spqr::{impl core::fmt::Debug for tacenta_spqr::SpqrError}::fmt]:
    Source: 'spqr/src/lib.rs', lines 113:37-113:42
    Name pattern: [tacenta_spqr::{core::fmt::Debug<tacenta_spqr::SpqrError>}::fmt]
    Visibility: public -/
@[rust_fun "tacenta_spqr::{core::fmt::Debug<tacenta_spqr::SpqrError>}::fmt"]
axiom tacenta_spqr.SpqrError.Insts.CoreFmtDebug.fmt
  :
  tacenta_spqr.SpqrError → core.fmt.Formatter → Result ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter)

/-- Trait implementation: [tacenta_spqr::{impl core::fmt::Debug for tacenta_spqr::SpqrError}]
    Source: 'spqr/src/lib.rs', lines 113:37-113:42
    Name pattern: [core::fmt::Debug<tacenta_spqr::SpqrError>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<tacenta_spqr::SpqrError>"]
def tacenta_spqr.SpqrError.Insts.CoreFmtDebug : core.fmt.Debug
  tacenta_spqr.SpqrError := {
  fmt := tacenta_spqr.SpqrError.Insts.CoreFmtDebug.fmt
}

/-- [tacenta_spqr::State]
    Source: 'spqr/src/lib.rs', lines 228:0-228:16
    Name pattern: [tacenta_spqr::State]
    Visibility: public -/
@[rust_type "tacenta_spqr::State"]
axiom tacenta_spqr.State : Type

/-- [tacenta_spqr::{impl core::clone::Clone for tacenta_spqr::State}::clone]:
    Source: 'spqr/src/lib.rs', lines 226:9-226:14
    Name pattern: [tacenta_spqr::{core::clone::Clone<tacenta_spqr::State>}::clone]
    Visibility: public -/
@[rust_fun "tacenta_spqr::{core::clone::Clone<tacenta_spqr::State>}::clone"]
axiom tacenta_spqr.State.Insts.CoreCloneClone.clone
  : tacenta_spqr.State → Result tacenta_spqr.State

/-- [tacenta_spqr::{tacenta_spqr::State}::init_alice]:
    Source: 'spqr/src/lib.rs', lines 322:4-322:41
    Name pattern: [tacenta_spqr::{tacenta_spqr::State}::init_alice]
    Visibility: public -/
@[rust_fun "tacenta_spqr::{tacenta_spqr::State}::init_alice"]
axiom tacenta_spqr.State.init_alice
  : Slice Std.U8 → Result tacenta_spqr.State

/-- [tacenta_spqr::{tacenta_spqr::State}::init_bob]:
    Source: 'spqr/src/lib.rs', lines 327:4-327:39
    Name pattern: [tacenta_spqr::{tacenta_spqr::State}::init_bob]
    Visibility: public -/
@[rust_fun "tacenta_spqr::{tacenta_spqr::State}::init_bob"]
axiom tacenta_spqr.State.init_bob : Slice Std.U8 → Result tacenta_spqr.State

/-- [tacenta_spqr::{tacenta_spqr::State}::epoch]:
    Source: 'spqr/src/lib.rs', lines 355:4-355:30
    Name pattern: [tacenta_spqr::{tacenta_spqr::State}::epoch]
    Visibility: public -/
@[rust_fun "tacenta_spqr::{tacenta_spqr::State}::epoch"]
axiom tacenta_spqr.State.epoch : tacenta_spqr.State → Result Std.U64

/-- [tacenta_spqr::{tacenta_spqr::State}::evict_oldest]:
    Source: 'spqr/src/lib.rs', lines 382:4-382:57
    Name pattern: [tacenta_spqr::{tacenta_spqr::State}::evict_oldest]
    Visibility: public -/
@[rust_fun "tacenta_spqr::{tacenta_spqr::State}::evict_oldest"]
axiom tacenta_spqr.State.evict_oldest
  :
  tacenta_spqr.State → Std.Usize → Result (Std.Usize × tacenta_spqr.State)

/-- [tacenta_spqr::{tacenta_spqr::State}::send]:
    Source: 'spqr/src/lib.rs', lines 457:4-461:38
    Name pattern: [tacenta_spqr::{tacenta_spqr::State}::send]
    Visibility: public -/
@[rust_fun "tacenta_spqr::{tacenta_spqr::State}::send"]
axiom tacenta_spqr.State.send
  :
  tacenta_spqr.State → Std.U64 → Option tacenta_spqr.Output → Result
    ((core.result.Result (Std.U64 × (Array Std.U8 32#usize))
    tacenta_spqr.SpqrError) × tacenta_spqr.State)

/-- [tacenta_spqr::{tacenta_spqr::State}::receive]:
    Source: 'spqr/src/lib.rs', lines 566:4-571:31
    Name pattern: [tacenta_spqr::{tacenta_spqr::State}::receive]
    Visibility: public -/
@[rust_fun "tacenta_spqr::{tacenta_spqr::State}::receive"]
axiom tacenta_spqr.State.receive
  :
  tacenta_spqr.State → Std.U64 → Option tacenta_spqr.Output → Std.U64 →
    Result ((core.result.Result (Array Std.U8 32#usize) tacenta_spqr.SpqrError)
    × tacenta_spqr.State)

/-- [tacenta_spqr::SpqrDecodeError]
    Source: 'spqr/src/lib.rs', lines 622:0-622:24
    Name pattern: [tacenta_spqr::SpqrDecodeError]
    Visibility: public -/
@[discriminant isize, rust_type "tacenta_spqr::SpqrDecodeError"]
inductive tacenta_spqr.SpqrDecodeError where
| UnknownVersion : tacenta_spqr.SpqrDecodeError
| TooShort : tacenta_spqr.SpqrDecodeError
| Malformed : tacenta_spqr.SpqrDecodeError

/-- [tacenta_spqr::{tacenta_spqr::State}::to_bytes]:
    Source: 'spqr/src/lib.rs', lines 757:4-757:48
    Name pattern: [tacenta_spqr::{tacenta_spqr::State}::to_bytes]
    Visibility: public -/
@[rust_fun "tacenta_spqr::{tacenta_spqr::State}::to_bytes"]
axiom tacenta_spqr.State.to_bytes
  : tacenta_spqr.State → Result (zeroize.Zeroizing (alloc.vec.Vec Std.U8))

/-- [tacenta_spqr::{tacenta_spqr::State}::from_bytes]:
    Source: 'spqr/src/lib.rs', lines 786:4-786:69
    Name pattern: [tacenta_spqr::{tacenta_spqr::State}::from_bytes]
    Visibility: public -/
@[rust_fun "tacenta_spqr::{tacenta_spqr::State}::from_bytes"]
axiom tacenta_spqr.State.from_bytes
  :
  Slice Std.U8 → Result (core.result.Result tacenta_spqr.State
    tacenta_spqr.SpqrDecodeError)

/-- Trait declaration: [zeroize::Zeroize]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 245:0-245:17
    Name pattern: [zeroize::Zeroize]
    Visibility: public -/
@[rust_trait "zeroize::Zeroize"]
structure zeroize.Zeroize (Self : Type) where
  zeroize : Self → Result Self

/-- Trait declaration: [zeroize::DefaultIsZeroes]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 255:0-255:49
    Name pattern: [zeroize::DefaultIsZeroes]
    Visibility: public -/
@[rust_trait "zeroize::DefaultIsZeroes"
  (parentClauses := ["coremarkerCopyInst", "coredefaultDefaultInst"])]
structure zeroize.DefaultIsZeroes (Self : Type) where
  coremarkerCopyInst : core.marker.Copy Self
  coredefaultDefaultInst : core.default.Default Self

/-- [zeroize::{impl zeroize::Zeroize for Z}::zeroize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 274:4-274:25
    Name pattern: [zeroize::{zeroize::Zeroize<@Z>}::zeroize]
    Visibility: public -/
@[rust_fun "zeroize::{zeroize::Zeroize<@Z>}::zeroize"]
axiom zeroize.Zeroize.Blanket.zeroize
  {Z : Type} (DefaultIsZeroesInst : zeroize.DefaultIsZeroes Z) : Z → Result Z

/-- Trait implementation: [zeroize::{impl zeroize::Zeroize for Z}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 270:0-272:23
    Name pattern: [zeroize::Zeroize<@Z>] -/
@[reducible, rust_trait_impl "zeroize::Zeroize<@Z>"]
def zeroize.Zeroize.Blanket {Z : Type} (DefaultIsZeroesInst :
  zeroize.DefaultIsZeroes Z) : zeroize.Zeroize Z := {
  zeroize := zeroize.Zeroize.Blanket.zeroize DefaultIsZeroesInst
}

/-- Trait implementation: [zeroize::{impl zeroize::DefaultIsZeroes for u8}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 282:10-282:40
    Name pattern: [zeroize::DefaultIsZeroes<u8>] -/
@[reducible, rust_trait_impl "zeroize::DefaultIsZeroes<u8>"]
def U8.Insts.ZeroizeDefaultIsZeroes : zeroize.DefaultIsZeroes Std.U8 := {
  coremarkerCopyInst := core.marker.CopyU8
  coredefaultDefaultInst := core.default.DefaultU8
}

/-- [zeroize::{impl zeroize::Zeroize for [Z; N]}::zeroize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 346:4-346:25
    Name pattern: [zeroize::{zeroize::Zeroize<[@Z; @N]>}::zeroize]
    Visibility: public -/
@[rust_fun "zeroize::{zeroize::Zeroize<[@Z; @N]>}::zeroize"]
axiom Array.Insts.ZeroizeZeroize.zeroize
  {Z : Type} {N : Std.Usize} (ZeroizeInst : zeroize.Zeroize Z) :
  Array Z N → Result (Array Z N)

/-- Trait implementation: [zeroize::{impl zeroize::Zeroize for [Z; N]}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 342:0-344:15
    Name pattern: [zeroize::Zeroize<[@Z; @N]>] -/
@[reducible, rust_trait_impl "zeroize::Zeroize<[@Z; @N]>"]
def Array.Insts.ZeroizeZeroize {Z : Type} (N : Std.Usize) (ZeroizeInst :
  zeroize.Zeroize Z) : zeroize.Zeroize (Array Z N) := {
  zeroize := Array.Insts.ZeroizeZeroize.zeroize ZeroizeInst
}

/-- [zeroize::{impl zeroize::Zeroize for alloc::vec::Vec<Z>}::zeroize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 528:4-528:25
    Name pattern: [zeroize::{zeroize::Zeroize<alloc::vec::Vec<@Z>>}::zeroize]
    Visibility: public -/
@[rust_fun "zeroize::{zeroize::Zeroize<alloc::vec::Vec<@Z>>}::zeroize"]
axiom alloc.vec.Vec.Insts.ZeroizeZeroize.zeroize
  {Z : Type} (ZeroizeInst : zeroize.Zeroize Z) :
  alloc.vec.Vec Z → Result (alloc.vec.Vec Z)

/-- Trait implementation: [zeroize::{impl zeroize::Zeroize for alloc::vec::Vec<Z>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 520:0-522:15
    Name pattern: [zeroize::Zeroize<alloc::vec::Vec<@Z>>] -/
@[reducible, rust_trait_impl "zeroize::Zeroize<alloc::vec::Vec<@Z>>"]
def alloc.vec.Vec.Insts.ZeroizeZeroize {Z : Type} (ZeroizeInst :
  zeroize.Zeroize Z) : zeroize.Zeroize (alloc.vec.Vec Z) := {
  zeroize := alloc.vec.Vec.Insts.ZeroizeZeroize.zeroize ZeroizeInst
}

/-- [zeroize::{zeroize::Zeroizing<Z>}::new]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 613:4-613:32
    Name pattern: [zeroize::{zeroize::Zeroizing<@Z>}::new]
    Visibility: public -/
@[rust_fun "zeroize::{zeroize::Zeroizing<@Z>}::new"]
axiom zeroize.Zeroizing.new
  {Z : Type} (ZeroizeInst : zeroize.Zeroize Z) :
  Z → Result (zeroize.Zeroizing Z)

/-- [zeroize::{impl core::ops::deref::Deref<Z> for zeroize::Zeroizing<Z>}::deref]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 648:4-648:25
    Name pattern: [zeroize::{core::ops::deref::Deref<zeroize::Zeroizing<@Z>, @Z>}::deref]
    Visibility: public -/
@[rust_fun
  "zeroize::{core::ops::deref::Deref<zeroize::Zeroizing<@Z>, @Z>}::deref"]
axiom zeroize.Zeroizing.Insts.CoreOpsDerefDeref.deref
  {Z : Type} (ZeroizeInst : zeroize.Zeroize Z) :
  zeroize.Zeroizing Z → Result Z

/-- [tacenta_triple::COMBINE_INFO]
    Source: 'triple/src/lib.rs', lines 59:0-59:68 -/
@[global_simps, irreducible]
def COMBINE_INFO : Slice Std.U8 :=
  Array.to_slice
    (Array.make 36#usize [
      84#u8, 97#u8, 99#u8, 101#u8, 110#u8, 116#u8, 97#u8, 95#u8, 67#u8, 85#u8,
      82#u8, 86#u8, 69#u8, 50#u8, 53#u8, 53#u8, 49#u8, 57#u8, 95#u8, 83#u8,
      72#u8, 65#u8, 45#u8, 50#u8, 53#u8, 54#u8, 95#u8, 77#u8, 76#u8, 75#u8,
      69#u8, 77#u8, 49#u8, 48#u8, 50#u8, 52#u8
      ])

/-- [tacenta_triple::SPLIT_INFO]
    Source: 'triple/src/lib.rs', lines 75:0-75:72 -/
@[global_simps, irreducible]
def SPLIT_INFO : Slice Std.U8 :=
  Array.to_slice
    (Array.make 42#usize [
      84#u8, 97#u8, 99#u8, 101#u8, 110#u8, 116#u8, 97#u8, 95#u8, 67#u8, 85#u8,
      82#u8, 86#u8, 69#u8, 50#u8, 53#u8, 53#u8, 49#u8, 57#u8, 95#u8, 83#u8,
      72#u8, 65#u8, 45#u8, 50#u8, 53#u8, 54#u8, 95#u8, 77#u8, 76#u8, 75#u8,
      69#u8, 77#u8, 49#u8, 48#u8, 50#u8, 52#u8, 58#u8, 83#u8, 112#u8, 108#u8,
      105#u8, 116#u8
      ])

/-- [tacenta_triple::Header]
    Source: 'triple/src/lib.rs', lines 84:0-92:1
    Visibility: public -/
structure Header where
  dr : tacenta_ratchet.Header
  epoch : Std.U64
  pq_n : Std.U64

/-- [tacenta_triple::{impl core::clone::Clone for tacenta_triple::Header}::clone]:
    Source: 'triple/src/lib.rs', lines 83:9-83:14
    Visibility: public -/
def Header.Insts.CoreCloneClone.clone (self : Header) : Result Header := do
  ok self

/-- Trait implementation: [tacenta_triple::{impl core::clone::Clone for tacenta_triple::Header}]
    Source: 'triple/src/lib.rs', lines 83:9-83:14 -/
@[reducible]
def Header.Insts.CoreCloneClone : core.clone.Clone Header := {
  clone := Header.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [tacenta_triple::{impl core::marker::Copy for tacenta_triple::Header}]
    Source: 'triple/src/lib.rs', lines 83:16-83:20 -/
@[reducible]
def Header.Insts.CoreMarkerCopy : core.marker.Copy Header := {
  cloneInst := Header.Insts.CoreCloneClone
}

/-- Trait implementation: [tacenta_triple::{impl core::marker::StructuralPartialEq for tacenta_triple::Header}]
    Source: 'triple/src/lib.rs', lines 83:22-83:31 -/
@[reducible]
def Header.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq Header := {
}

/-- [tacenta_triple::{impl core::cmp::PartialEq<tacenta_triple::Header> for tacenta_triple::Header}::eq]:
    Source: 'triple/src/lib.rs', lines 83:22-83:31
    Visibility: public -/
def Header.Insts.CoreCmpPartialEqHeader.eq
  (self : Header) (other : Header) : Result Bool := do
  if self.epoch = other.epoch
  then
    if self.pq_n = other.pq_n
    then
      tacenta_ratchet.Header.Insts.CoreCmpPartialEqHeader.eq self.dr other.dr
    else ok false
  else ok false

/-- Trait implementation: [tacenta_triple::{impl core::cmp::PartialEq<tacenta_triple::Header> for tacenta_triple::Header}]
    Source: 'triple/src/lib.rs', lines 83:22-83:31 -/
@[reducible]
def Header.Insts.CoreCmpPartialEqHeader : core.cmp.PartialEq Header Header := {
  eq := Header.Insts.CoreCmpPartialEqHeader.eq
}

/-- [tacenta_triple::{impl core::cmp::Eq for tacenta_triple::Header}::assert_fields_are_eq]:
    Source: 'triple/src/lib.rs', lines 83:33-83:35
    Visibility: public -/
def Header.Insts.CoreCmpEq.assert_fields_are_eq
  (self : Header) : Result Unit := do
  ok ()

/-- Trait implementation: [tacenta_triple::{impl core::cmp::Eq for tacenta_triple::Header}]
    Source: 'triple/src/lib.rs', lines 83:33-83:35 -/
@[reducible]
def Header.Insts.CoreCmpEq : core.cmp.Eq Header := {
  partialEqInst := Header.Insts.CoreCmpPartialEqHeader
  assert_fields_are_eq := Header.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [tacenta_triple::{impl core::fmt::Debug for tacenta_triple::Header}::fmt]:
    Source: 'triple/src/lib.rs', lines 83:37-83:42
    Visibility: public -/
def Header.Insts.CoreFmtDebug.fmt
  (self : Header) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ tacenta_ratchet.Header.Insts.CoreFmtDebug self.dr
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.epoch
  let dyn2 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64) self.pq_n
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "Header") (toStr "dr")
    dyn (toStr "epoch") dyn1 (toStr "pq_n") dyn2

/-- Trait implementation: [tacenta_triple::{impl core::fmt::Debug for tacenta_triple::Header}]
    Source: 'triple/src/lib.rs', lines 83:37-83:42 -/
@[reducible]
def Header.Insts.CoreFmtDebug : core.fmt.Debug Header := {
  fmt := Header.Insts.CoreFmtDebug.fmt
}

/-- [tacenta_triple::TripleError]
    Source: 'triple/src/lib.rs', lines 98:0-103:1
    Visibility: public -/
@[discriminant isize]
inductive TripleError where
| Classical : tacenta_ratchet.RatchetError → TripleError
| PostQuantum : tacenta_spqr.SpqrError → TripleError

/-- [tacenta_triple::{impl core::clone::Clone for tacenta_triple::TripleError}::clone]:
    Source: 'triple/src/lib.rs', lines 97:9-97:14
    Visibility: public -/
def TripleError.Insts.CoreCloneClone.clone
  (self : TripleError) : Result TripleError := do
  ok self

/-- Trait implementation: [tacenta_triple::{impl core::clone::Clone for tacenta_triple::TripleError}]
    Source: 'triple/src/lib.rs', lines 97:9-97:14 -/
@[reducible]
def TripleError.Insts.CoreCloneClone : core.clone.Clone TripleError := {
  clone := TripleError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [tacenta_triple::{impl core::marker::Copy for tacenta_triple::TripleError}]
    Source: 'triple/src/lib.rs', lines 97:16-97:20 -/
@[reducible]
def TripleError.Insts.CoreMarkerCopy : core.marker.Copy TripleError := {
  cloneInst := TripleError.Insts.CoreCloneClone
}

/-- Trait implementation: [tacenta_triple::{impl core::marker::StructuralPartialEq for tacenta_triple::TripleError}]
    Source: 'triple/src/lib.rs', lines 97:22-97:31 -/
@[reducible]
def TripleError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq TripleError := {
}

/-- [tacenta_triple::{impl core::cmp::PartialEq<tacenta_triple::TripleError> for tacenta_triple::TripleError}::eq]:
    Source: 'triple/src/lib.rs', lines 97:22-97:31
    Visibility: public -/
def TripleError.Insts.CoreCmpPartialEqTripleError.eq
  (self : TripleError) (other : TripleError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | TripleError.Classical __self_0 =>
      match other with
      | TripleError.Classical __arg1_0 =>
        tacenta_ratchet.RatchetError.Insts.CoreCmpPartialEqRatchetError.eq
          __self_0 __arg1_0
      | TripleError.PostQuantum _ => fail panic
    | TripleError.PostQuantum __self_0 =>
      match other with
      | TripleError.Classical _ => fail panic
      | TripleError.PostQuantum __arg1_0 =>
        tacenta_spqr.SpqrError.Insts.CoreCmpPartialEqSpqrError.eq __self_0
          __arg1_0
  else ok false

/-- Trait implementation: [tacenta_triple::{impl core::cmp::PartialEq<tacenta_triple::TripleError> for tacenta_triple::TripleError}]
    Source: 'triple/src/lib.rs', lines 97:22-97:31 -/
@[reducible]
def TripleError.Insts.CoreCmpPartialEqTripleError : core.cmp.PartialEq
  TripleError TripleError := {
  eq := TripleError.Insts.CoreCmpPartialEqTripleError.eq
}

/-- [tacenta_triple::{impl core::cmp::Eq for tacenta_triple::TripleError}::assert_fields_are_eq]:
    Source: 'triple/src/lib.rs', lines 97:33-97:35
    Visibility: public -/
def TripleError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : TripleError) : Result Unit := do
  ok ()

/-- Trait implementation: [tacenta_triple::{impl core::cmp::Eq for tacenta_triple::TripleError}]
    Source: 'triple/src/lib.rs', lines 97:33-97:35 -/
@[reducible]
def TripleError.Insts.CoreCmpEq : core.cmp.Eq TripleError := {
  partialEqInst := TripleError.Insts.CoreCmpPartialEqTripleError
  assert_fields_are_eq := TripleError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [tacenta_triple::{impl core::fmt::Debug for tacenta_triple::TripleError}::fmt]:
    Source: 'triple/src/lib.rs', lines 97:37-97:42
    Visibility: public -/
def TripleError.Insts.CoreFmtDebug.fmt
  (self : TripleError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | TripleError.Classical __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared
        tacenta_ratchet.RatchetError.Insts.CoreFmtDebug) __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Classical")
      __self_01
  | TripleError.PostQuantum __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared tacenta_spqr.SpqrError.Insts.CoreFmtDebug)
        __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "PostQuantum")
      __self_01

/-- Trait implementation: [tacenta_triple::{impl core::fmt::Debug for tacenta_triple::TripleError}]
    Source: 'triple/src/lib.rs', lines 97:37-97:42 -/
@[reducible]
def TripleError.Insts.CoreFmtDebug : core.fmt.Debug TripleError := {
  fmt := TripleError.Insts.CoreFmtDebug.fmt
}

/-- [tacenta_triple::split_secret]:
    Source: 'triple/src/lib.rs', lines 113:0-121:1
    Visibility: public -/
def split_secret
  (sk : Slice Std.U8) :
  Result ((Array Std.U8 32#usize) × (Array Std.U8 32#usize))
  := do
  let a := Array.repeat 32#usize 0#u8
  let s ← lift (Array.to_slice a)
  let a1 ← tacenta_kdf.hkdf_sha256 64#usize s sk SPLIT_INFO
  let out ←
    zeroize.Zeroizing.new (Array.Insts.ZeroizeZeroize 64#usize
      (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes)) a1
  let ec := Array.repeat 32#usize 0#u8
  let pq := Array.repeat 32#usize 0#u8
  let (s1, to_slice_mut_back) ← lift (Array.to_slice_mut ec)
  let a2 ←
    zeroize.Zeroizing.Insts.CoreOpsDerefDeref.deref (Array.Insts.ZeroizeZeroize
      64#usize (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes)) out
  let s2 ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) a2
      { start := 0#usize, «end» := 32#usize }
  let s3 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s1 s2
  let (s4, to_slice_mut_back1) ← lift (Array.to_slice_mut pq)
  let s5 ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) a2
      { start := 32#usize, «end» := 64#usize }
  let s6 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s4 s5
  let ec1 := to_slice_mut_back s3
  let pq1 := to_slice_mut_back1 s6
  ok (ec1, pq1)

/-- [tacenta_triple::combine]:
    Source: 'triple/src/lib.rs', lines 128:0-137:1
    Visibility: public -/
def combine
  (mk_classical : Array Std.U8 32#usize) (mk_pq : Array Std.U8 32#usize) :
  Result (Array Std.U8 32#usize)
  := do
  let s ← lift (Array.to_slice mk_pq)
  let s1 ← lift (Array.to_slice mk_classical)
  tacenta_kdf.hkdf_sha256 32#usize s s1 COMBINE_INFO

/-- [tacenta_triple::State]
    Source: 'triple/src/lib.rs', lines 150:0-153:1
    Visibility: public -/
structure State where
  classical : tacenta_ratchet.State
  post_quantum : tacenta_spqr.State

/-- [tacenta_triple::{impl core::clone::Clone for tacenta_triple::State}::clone]:
    Source: 'triple/src/lib.rs', lines 149:9-149:14
    Visibility: public -/
def State.Insts.CoreCloneClone.clone (self : State) : Result State := do
  let s ← tacenta_ratchet.State.Insts.CoreCloneClone.clone self.classical
  let s1 ← tacenta_spqr.State.Insts.CoreCloneClone.clone self.post_quantum
  ok { classical := s, post_quantum := s1 }

/-- Trait implementation: [tacenta_triple::{impl core::clone::Clone for tacenta_triple::State}]
    Source: 'triple/src/lib.rs', lines 149:9-149:14 -/
@[reducible]
def State.Insts.CoreCloneClone : core.clone.Clone State := {
  clone := State.Insts.CoreCloneClone.clone
}

/-- [tacenta_triple::{tacenta_triple::State}::init_sender]:
    Source: 'triple/src/lib.rs', lines 172:4-187:5
    Visibility: public -/
def State.init_sender
  (sk : Slice Std.U8) (our_pub : Array Std.U8 32#usize)
  (peer_pub : Array Std.U8 32#usize) (dh_out : Array Std.U8 32#usize)
  (labels : tacenta_ratchet.LabelSet) :
  Result State
  := do
  let (ec, pq) ← split_secret sk
  let s ← tacenta_ratchet.init_sender ec our_pub peer_pub dh_out labels
  let s1 ← lift (Array.to_slice pq)
  let s2 ← tacenta_spqr.State.init_alice s1
  let _ ←
    Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes) ec
  let _ ←
    Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes) pq
  ok { classical := s, post_quantum := s2 }

/-- [tacenta_triple::{tacenta_triple::State}::init_receiver]:
    Source: 'triple/src/lib.rs', lines 190:4-199:5
    Visibility: public -/
def State.init_receiver
  (sk : Slice Std.U8) (our_pub : Array Std.U8 32#usize)
  (labels : tacenta_ratchet.LabelSet) :
  Result State
  := do
  let (ec, pq) ← split_secret sk
  let s ← tacenta_ratchet.init_receiver ec our_pub labels
  let s1 ← lift (Array.to_slice pq)
  let s2 ← tacenta_spqr.State.init_bob s1
  let _ ←
    Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes) ec
  let _ ←
    Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes) pq
  ok { classical := s, post_quantum := s2 }

/-- [tacenta_triple::{tacenta_triple::State}::sending_public]:
    Source: 'triple/src/lib.rs', lines 203:4-205:5
    Visibility: public -/
def State.sending_public (self : State) : Result (Array Std.U8 32#usize) := do
  tacenta_ratchet.State.sending_public self.classical

/-- [tacenta_triple::{tacenta_triple::State}::send_count]:
    Source: 'triple/src/lib.rs', lines 211:4-213:5
    Visibility: public -/
def State.send_count (self : State) : Result Std.U32 := do
  tacenta_ratchet.State.send_count self.classical

/-- [tacenta_triple::{tacenta_triple::State}::receive_count]:
    Source: 'triple/src/lib.rs', lines 216:4-218:5
    Visibility: public -/
def State.receive_count (self : State) : Result Std.U32 := do
  tacenta_ratchet.State.receive_count self.classical

/-- [tacenta_triple::{tacenta_triple::State}::classical_skipped_len]:
    Source: 'triple/src/lib.rs', lines 224:4-226:5
    Visibility: public -/
def State.classical_skipped_len (self : State) : Result Std.Usize := do
  tacenta_ratchet.State.skipped_len self.classical

/-- [tacenta_triple::{tacenta_triple::State}::evict_oldest_classical]:
    Source: 'triple/src/lib.rs', lines 235:4-237:5
    Visibility: public -/
def State.evict_oldest_classical
  (self : State) (count : Std.Usize) : Result (Std.Usize × State) := do
  let (i, s) ← tacenta_ratchet.State.evict_oldest self.classical count
  ok (i, { self with classical := s })

/-- [tacenta_triple::{tacenta_triple::State}::evict_oldest_post_quantum]:
    Source: 'triple/src/lib.rs', lines 241:4-243:5
    Visibility: public -/
def State.evict_oldest_post_quantum
  (self : State) (count : Std.Usize) : Result (Std.Usize × State) := do
  let (i, s) ← tacenta_spqr.State.evict_oldest self.post_quantum count
  ok (i, { self with post_quantum := s })

/-- [tacenta_triple::{tacenta_triple::State}::epoch]:
    Source: 'triple/src/lib.rs', lines 246:4-248:5
    Visibility: public -/
def State.epoch (self : State) : Result Std.U64 := do
  tacenta_spqr.State.epoch self.post_quantum

/-- [tacenta_triple::{tacenta_triple::State}::send]:
    Source: 'triple/src/lib.rs', lines 283:4-312:5
    Visibility: public -/
def State.send
  (self : State) (sending_epoch : Std.U64)
  (output : Option tacenta_spqr.Output) :
  Result ((core.result.Result (Header × (Array Std.U8 32#usize)) TripleError)
    × State)
  := do
  let candidate ← State.Insts.CoreCloneClone.clone self
  let (r, s) ← tacenta_ratchet.send candidate.classical
  match r with
  | core.result.Result.Ok v =>
    let (dr, mk_ec) := v
    let (r1, s1) ←
      tacenta_spqr.State.send candidate.post_quantum sending_epoch output
    match r1 with
    | core.result.Result.Ok v1 =>
      let (pq_n, mk_pq) := v1
      let key ← combine mk_ec mk_pq
      let _ ←
        Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
          U8.Insts.ZeroizeDefaultIsZeroes) mk_ec
      let _ ←
        Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
          U8.Insts.ZeroizeDefaultIsZeroes) mk_pq
      ok (core.result.Result.Ok ({ dr, epoch := sending_epoch, pq_n }, key),
        { classical := s, post_quantum := s1 })
    | core.result.Result.Err e =>
      let _ ←
        Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
          U8.Insts.ZeroizeDefaultIsZeroes) mk_ec
      ok (core.result.Result.Err (TripleError.PostQuantum e), self)
  | core.result.Result.Err e =>
    ok (core.result.Result.Err (TripleError.Classical e), self)

/-- [tacenta_triple::{tacenta_triple::State}::receive]:
    Source: 'triple/src/lib.rs', lines 339:4-372:5
    Visibility: public -/
def State.receive
  (self : State) (header : Header) (dh_out_recv : Array Std.U8 32#usize)
  (dh_out_send : Array Std.U8 32#usize) (new_dhs_pub : Array Std.U8 32#usize)
  (output : Option tacenta_spqr.Output) :
  Result (core.result.Result (State × (Array Std.U8 32#usize)) TripleError)
  := do
  let candidate ← State.Insts.CoreCloneClone.clone self
  let (r, s) ←
    tacenta_ratchet.receive candidate.classical header.dr dh_out_recv
      dh_out_send new_dhs_pub
  match r with
  | core.result.Result.Ok v =>
    let (r1, s1) ←
      tacenta_spqr.State.receive candidate.post_quantum header.epoch output
        header.pq_n
    match r1 with
    | core.result.Result.Ok v1 =>
      let key ← combine v v1
      let _ ←
        Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
          U8.Insts.ZeroizeDefaultIsZeroes) v
      let _ ←
        Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
          U8.Insts.ZeroizeDefaultIsZeroes) v1
      ok (core.result.Result.Ok ({ classical := s, post_quantum := s1 }, key))
    | core.result.Result.Err e =>
      let _ ←
        Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
          U8.Insts.ZeroizeDefaultIsZeroes) v
      ok (core.result.Result.Err (TripleError.PostQuantum e))
  | core.result.Result.Err e =>
    ok (core.result.Result.Err (TripleError.Classical e))

/-- [tacenta_triple::{tacenta_triple::State}::commit]:
    Source: 'triple/src/lib.rs', lines 381:4-383:5
    Visibility: public -/
def State.commit (self : State) (next : State) : Result State := do
  ok next

/-- [tacenta_triple::STATE_VERSION]
    Source: 'triple/src/lib.rs', lines 390:0-390:31 -/
@[global_simps, irreducible] def STATE_VERSION : Std.U8 := 1#u8

/-- [tacenta_triple::TripleDecodeError]
    Source: 'triple/src/lib.rs', lines 402:0-406:1
    Visibility: public -/
@[discriminant isize]
inductive TripleDecodeError where
| UnknownVersion : TripleDecodeError
| TooShort : TripleDecodeError
| Malformed : TripleDecodeError

/-- [tacenta_triple::{impl core::clone::Clone for tacenta_triple::TripleDecodeError}::clone]:
    Source: 'triple/src/lib.rs', lines 401:9-401:14
    Visibility: public -/
def TripleDecodeError.Insts.CoreCloneClone.clone
  (self : TripleDecodeError) : Result TripleDecodeError := do
  ok self

/-- Trait implementation: [tacenta_triple::{impl core::clone::Clone for tacenta_triple::TripleDecodeError}]
    Source: 'triple/src/lib.rs', lines 401:9-401:14 -/
@[reducible]
def TripleDecodeError.Insts.CoreCloneClone : core.clone.Clone TripleDecodeError
  := {
  clone := TripleDecodeError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [tacenta_triple::{impl core::marker::Copy for tacenta_triple::TripleDecodeError}]
    Source: 'triple/src/lib.rs', lines 401:16-401:20 -/
@[reducible]
def TripleDecodeError.Insts.CoreMarkerCopy : core.marker.Copy TripleDecodeError
  := {
  cloneInst := TripleDecodeError.Insts.CoreCloneClone
}

/-- Trait implementation: [tacenta_triple::{impl core::marker::StructuralPartialEq for tacenta_triple::TripleDecodeError}]
    Source: 'triple/src/lib.rs', lines 401:22-401:31 -/
@[reducible]
def TripleDecodeError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq TripleDecodeError := {
}

/-- [tacenta_triple::{impl core::cmp::PartialEq<tacenta_triple::TripleDecodeError> for tacenta_triple::TripleDecodeError}::eq]:
    Source: 'triple/src/lib.rs', lines 401:22-401:31
    Visibility: public -/
def TripleDecodeError.Insts.CoreCmpPartialEqTripleDecodeError.eq
  (self : TripleDecodeError) (other : TripleDecodeError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [tacenta_triple::{impl core::cmp::PartialEq<tacenta_triple::TripleDecodeError> for tacenta_triple::TripleDecodeError}]
    Source: 'triple/src/lib.rs', lines 401:22-401:31 -/
@[reducible]
def TripleDecodeError.Insts.CoreCmpPartialEqTripleDecodeError :
  core.cmp.PartialEq TripleDecodeError TripleDecodeError := {
  eq := TripleDecodeError.Insts.CoreCmpPartialEqTripleDecodeError.eq
}

/-- [tacenta_triple::{impl core::cmp::Eq for tacenta_triple::TripleDecodeError}::assert_fields_are_eq]:
    Source: 'triple/src/lib.rs', lines 401:33-401:35
    Visibility: public -/
def TripleDecodeError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : TripleDecodeError) : Result Unit := do
  ok ()

/-- Trait implementation: [tacenta_triple::{impl core::cmp::Eq for tacenta_triple::TripleDecodeError}]
    Source: 'triple/src/lib.rs', lines 401:33-401:35 -/
@[reducible]
def TripleDecodeError.Insts.CoreCmpEq : core.cmp.Eq TripleDecodeError := {
  partialEqInst := TripleDecodeError.Insts.CoreCmpPartialEqTripleDecodeError
  assert_fields_are_eq :=
    TripleDecodeError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [tacenta_triple::{impl core::fmt::Debug for tacenta_triple::TripleDecodeError}::fmt]:
    Source: 'triple/src/lib.rs', lines 401:37-401:42
    Visibility: public -/
def TripleDecodeError.Insts.CoreFmtDebug.fmt
  (self : TripleDecodeError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | TripleDecodeError.UnknownVersion =>
    core.fmt.Formatter.write_str f (toStr "UnknownVersion")
  | TripleDecodeError.TooShort =>
    core.fmt.Formatter.write_str f (toStr "TooShort")
  | TripleDecodeError.Malformed =>
    core.fmt.Formatter.write_str f (toStr "Malformed")

/-- Trait implementation: [tacenta_triple::{impl core::fmt::Debug for tacenta_triple::TripleDecodeError}]
    Source: 'triple/src/lib.rs', lines 401:37-401:42 -/
@[reducible]
def TripleDecodeError.Insts.CoreFmtDebug : core.fmt.Debug TripleDecodeError
  := {
  fmt := TripleDecodeError.Insts.CoreFmtDebug.fmt
}

/-- [tacenta_triple::take_len_prefixed]:
    Source: 'triple/src/lib.rs', lines 410:0-432:1 -/
def take_len_prefixed
  (bytes : Slice Std.U8) (pos : Std.Usize) :
  Result (Option ((Slice Std.U8) × Std.Usize))
  := do
  let o ← lift (Usize.checked_add pos 4#usize)
  match o with
  | none => ok none
  | some s =>
    let i := Slice.len bytes
    if i < s
    then ok none
    else
      let len_bytes := Array.repeat 4#usize 0#u8
      let (s1, to_slice_mut_back) ← lift (Array.to_slice_mut len_bytes)
      let s2 ←
        core.slice.index.Slice.index
          (core.slice.index.SliceIndexRangeUsizeSlice Std.U8) bytes
          { start := pos, «end» := s }
      let s3 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s1 s2
      let len_bytes1 := to_slice_mut_back s3
      let i1 ← lift (core.num.U32.from_be_bytes len_bytes1)
      let len ← lift (UScalar.cast .Usize i1)
      let o1 ← lift (Usize.checked_add s len)
      match o1 with
      | none => ok none
      | some e =>
        let i2 := Slice.len bytes
        if i2 < e
        then ok none
        else
          let s4 ←
            core.slice.index.Slice.index
              (core.slice.index.SliceIndexRangeUsizeSlice Std.U8) bytes
              { start := s, «end» := e }
          ok (some (s4, e))

/-- [tacenta_triple::{tacenta_triple::State}::to_bytes]:
    Source: 'triple/src/lib.rs', lines 441:4-451:5
    Visibility: public -/
def State.to_bytes
  (self : State) : Result (zeroize.Zeroizing (alloc.vec.Vec Std.U8)) := do
  let out ← alloc.vec.Vec.push (alloc.vec.Vec.new Std.U8) STATE_VERSION
  let classical ← tacenta_ratchet.State.to_bytes self.classical
  let v ←
    zeroize.Zeroizing.Insts.CoreOpsDerefDeref.deref
      (alloc.vec.Vec.Insts.ZeroizeZeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes)) classical
  let i := alloc.vec.Vec.len v
  let i1 ← lift (UScalar.cast .U32 i)
  let a ← lift (core.num.U32.to_be_bytes i1)
  let s ← lift (Array.to_slice a)
  let out1 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s
  let s1 := alloc.vec.Vec.deref v
  let out2 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out1 s1
  let post_quantum ← tacenta_spqr.State.to_bytes self.post_quantum
  let v1 ←
    zeroize.Zeroizing.Insts.CoreOpsDerefDeref.deref
      (alloc.vec.Vec.Insts.ZeroizeZeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes)) post_quantum
  let i2 := alloc.vec.Vec.len v1
  let i3 ← lift (UScalar.cast .U32 i2)
  let a1 ← lift (core.num.U32.to_be_bytes i3)
  let s2 ← lift (Array.to_slice a1)
  let out3 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out2 s2
  let s3 := alloc.vec.Vec.deref v1
  let out4 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out3 s3
  zeroize.Zeroizing.new (alloc.vec.Vec.Insts.ZeroizeZeroize
    (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes)) out4

/-- [tacenta_triple::{tacenta_triple::State}::from_bytes]:
    Source: 'triple/src/lib.rs', lines 454:4-480:5
    Visibility: public -/
def State.from_bytes
  (bytes : Slice Std.U8) :
  Result (core.result.Result State TripleDecodeError)
  := do
  let b ← core.slice.Slice.is_empty bytes
  if b
  then ok (core.result.Result.Err TripleDecodeError.TooShort)
  else
    let i ← Slice.index_usize bytes 0#usize
    if i != STATE_VERSION
    then ok (core.result.Result.Err TripleDecodeError.UnknownVersion)
    else
      let o ← take_len_prefixed bytes 1#usize
      match o with
      | none => ok (core.result.Result.Err TripleDecodeError.TooShort)
      | some p =>
        let (classical_bytes, pos) := p
        let r ← tacenta_ratchet.State.from_bytes classical_bytes
        match r with
        | core.result.Result.Ok classical =>
          let o1 ← take_len_prefixed bytes pos
          match o1 with
          | none => ok (core.result.Result.Err TripleDecodeError.TooShort)
          | some p1 =>
            let (pq_bytes, pos1) := p1
            let r1 ← tacenta_spqr.State.from_bytes pq_bytes
            match r1 with
            | core.result.Result.Ok post_quantum =>
              let i1 := Slice.len bytes
              if pos1 != i1
              then ok (core.result.Result.Err TripleDecodeError.Malformed)
              else ok (core.result.Result.Ok { classical, post_quantum })
            | core.result.Result.Err _ =>
              ok (core.result.Result.Err TripleDecodeError.Malformed)
        | core.result.Result.Err _ =>
          ok (core.result.Result.Err TripleDecodeError.Malformed)

end tacenta_triple
