-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [tacenta_session]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace tacenta_session

/-- [tacenta_kdf::hkdf_sha256]:
    Source: 'kdf/src/lib.rs', lines 27:0-27:83
    Name pattern: [tacenta_kdf::hkdf_sha256]
    Visibility: public -/
@[rust_fun "tacenta_kdf::hkdf_sha256"]
axiom tacenta_kdf.hkdf_sha256
  (N : Std.Usize) :
  Slice Std.U8 → Slice Std.U8 → Slice Std.U8 → Result (Array Std.U8 N)

/-- Trait declaration: [zeroize::Zeroize]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 245:0-245:17
    Name pattern: [zeroize::Zeroize]
    Visibility: public -/
@[rust_trait "zeroize::Zeroize"]
structure zeroize.Zeroize (Self : Type) where
  zeroize : Self → Result Self

/-- Trait declaration: [zeroize::DefaultIsZeroes]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 255:0-255:49
    Name pattern: [zeroize::DefaultIsZeroes]
    Visibility: public -/
@[rust_trait "zeroize::DefaultIsZeroes"
  (parentClauses := ["coremarkerCopyInst", "coredefaultDefaultInst"])]
structure zeroize.DefaultIsZeroes (Self : Type) where
  coremarkerCopyInst : core.marker.Copy Self
  coredefaultDefaultInst : core.default.Default Self

/-- [zeroize::{impl zeroize::Zeroize for Z}::zeroize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 274:4-274:25
    Name pattern: [zeroize::{zeroize::Zeroize<@Z>}::zeroize]
    Visibility: public -/
@[rust_fun "zeroize::{zeroize::Zeroize<@Z>}::zeroize"]
axiom zeroize.Zeroize.Blanket.zeroize
  {Z : Type} (DefaultIsZeroesInst : zeroize.DefaultIsZeroes Z) : Z → Result Z

/-- Trait implementation: [zeroize::{impl zeroize::Zeroize for Z}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 270:0-272:23
    Name pattern: [zeroize::Zeroize<@Z>] -/
@[reducible, rust_trait_impl "zeroize::Zeroize<@Z>"]
def zeroize.Zeroize.Blanket {Z : Type} (DefaultIsZeroesInst :
  zeroize.DefaultIsZeroes Z) : zeroize.Zeroize Z := {
  zeroize := zeroize.Zeroize.Blanket.zeroize DefaultIsZeroesInst
}

/-- Trait implementation: [zeroize::{impl zeroize::DefaultIsZeroes for u8}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 282:10-282:40
    Name pattern: [zeroize::DefaultIsZeroes<u8>] -/
@[reducible, rust_trait_impl "zeroize::DefaultIsZeroes<u8>"]
def U8.Insts.ZeroizeDefaultIsZeroes : zeroize.DefaultIsZeroes Std.U8 := {
  coremarkerCopyInst := core.marker.CopyU8
  coredefaultDefaultInst := core.default.DefaultU8
}

/-- [zeroize::{impl zeroize::Zeroize for alloc::vec::Vec<Z>}::zeroize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 528:4-528:25
    Name pattern: [zeroize::{zeroize::Zeroize<alloc::vec::Vec<@Z>>}::zeroize]
    Visibility: public -/
@[rust_fun "zeroize::{zeroize::Zeroize<alloc::vec::Vec<@Z>>}::zeroize"]
axiom alloc.vec.Vec.Insts.ZeroizeZeroize.zeroize
  {Z : Type} (ZeroizeInst : zeroize.Zeroize Z) :
  alloc.vec.Vec Z → Result (alloc.vec.Vec Z)

/-- Trait implementation: [zeroize::{impl zeroize::Zeroize for alloc::vec::Vec<Z>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 520:0-522:15
    Name pattern: [zeroize::Zeroize<alloc::vec::Vec<@Z>>] -/
@[reducible, rust_trait_impl "zeroize::Zeroize<alloc::vec::Vec<@Z>>"]
def alloc.vec.Vec.Insts.ZeroizeZeroize {Z : Type} (ZeroizeInst :
  zeroize.Zeroize Z) : zeroize.Zeroize (alloc.vec.Vec Z) := {
  zeroize := alloc.vec.Vec.Insts.ZeroizeZeroize.zeroize ZeroizeInst
}

/-- [zeroize::Zeroizing]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 604:0-604:41
    Name pattern: [zeroize::Zeroizing]
    Visibility: public -/
@[rust_type "zeroize::Zeroizing"]
axiom zeroize.Zeroizing (Z : Type) : Type

/-- [zeroize::{zeroize::Zeroizing<Z>}::new]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 613:4-613:32
    Name pattern: [zeroize::{zeroize::Zeroizing<@Z>}::new]
    Visibility: public -/
@[rust_fun "zeroize::{zeroize::Zeroizing<@Z>}::new"]
axiom zeroize.Zeroizing.new
  {Z : Type} (ZeroizeInst : zeroize.Zeroize Z) :
  Z → Result (zeroize.Zeroizing Z)

/-- [zeroize::{impl core::ops::deref::Deref<Z> for zeroize::Zeroizing<Z>}::deref]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 648:4-648:25
    Name pattern: [zeroize::{core::ops::deref::Deref<zeroize::Zeroizing<@Z>, @Z>}::deref]
    Visibility: public -/
@[rust_fun
  "zeroize::{core::ops::deref::Deref<zeroize::Zeroizing<@Z>, @Z>}::deref"]
axiom zeroize.Zeroizing.Insts.CoreOpsDerefDeref.deref
  {Z : Type} (ZeroizeInst : zeroize.Zeroize Z) :
  zeroize.Zeroizing Z → Result Z

/-- [zeroize::{impl core::ops::deref::DerefMut<Z> for zeroize::Zeroizing<Z>}::deref_mut]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 658:4-658:37
    Name pattern: [zeroize::{core::ops::deref::DerefMut<zeroize::Zeroizing<@Z>, @Z>}::deref_mut]
    Visibility: public -/
@[rust_fun
  "zeroize::{core::ops::deref::DerefMut<zeroize::Zeroizing<@Z>, @Z>}::deref_mut"]
axiom zeroize.Zeroizing.Insts.CoreOpsDerefDerefMut.deref_mut
  {Z : Type} (ZeroizeInst : zeroize.Zeroize Z) :
  zeroize.Zeroizing Z → Result (Z × (Z → zeroize.Zeroizing Z))

/-- [tacenta_session::F_PREFIX]
    Source: 'session/src/lib.rs', lines 40:0-40:38 -/
@[global_simps, irreducible]
def F_PREFIX : Array Std.U8 32#usize := Array.repeat 32#usize 255#u8

/-- [tacenta_session::SK_INFO]
    Source: 'session/src/lib.rs', lines 45:0-45:65 -/
@[global_simps, irreducible]
def SK_INFO : Slice Std.U8 :=
  Array.to_slice
    (Array.make 38#usize [
      84#u8, 97#u8, 99#u8, 101#u8, 110#u8, 116#u8, 97#u8, 95#u8, 67#u8, 85#u8,
      82#u8, 86#u8, 69#u8, 50#u8, 53#u8, 53#u8, 49#u8, 57#u8, 95#u8, 83#u8,
      72#u8, 65#u8, 45#u8, 50#u8, 53#u8, 54#u8, 95#u8, 77#u8, 76#u8, 45#u8,
      75#u8, 69#u8, 77#u8, 45#u8, 49#u8, 48#u8, 50#u8, 52#u8
      ])

/-- [tacenta_session::ENCODE_EC_CURVE25519]
    Source: 'session/src/lib.rs', lines 52:0-52:42
    Visibility: public -/
@[global_simps, irreducible] def ENCODE_EC_CURVE25519 : Std.U8 := 5#u8

/-- [tacenta_session::ENCODE_KEM_ML_KEM_1024]
    Source: 'session/src/lib.rs', lines 64:0-64:44
    Visibility: public -/
@[global_simps, irreducible] def ENCODE_KEM_ML_KEM_1024 : Std.U8 := 8#u8

/-- [tacenta_session::ENCODE_EC_LEN]
    Source: 'session/src/lib.rs', lines 71:0-71:36
    Visibility: public -/
@[global_simps, irreducible] def ENCODE_EC_LEN : Std.Usize := 33#usize

/-- [tacenta_session::km]:
    Source: 'session/src/lib.rs', lines 81:0-97:1
    Visibility: public -/
def km
  (dh1 : Array Std.U8 32#usize) (dh2 : Array Std.U8 32#usize)
  (dh3 : Array Std.U8 32#usize) (dh4 : Option (Array Std.U8 32#usize))
  (ss : Array Std.U8 32#usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let i ← 5#usize * 32#usize
  let out := alloc.vec.Vec.with_capacity Std.U8 i
  let s ← lift (Array.to_slice dh1)
  let out1 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s
  let s1 ← lift (Array.to_slice dh2)
  let out2 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out1 s1
  let s2 ← lift (Array.to_slice dh3)
  let out3 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out2 s2
  let out4 ←
    match dh4 with
    | none => ok out3
    | some d4 =>
      do
      let s3 ← lift (Array.to_slice d4)
      alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out3 s3
  let s3 ← lift (Array.to_slice ss)
  alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out4 s3

/-- [tacenta_session::kdf_sk]:
    Source: 'session/src/lib.rs', lines 104:0-116:1
    Visibility: public -/
def kdf_sk (km_bytes : Slice Std.U8) : Result (Array Std.U8 32#usize) := do
  let s ← lift (Array.to_slice F_PREFIX)
  let i := Slice.len s
  let i1 := Slice.len km_bytes
  let i2 ← lift (core.num.Usize.saturating_add i i1)
  let v := alloc.vec.Vec.with_capacity Std.U8 i2
  let ikm ←
    zeroize.Zeroizing.new (alloc.vec.Vec.Insts.ZeroizeZeroize
      (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes)) v
  let (v1, deref_mut_back) ←
    zeroize.Zeroizing.Insts.CoreOpsDerefDerefMut.deref_mut
      (alloc.vec.Vec.Insts.ZeroizeZeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes)) ikm
  let s1 ← lift (Array.to_slice F_PREFIX)
  let v2 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 v1 s1
  let ikm1 := deref_mut_back v2
  let (v3, deref_mut_back1) ←
    zeroize.Zeroizing.Insts.CoreOpsDerefDerefMut.deref_mut
      (alloc.vec.Vec.Insts.ZeroizeZeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes)) ikm1
  let v4 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 v3 km_bytes
  let a := Array.repeat 32#usize 0#u8
  let s2 ← lift (Array.to_slice a)
  let ikm2 := deref_mut_back1 v4
  let v5 ←
    zeroize.Zeroizing.Insts.CoreOpsDerefDeref.deref
      (alloc.vec.Vec.Insts.ZeroizeZeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes)) ikm2
  let s3 := alloc.vec.Vec.deref v5
  tacenta_kdf.hkdf_sha256 32#usize s2 s3 SK_INFO

/-- [tacenta_session::shared_secret]:
    Source: 'session/src/lib.rs', lines 123:0-128:1
    Visibility: public -/
def shared_secret
  (dh1 : Array Std.U8 32#usize) (dh2 : Array Std.U8 32#usize)
  (dh3 : Array Std.U8 32#usize) (dh4 : Option (Array Std.U8 32#usize))
  (ss : Array Std.U8 32#usize) :
  Result (Array Std.U8 32#usize)
  := do
  let v ← km dh1 dh2 dh3 dh4 ss
  let material ←
    zeroize.Zeroizing.new (alloc.vec.Vec.Insts.ZeroizeZeroize
      (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes)) v
  let v1 ←
    zeroize.Zeroizing.Insts.CoreOpsDerefDeref.deref
      (alloc.vec.Vec.Insts.ZeroizeZeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes)) material
  let s := alloc.vec.Vec.deref v1
  kdf_sk s

/-- [tacenta_session::associated_data]:
    Source: 'session/src/lib.rs', lines 139:0-146:1
    Visibility: public -/
def associated_data
  (encoded_ik_a : Slice Std.U8) (encoded_ik_b : Slice Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let i := Slice.len encoded_ik_a
  let i1 := Slice.len encoded_ik_b
  let i2 ← lift (core.num.Usize.saturating_add i i1)
  let ad := alloc.vec.Vec.with_capacity Std.U8 i2
  let ad1 ←
    alloc.vec.Vec.extend_from_slice core.clone.CloneU8 ad encoded_ik_a
  alloc.vec.Vec.extend_from_slice core.clone.CloneU8 ad1 encoded_ik_b

/-- [tacenta_session::associated_data_with_kem]:
    Source: 'session/src/lib.rs', lines 150:0-158:1
    Visibility: public -/
def associated_data_with_kem
  (encoded_ik_a : Slice Std.U8) (encoded_ik_b : Slice Std.U8)
  (encoded_pq_pk : Slice Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let ad ← associated_data encoded_ik_a encoded_ik_b
  alloc.vec.Vec.extend_from_slice core.clone.CloneU8 ad encoded_pq_pk

/-- [tacenta_session::encode_ec]:
    Source: 'session/src/lib.rs', lines 161:0-166:1
    Visibility: public -/
def encode_ec
  (pk : Array Std.U8 32#usize) : Result (alloc.vec.Vec Std.U8) := do
  let out ←
    alloc.vec.Vec.push (alloc.vec.Vec.new Std.U8) ENCODE_EC_CURVE25519
  let s ← lift (Array.to_slice pk)
  alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s

/-- [tacenta_session::encode_kem]:
    Source: 'session/src/lib.rs', lines 169:0-174:1
    Visibility: public -/
def encode_kem (pk : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  let out ←
    alloc.vec.Vec.push (alloc.vec.Vec.new Std.U8) ENCODE_KEM_ML_KEM_1024
  alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out pk

/-- [tacenta_session::decode_ec]: loop body 0:
    Source: 'session/src/lib.rs', lines 185:8-188:9
    Visibility: public -/
@[rust_loop_body]
def decode_ec_loop.body
  (bytes : Slice Std.U8) (k : Array Std.U8 32#usize) (i : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 32#usize) × Std.Usize) (Array Std.U8
    32#usize))
  := do
  if i < 32#usize
  then
    let i1 ← i + 1#usize
    let i2 ← Slice.index_usize bytes i1
    let a ← Array.update k i i2
    ok (cont (a, i1))
  else ok (done k)

/-- [tacenta_session::decode_ec]: loop 0:
    Source: 'session/src/lib.rs', lines 185:8-188:9
    Visibility: public -/
@[rust_loop]
def decode_ec_loop
  (bytes : Slice Std.U8) (k : Array Std.U8 32#usize) (i : Std.Usize) :
  Result (Array Std.U8 32#usize)
  := do
  loop
    (fun (k1, i1) => decode_ec_loop.body bytes k1 i1)
    (k, i)

/-- [tacenta_session::decode_ec]:
    Source: 'session/src/lib.rs', lines 178:0-193:1
    Visibility: public -/
def decode_ec
  (bytes : Slice Std.U8) : Result (Option (Array Std.U8 32#usize)) := do
  let i := Slice.len bytes
  if i = ENCODE_EC_LEN
  then
    let i1 ← Slice.index_usize bytes 0#usize
    if i1 = ENCODE_EC_CURVE25519
    then
      let k := Array.repeat 32#usize 0#u8
      let k1 ← decode_ec_loop bytes k 0#usize
      ok (some k1)
    else ok none
  else ok none

end tacenta_session
