-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [tacenta_ratchet]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace tacenta_ratchet

/-- [core::option::{impl core::clone::Clone for core::option::Option<T>}::clone]:
    Source: '/rustc/library/core/src/option.rs', lines 2277:4-2277:27
    Name pattern: [core::option::{core::clone::Clone<core::option::Option<@T>>}::clone]
    Visibility: public -/
@[rust_fun
  "core::option::{core::clone::Clone<core::option::Option<@T>>}::clone"]
axiom core.option.Option.Insts.CoreCloneClone.clone
  {T : Type} (cloneCloneInst : core.clone.Clone T) :
  Option T → Result (Option T)

/-- [alloc::vec::{alloc::vec::Vec<T>}::remove]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2401:4-2401:47
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::remove]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::remove"]
axiom alloc.vec.Vec.remove
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Std.Usize → Result (T × (alloc.vec.Vec T))

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3085:4-3085:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::is_empty]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
axiom alloc.vec.Vec.is_empty
  {T : Type} (A : Type) : alloc.vec.Vec T → Result Bool

/-- [tacenta_kdf::hkdf_sha256]:
    Source: 'kdf/src/lib.rs', lines 27:0-27:83
    Name pattern: [tacenta_kdf::hkdf_sha256]
    Visibility: public -/
@[rust_fun "tacenta_kdf::hkdf_sha256"]
axiom tacenta_kdf.hkdf_sha256
  (N : Std.Usize) :
  Slice Std.U8 → Slice Std.U8 → Slice Std.U8 → Result (Array Std.U8 N)

/-- [tacenta_kdf::hmac_sha256]:
    Source: 'kdf/src/lib.rs', lines 34:0-34:55
    Name pattern: [tacenta_kdf::hmac_sha256]
    Visibility: public -/
@[rust_fun "tacenta_kdf::hmac_sha256"]
axiom tacenta_kdf.hmac_sha256
  : Slice Std.U8 → Slice Std.U8 → Result (Array Std.U8 32#usize)

/-- Trait declaration: [zeroize::Zeroize]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 245:0-245:17
    Name pattern: [zeroize::Zeroize]
    Visibility: public -/
@[rust_trait "zeroize::Zeroize"]
structure zeroize.Zeroize (Self : Type) where
  zeroize : Self → Result Self

/-- Trait declaration: [zeroize::ZeroizeOnDrop]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 252:0-252:23
    Name pattern: [zeroize::ZeroizeOnDrop]
    Visibility: public -/
@[rust_trait "zeroize::ZeroizeOnDrop"]
structure zeroize.ZeroizeOnDrop (Self : Type) where

/-- Trait declaration: [zeroize::DefaultIsZeroes]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 255:0-255:49
    Name pattern: [zeroize::DefaultIsZeroes]
    Visibility: public -/
@[rust_trait "zeroize::DefaultIsZeroes"
  (parentClauses := ["coremarkerCopyInst", "coredefaultDefaultInst"])]
structure zeroize.DefaultIsZeroes (Self : Type) where
  coremarkerCopyInst : core.marker.Copy Self
  coredefaultDefaultInst : core.default.Default Self

/-- [zeroize::{impl zeroize::Zeroize for Z}::zeroize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 274:4-274:25
    Name pattern: [zeroize::{zeroize::Zeroize<@Z>}::zeroize]
    Visibility: public -/
@[rust_fun "zeroize::{zeroize::Zeroize<@Z>}::zeroize"]
axiom zeroize.Zeroize.Blanket.zeroize
  {Z : Type} (DefaultIsZeroesInst : zeroize.DefaultIsZeroes Z) : Z → Result Z

/-- Trait implementation: [zeroize::{impl zeroize::Zeroize for Z}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 270:0-272:23
    Name pattern: [zeroize::Zeroize<@Z>] -/
@[reducible, rust_trait_impl "zeroize::Zeroize<@Z>"]
def zeroize.Zeroize.Blanket {Z : Type} (DefaultIsZeroesInst :
  zeroize.DefaultIsZeroes Z) : zeroize.Zeroize Z := {
  zeroize := zeroize.Zeroize.Blanket.zeroize DefaultIsZeroesInst
}

/-- Trait implementation: [zeroize::{impl zeroize::DefaultIsZeroes for u8}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 282:10-282:40
    Name pattern: [zeroize::DefaultIsZeroes<u8>] -/
@[reducible, rust_trait_impl "zeroize::DefaultIsZeroes<u8>"]
def U8.Insts.ZeroizeDefaultIsZeroes : zeroize.DefaultIsZeroes Std.U8 := {
  coremarkerCopyInst := core.marker.CopyU8
  coredefaultDefaultInst := core.default.DefaultU8
}

/-- Trait implementation: [zeroize::{impl zeroize::DefaultIsZeroes for u32}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 282:10-282:40
    Name pattern: [zeroize::DefaultIsZeroes<u32>] -/
@[reducible, rust_trait_impl "zeroize::DefaultIsZeroes<u32>"]
def U32.Insts.ZeroizeDefaultIsZeroes : zeroize.DefaultIsZeroes Std.U32 := {
  coremarkerCopyInst := core.marker.CopyU32
  coredefaultDefaultInst := core.default.DefaultU32
}

/-- [zeroize::{impl zeroize::Zeroize for [Z; N]}::zeroize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 346:4-346:25
    Name pattern: [zeroize::{zeroize::Zeroize<[@Z; @N]>}::zeroize]
    Visibility: public -/
@[rust_fun "zeroize::{zeroize::Zeroize<[@Z; @N]>}::zeroize"]
axiom Array.Insts.ZeroizeZeroize.zeroize
  {Z : Type} {N : Std.Usize} (ZeroizeInst : zeroize.Zeroize Z) :
  Array Z N → Result (Array Z N)

/-- Trait implementation: [zeroize::{impl zeroize::Zeroize for [Z; N]}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 342:0-344:15
    Name pattern: [zeroize::Zeroize<[@Z; @N]>] -/
@[reducible, rust_trait_impl "zeroize::Zeroize<[@Z; @N]>"]
def Array.Insts.ZeroizeZeroize {Z : Type} (N : Std.Usize) (ZeroizeInst :
  zeroize.Zeroize Z) : zeroize.Zeroize (Array Z N) := {
  zeroize := Array.Insts.ZeroizeZeroize.zeroize ZeroizeInst
}

/-- [zeroize::{impl zeroize::Zeroize for core::option::Option<Z>}::zeroize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 369:4-369:25
    Name pattern: [zeroize::{zeroize::Zeroize<core::option::Option<@Z>>}::zeroize]
    Visibility: public -/
@[rust_fun "zeroize::{zeroize::Zeroize<core::option::Option<@Z>>}::zeroize"]
axiom core.option.Option.Insts.ZeroizeZeroize.zeroize
  {Z : Type} (ZeroizeInst : zeroize.Zeroize Z) : Option Z → Result (Option Z)

/-- Trait implementation: [zeroize::{impl zeroize::Zeroize for core::option::Option<Z>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 365:0-367:15
    Name pattern: [zeroize::Zeroize<core::option::Option<@Z>>] -/
@[reducible, rust_trait_impl "zeroize::Zeroize<core::option::Option<@Z>>"]
def core.option.Option.Insts.ZeroizeZeroize {Z : Type} (ZeroizeInst :
  zeroize.Zeroize Z) : zeroize.Zeroize (Option Z) := {
  zeroize := core.option.Option.Insts.ZeroizeZeroize.zeroize ZeroizeInst
}

/-- [zeroize::{impl zeroize::Zeroize for (A, B)}::zeroize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 496:12-496:33
    Name pattern: [zeroize::{zeroize::Zeroize<(@A, @B)>}::zeroize]
    Visibility: public -/
@[rust_fun "zeroize::{zeroize::Zeroize<(@A, @B)>}::zeroize"]
axiom Pair.Insts.ZeroizeZeroize.zeroize
  {A : Type} {B : Type} (ZeroizeInst : zeroize.Zeroize A) (ZeroizeInst1 :
  zeroize.Zeroize B) :
  (A × B) → Result (A × B)

/-- Trait implementation: [zeroize::{impl zeroize::Zeroize for (A, B)}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 495:8-495:68
    Name pattern: [zeroize::Zeroize<(@A, @B)>] -/
@[reducible, rust_trait_impl "zeroize::Zeroize<(@A, @B)>"]
def Pair.Insts.ZeroizeZeroize {A : Type} {B : Type} (ZeroizeInst :
  zeroize.Zeroize A) (ZeroizeInst1 : zeroize.Zeroize B) : zeroize.Zeroize (A ×
  B) := {
  zeroize := Pair.Insts.ZeroizeZeroize.zeroize ZeroizeInst ZeroizeInst1
}

/-- [zeroize::{impl zeroize::Zeroize for alloc::vec::Vec<Z>}::zeroize]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 528:4-528:25
    Name pattern: [zeroize::{zeroize::Zeroize<alloc::vec::Vec<@Z>>}::zeroize]
    Visibility: public -/
@[rust_fun "zeroize::{zeroize::Zeroize<alloc::vec::Vec<@Z>>}::zeroize"]
axiom alloc.vec.Vec.Insts.ZeroizeZeroize.zeroize
  {Z : Type} (ZeroizeInst : zeroize.Zeroize Z) :
  alloc.vec.Vec Z → Result (alloc.vec.Vec Z)

/-- Trait implementation: [zeroize::{impl zeroize::Zeroize for alloc::vec::Vec<Z>}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 520:0-522:15
    Name pattern: [zeroize::Zeroize<alloc::vec::Vec<@Z>>] -/
@[reducible, rust_trait_impl "zeroize::Zeroize<alloc::vec::Vec<@Z>>"]
def alloc.vec.Vec.Insts.ZeroizeZeroize {Z : Type} (ZeroizeInst :
  zeroize.Zeroize Z) : zeroize.Zeroize (alloc.vec.Vec Z) := {
  zeroize := alloc.vec.Vec.Insts.ZeroizeZeroize.zeroize ZeroizeInst
}

/-- [zeroize::Zeroizing]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 604:0-604:41
    Name pattern: [zeroize::Zeroizing]
    Visibility: public -/
@[rust_type "zeroize::Zeroizing"]
axiom zeroize.Zeroizing (Z : Type) : Type

/-- [zeroize::{zeroize::Zeroizing<Z>}::new]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 613:4-613:32
    Name pattern: [zeroize::{zeroize::Zeroizing<@Z>}::new]
    Visibility: public -/
@[rust_fun "zeroize::{zeroize::Zeroizing<@Z>}::new"]
axiom zeroize.Zeroizing.new
  {Z : Type} (ZeroizeInst : zeroize.Zeroize Z) :
  Z → Result (zeroize.Zeroizing Z)

/-- [zeroize::{impl core::ops::deref::Deref<Z> for zeroize::Zeroizing<Z>}::deref]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 648:4-648:25
    Name pattern: [zeroize::{core::ops::deref::Deref<zeroize::Zeroizing<@Z>, @Z>}::deref]
    Visibility: public -/
@[rust_fun
  "zeroize::{core::ops::deref::Deref<zeroize::Zeroizing<@Z>, @Z>}::deref"]
axiom zeroize.Zeroizing.Insts.CoreOpsDerefDeref.deref
  {Z : Type} (ZeroizeInst : zeroize.Zeroize Z) :
  zeroize.Zeroizing Z → Result Z

/-- [zeroize::{impl core::ops::deref::DerefMut<Z> for zeroize::Zeroizing<Z>}::deref_mut]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 658:4-658:37
    Name pattern: [zeroize::{core::ops::deref::DerefMut<zeroize::Zeroizing<@Z>, @Z>}::deref_mut]
    Visibility: public -/
@[rust_fun
  "zeroize::{core::ops::deref::DerefMut<zeroize::Zeroizing<@Z>, @Z>}::deref_mut"]
axiom zeroize.Zeroizing.Insts.CoreOpsDerefDerefMut.deref_mut
  {Z : Type} (ZeroizeInst : zeroize.Zeroize Z) :
  zeroize.Zeroizing Z → Result (Z × (Z → zeroize.Zeroizing Z))

/-- [zeroize::__internal::{impl zeroize::__internal::AssertZeroize for T}::zeroize_or_on_drop]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.9.0/src/lib.rs', lines 846:8-846:40
    Name pattern: [zeroize::__internal::{zeroize::__internal::AssertZeroize<@T>}::zeroize_or_on_drop]
    Visibility: public -/
@[rust_fun
  "zeroize::__internal::{zeroize::__internal::AssertZeroize<@T>}::zeroize_or_on_drop"]
axiom zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
  {T : Type} (ZeroizeInst : zeroize.Zeroize T) : T → Result T

/-- [tacenta_ratchet::LabelSet]
    Source: 'ratchet/src/lib.rs', lines 68:0-72:1
    Visibility: public -/
@[discriminant isize]
inductive LabelSet where
| Tacenta : LabelSet

/-- [tacenta_ratchet::{impl core::clone::Clone for tacenta_ratchet::LabelSet}::clone]:
    Source: 'ratchet/src/lib.rs', lines 67:9-67:14
    Visibility: public -/
def LabelSet.Insts.CoreCloneClone.clone
  (self : LabelSet) : Result LabelSet := do
  ok self

/-- Trait implementation: [tacenta_ratchet::{impl core::clone::Clone for tacenta_ratchet::LabelSet}]
    Source: 'ratchet/src/lib.rs', lines 67:9-67:14 -/
@[reducible]
def LabelSet.Insts.CoreCloneClone : core.clone.Clone LabelSet := {
  clone := LabelSet.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [tacenta_ratchet::{impl core::marker::Copy for tacenta_ratchet::LabelSet}]
    Source: 'ratchet/src/lib.rs', lines 67:16-67:20 -/
@[reducible]
def LabelSet.Insts.CoreMarkerCopy : core.marker.Copy LabelSet := {
  cloneInst := LabelSet.Insts.CoreCloneClone
}

/-- Trait implementation: [tacenta_ratchet::{impl core::marker::StructuralPartialEq for tacenta_ratchet::LabelSet}]
    Source: 'ratchet/src/lib.rs', lines 67:22-67:31 -/
@[reducible]
def LabelSet.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq LabelSet := {
}

/-- [tacenta_ratchet::{impl core::cmp::PartialEq<tacenta_ratchet::LabelSet> for tacenta_ratchet::LabelSet}::eq]:
    Source: 'ratchet/src/lib.rs', lines 67:22-67:31
    Visibility: public -/
def LabelSet.Insts.CoreCmpPartialEqLabelSet.eq
  (self : LabelSet) (other : LabelSet) : Result Bool := do
  ok true

/-- Trait implementation: [tacenta_ratchet::{impl core::cmp::PartialEq<tacenta_ratchet::LabelSet> for tacenta_ratchet::LabelSet}]
    Source: 'ratchet/src/lib.rs', lines 67:22-67:31 -/
@[reducible]
impl_def LabelSet.Insts.CoreCmpPartialEqLabelSet : core.cmp.PartialEq LabelSet
  LabelSet := {
  eq := LabelSet.Insts.CoreCmpPartialEqLabelSet.eq
  ne := core.cmp.PartialEq.ne.trait_default
    LabelSet.Insts.CoreCmpPartialEqLabelSet
}

/-- [tacenta_ratchet::{impl core::cmp::Eq for tacenta_ratchet::LabelSet}::assert_fields_are_eq]:
    Source: 'ratchet/src/lib.rs', lines 67:33-67:35
    Visibility: public -/
def LabelSet.Insts.CoreCmpEq.assert_fields_are_eq
  (self : LabelSet) : Result Unit := do
  ok ()

/-- Trait implementation: [tacenta_ratchet::{impl core::cmp::Eq for tacenta_ratchet::LabelSet}]
    Source: 'ratchet/src/lib.rs', lines 67:33-67:35 -/
@[reducible]
def LabelSet.Insts.CoreCmpEq : core.cmp.Eq LabelSet := {
  partialEqInst := LabelSet.Insts.CoreCmpPartialEqLabelSet
  assert_fields_are_eq := LabelSet.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [tacenta_ratchet::{impl core::fmt::Debug for tacenta_ratchet::LabelSet}::fmt]:
    Source: 'ratchet/src/lib.rs', lines 67:37-67:42
    Visibility: public -/
def LabelSet.Insts.CoreFmtDebug.fmt
  (self : LabelSet) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  core.fmt.Formatter.write_str f (toStr "Tacenta")

/-- Trait implementation: [tacenta_ratchet::{impl core::fmt::Debug for tacenta_ratchet::LabelSet}]
    Source: 'ratchet/src/lib.rs', lines 67:37-67:42 -/
@[reducible]
def LabelSet.Insts.CoreFmtDebug : core.fmt.Debug LabelSet := {
  fmt := LabelSet.Insts.CoreFmtDebug.fmt
}

/-- [tacenta_ratchet::RK_INFO]
    Source: 'ratchet/src/lib.rs', lines 74:0-74:37 -/
@[global_simps, irreducible]
def RK_INFO : Slice Std.U8 :=
  Array.to_slice
    (Array.make 10#usize [
      84#u8, 97#u8, 99#u8, 101#u8, 110#u8, 116#u8, 97#u8, 32#u8, 82#u8, 75#u8
      ])

/-- [tacenta_ratchet::MK_INFO]
    Source: 'ratchet/src/lib.rs', lines 76:0-76:37 -/
@[global_simps, irreducible]
def MK_INFO : Slice Std.U8 :=
  Array.to_slice
    (Array.make 10#usize [
      84#u8, 97#u8, 99#u8, 101#u8, 110#u8, 116#u8, 97#u8, 32#u8, 77#u8, 75#u8
      ])

/-- [tacenta_ratchet::MAX_SKIP]
    Source: 'ratchet/src/lib.rs', lines 80:0-80:31
    Visibility: public -/
@[global_simps, irreducible] def MAX_SKIP : Std.U32 := 1000#u32

/-- [tacenta_ratchet::MAX_SKIPPED_STORE]
    Source: 'ratchet/src/lib.rs', lines 86:0-86:42
    Visibility: public -/
@[global_simps, irreducible] def MAX_SKIPPED_STORE : Std.Usize := 2000#usize

/-- [tacenta_ratchet::MAX_SKIPPED_AGE]
    Source: 'ratchet/src/lib.rs', lines 97:0-97:38
    Visibility: public -/
@[global_simps, irreducible] def MAX_SKIPPED_AGE : Std.U32 := 1000#u32

/-- [tacenta_ratchet::MAX_EVENTS]
    Source: 'ratchet/src/lib.rs', lines 107:0-107:38 -/
@[global_simps, irreducible] def MAX_EVENTS : Std.U32 := 4294967294#u32

/-- [tacenta_ratchet::MAX_EVENTS_IS_ONE_BELOW_THE_CEILING]
    Source: 'ratchet/src/lib.rs', lines 116:0-116:84 -/
@[global_simps, irreducible]
def MAX_EVENTS_IS_ONE_BELOW_THE_CEILING : Result Unit := do
  let i ← core.num.U32.MAX - 1#u32
  massert (MAX_EVENTS = i)

/-- [tacenta_ratchet::Header]
    Source: 'ratchet/src/lib.rs', lines 124:0-128:1
    Visibility: public -/
structure Header where
  dh : Array Std.U8 32#usize
  pn : Std.U32
  n : Std.U32

/-- [tacenta_ratchet::{impl core::clone::Clone for tacenta_ratchet::Header}::clone]:
    Source: 'ratchet/src/lib.rs', lines 123:9-123:14
    Visibility: public -/
def Header.Insts.CoreCloneClone.clone (self : Header) : Result Header := do
  ok self

/-- Trait implementation: [tacenta_ratchet::{impl core::clone::Clone for tacenta_ratchet::Header}]
    Source: 'ratchet/src/lib.rs', lines 123:9-123:14 -/
@[reducible]
def Header.Insts.CoreCloneClone : core.clone.Clone Header := {
  clone := Header.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [tacenta_ratchet::{impl core::marker::Copy for tacenta_ratchet::Header}]
    Source: 'ratchet/src/lib.rs', lines 123:16-123:20 -/
@[reducible]
def Header.Insts.CoreMarkerCopy : core.marker.Copy Header := {
  cloneInst := Header.Insts.CoreCloneClone
}

/-- Trait implementation: [tacenta_ratchet::{impl core::marker::StructuralPartialEq for tacenta_ratchet::Header}]
    Source: 'ratchet/src/lib.rs', lines 123:22-123:31 -/
@[reducible]
def Header.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq Header := {
}

/-- [tacenta_ratchet::{impl core::cmp::PartialEq<tacenta_ratchet::Header> for tacenta_ratchet::Header}::eq]:
    Source: 'ratchet/src/lib.rs', lines 123:22-123:31
    Visibility: public -/
def Header.Insts.CoreCmpPartialEqHeader.eq
  (self : Header) (other : Header) : Result Bool := do
  if self.pn = other.pn
  then
    if self.n = other.n
    then
      core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 self.dh
        other.dh
    else ok false
  else ok false

/-- Trait implementation: [tacenta_ratchet::{impl core::cmp::PartialEq<tacenta_ratchet::Header> for tacenta_ratchet::Header}]
    Source: 'ratchet/src/lib.rs', lines 123:22-123:31 -/
@[reducible]
impl_def Header.Insts.CoreCmpPartialEqHeader : core.cmp.PartialEq Header Header
  := {
  eq := Header.Insts.CoreCmpPartialEqHeader.eq
  ne := core.cmp.PartialEq.ne.trait_default Header.Insts.CoreCmpPartialEqHeader
}

/-- [tacenta_ratchet::{impl core::cmp::Eq for tacenta_ratchet::Header}::assert_fields_are_eq]:
    Source: 'ratchet/src/lib.rs', lines 123:33-123:35
    Visibility: public -/
def Header.Insts.CoreCmpEq.assert_fields_are_eq
  (self : Header) : Result Unit := do
  ok ()

/-- Trait implementation: [tacenta_ratchet::{impl core::cmp::Eq for tacenta_ratchet::Header}]
    Source: 'ratchet/src/lib.rs', lines 123:33-123:35 -/
@[reducible]
def Header.Insts.CoreCmpEq : core.cmp.Eq Header := {
  partialEqInst := Header.Insts.CoreCmpPartialEqHeader
  assert_fields_are_eq := Header.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [tacenta_ratchet::{impl core::fmt::Debug for tacenta_ratchet::Header}::fmt]:
    Source: 'ratchet/src/lib.rs', lines 123:37-123:42
    Visibility: public -/
def Header.Insts.CoreFmtDebug.fmt
  (self : Header) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn :=
    Dyn.mk _ (Array.Insts.CoreFmtDebug 32#usize core.fmt.DebugU8) self.dh
  let dyn1 := Dyn.mk _ core.fmt.DebugU32 self.pn
  let dyn2 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU32) self.n
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "Header") (toStr "dh")
    dyn (toStr "pn") dyn1 (toStr "n") dyn2

/-- Trait implementation: [tacenta_ratchet::{impl core::fmt::Debug for tacenta_ratchet::Header}]
    Source: 'ratchet/src/lib.rs', lines 123:37-123:42 -/
@[reducible]
def Header.Insts.CoreFmtDebug : core.fmt.Debug Header := {
  fmt := Header.Insts.CoreFmtDebug.fmt
}

/-- [tacenta_ratchet::SkippedKey]
    Source: 'ratchet/src/lib.rs', lines 137:0-148:1 -/
structure SkippedKey where
  dh : Array Std.U8 32#usize
  n : Std.U32
  stored_at : Std.U32
  key : Array Std.U8 32#usize

/-- [tacenta_ratchet::{impl core::clone::Clone for tacenta_ratchet::SkippedKey}::clone]:
    Source: 'ratchet/src/lib.rs', lines 135:9-135:14
    Visibility: public -/
def SkippedKey.Insts.CoreCloneClone.clone
  (self : SkippedKey) : Result SkippedKey := do
  let a ← core.array.CloneArray.clone core.clone.CloneU8 self.dh
  let i ← lift (core.clone.impls.CloneU32.clone self.n)
  let i1 ← lift (core.clone.impls.CloneU32.clone self.stored_at)
  let a1 ← core.array.CloneArray.clone core.clone.CloneU8 self.key
  ok { dh := a, n := i, stored_at := i1, key := a1 }

/-- Trait implementation: [tacenta_ratchet::{impl core::clone::Clone for tacenta_ratchet::SkippedKey}]
    Source: 'ratchet/src/lib.rs', lines 135:9-135:14 -/
@[reducible]
def SkippedKey.Insts.CoreCloneClone : core.clone.Clone SkippedKey := {
  clone := SkippedKey.Insts.CoreCloneClone.clone
}

/-- [tacenta_ratchet::{impl zeroize::Zeroize for tacenta_ratchet::SkippedKey}::zeroize]:
    Source: 'ratchet/src/lib.rs', lines 135:16-135:23
    Visibility: public -/
def SkippedKey.Insts.ZeroizeZeroize.zeroize
  (self : SkippedKey) : Result SkippedKey := do
  let dh ←
    Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes) self.dh
  let n ←
    zeroize.Zeroize.Blanket.zeroize U32.Insts.ZeroizeDefaultIsZeroes self.n
  let stored_at ←
    zeroize.Zeroize.Blanket.zeroize U32.Insts.ZeroizeDefaultIsZeroes
      self.stored_at
  let key ←
    Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes) self.key
  ok { dh, n, stored_at, key }

/-- Trait implementation: [tacenta_ratchet::{impl zeroize::Zeroize for tacenta_ratchet::SkippedKey}]
    Source: 'ratchet/src/lib.rs', lines 135:16-135:23 -/
@[reducible]
def SkippedKey.Insts.ZeroizeZeroize : zeroize.Zeroize SkippedKey := {
  zeroize := SkippedKey.Insts.ZeroizeZeroize.zeroize
}

/-- [tacenta_ratchet::{impl core::ops::drop::Drop for tacenta_ratchet::SkippedKey}::drop]:
    Source: 'ratchet/src/lib.rs', lines 135:25-135:38
    Visibility: public -/
def SkippedKey.Insts.CoreOpsDropDrop.drop
  (self : SkippedKey) : Result SkippedKey := do
  let dh ←
    zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
      (Array.Insts.ZeroizeZeroize 32#usize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes)) self.dh
  let n ←
    zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
      (zeroize.Zeroize.Blanket U32.Insts.ZeroizeDefaultIsZeroes) self.n
  let stored_at ←
    zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
      (zeroize.Zeroize.Blanket U32.Insts.ZeroizeDefaultIsZeroes) self.stored_at
  let key ←
    zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
      (Array.Insts.ZeroizeZeroize 32#usize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes)) self.key
  ok { dh, n, stored_at, key }

/-- Trait implementation: [tacenta_ratchet::{impl core::ops::drop::Drop for tacenta_ratchet::SkippedKey}]
    Source: 'ratchet/src/lib.rs', lines 135:25-135:38 -/
@[reducible]
def SkippedKey.Insts.CoreOpsDropDrop : core.ops.drop.Drop SkippedKey := {
  drop := SkippedKey.Insts.CoreOpsDropDrop.drop
}

/-- Trait implementation: [tacenta_ratchet::{impl zeroize::ZeroizeOnDrop for tacenta_ratchet::SkippedKey}]
    Source: 'ratchet/src/lib.rs', lines 135:25-135:38 -/
@[reducible]
def SkippedKey.Insts.ZeroizeZeroizeOnDrop : zeroize.ZeroizeOnDrop SkippedKey
  := {
}

/-- [tacenta_ratchet::State]
    Source: 'ratchet/src/lib.rs', lines 162:0-185:1
    Visibility: public -/
structure State where
  dhs_pub : Array Std.U8 32#usize
  dhr_pub : Option (Array Std.U8 32#usize)
  rk : Array Std.U8 32#usize
  cks : Option (Array Std.U8 32#usize)
  ckr : Option (Array Std.U8 32#usize)
  ns : Std.U32
  nr : Std.U32
  pn : Std.U32
  skipped : alloc.vec.Vec SkippedKey
  events : Std.U32
  labels : LabelSet

/-- [tacenta_ratchet::{impl core::clone::Clone for tacenta_ratchet::State}::clone]:
    Source: 'ratchet/src/lib.rs', lines 160:9-160:14
    Visibility: public -/
def State.Insts.CoreCloneClone.clone (self : State) : Result State := do
  let a ← core.array.CloneArray.clone core.clone.CloneU8 self.dhs_pub
  let o ←
    core.option.Option.Insts.CoreCloneClone.clone (core.clone.CloneArray
      32#usize core.clone.CloneU8) self.dhr_pub
  let a1 ← core.array.CloneArray.clone core.clone.CloneU8 self.rk
  let o1 ←
    core.option.Option.Insts.CoreCloneClone.clone (core.clone.CloneArray
      32#usize core.clone.CloneU8) self.cks
  let o2 ←
    core.option.Option.Insts.CoreCloneClone.clone (core.clone.CloneArray
      32#usize core.clone.CloneU8) self.ckr
  let i ← lift (core.clone.impls.CloneU32.clone self.ns)
  let i1 ← lift (core.clone.impls.CloneU32.clone self.nr)
  let i2 ← lift (core.clone.impls.CloneU32.clone self.pn)
  let v ←
    alloc.vec.CloneVec.clone SkippedKey.Insts.CoreCloneClone self.skipped
  let i3 ← lift (core.clone.impls.CloneU32.clone self.events)
  let ls ← LabelSet.Insts.CoreCloneClone.clone self.labels
  ok
    {
      dhs_pub := a,
      dhr_pub := o,
      rk := a1,
      cks := o1,
      ckr := o2,
      ns := i,
      nr := i1,
      pn := i2,
      skipped := v,
      events := i3,
      labels := ls
    }

/-- Trait implementation: [tacenta_ratchet::{impl core::clone::Clone for tacenta_ratchet::State}]
    Source: 'ratchet/src/lib.rs', lines 160:9-160:14 -/
@[reducible]
def State.Insts.CoreCloneClone : core.clone.Clone State := {
  clone := State.Insts.CoreCloneClone.clone
}

/-- [tacenta_ratchet::{impl zeroize::Zeroize for tacenta_ratchet::State}::zeroize]:
    Source: 'ratchet/src/lib.rs', lines 160:16-160:23
    Visibility: public -/
def State.Insts.ZeroizeZeroize.zeroize (self : State) : Result State := do
  let dhs_pub ←
    Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes) self.dhs_pub
  let dhr_pub ←
    core.option.Option.Insts.ZeroizeZeroize.zeroize (Array.Insts.ZeroizeZeroize
      32#usize (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes))
      self.dhr_pub
  let rk ←
    Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes) self.rk
  let cks ←
    core.option.Option.Insts.ZeroizeZeroize.zeroize (Array.Insts.ZeroizeZeroize
      32#usize (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes))
      self.cks
  let ckr ←
    core.option.Option.Insts.ZeroizeZeroize.zeroize (Array.Insts.ZeroizeZeroize
      32#usize (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes))
      self.ckr
  let ns ←
    zeroize.Zeroize.Blanket.zeroize U32.Insts.ZeroizeDefaultIsZeroes self.ns
  let nr ←
    zeroize.Zeroize.Blanket.zeroize U32.Insts.ZeroizeDefaultIsZeroes self.nr
  let pn ←
    zeroize.Zeroize.Blanket.zeroize U32.Insts.ZeroizeDefaultIsZeroes self.pn
  let skipped ←
    alloc.vec.Vec.Insts.ZeroizeZeroize.zeroize SkippedKey.Insts.ZeroizeZeroize
      self.skipped
  let events ←
    zeroize.Zeroize.Blanket.zeroize U32.Insts.ZeroizeDefaultIsZeroes
      self.events
  ok { self with dhs_pub, dhr_pub, rk, cks, ckr, ns, nr, pn, skipped, events }

/-- Trait implementation: [tacenta_ratchet::{impl zeroize::Zeroize for tacenta_ratchet::State}]
    Source: 'ratchet/src/lib.rs', lines 160:16-160:23 -/
@[reducible]
def State.Insts.ZeroizeZeroize : zeroize.Zeroize State := {
  zeroize := State.Insts.ZeroizeZeroize.zeroize
}

/-- [tacenta_ratchet::{impl core::ops::drop::Drop for tacenta_ratchet::State}::drop]:
    Source: 'ratchet/src/lib.rs', lines 160:25-160:38
    Visibility: public -/
def State.Insts.CoreOpsDropDrop.drop (self : State) : Result State := do
  let dhs_pub ←
    zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
      (Array.Insts.ZeroizeZeroize 32#usize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes)) self.dhs_pub
  let dhr_pub ←
    zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
      (core.option.Option.Insts.ZeroizeZeroize (Array.Insts.ZeroizeZeroize
      32#usize (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes)))
      self.dhr_pub
  let rk ←
    zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
      (Array.Insts.ZeroizeZeroize 32#usize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes)) self.rk
  let cks ←
    zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
      (core.option.Option.Insts.ZeroizeZeroize (Array.Insts.ZeroizeZeroize
      32#usize (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes)))
      self.cks
  let ckr ←
    zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
      (core.option.Option.Insts.ZeroizeZeroize (Array.Insts.ZeroizeZeroize
      32#usize (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes)))
      self.ckr
  let ns ←
    zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
      (zeroize.Zeroize.Blanket U32.Insts.ZeroizeDefaultIsZeroes) self.ns
  let nr ←
    zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
      (zeroize.Zeroize.Blanket U32.Insts.ZeroizeDefaultIsZeroes) self.nr
  let pn ←
    zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
      (zeroize.Zeroize.Blanket U32.Insts.ZeroizeDefaultIsZeroes) self.pn
  let skipped ←
    zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
      (alloc.vec.Vec.Insts.ZeroizeZeroize SkippedKey.Insts.ZeroizeZeroize)
      self.skipped
  let events ←
    zeroize.__internal.AssertZeroize.Blanket.zeroize_or_on_drop
      (zeroize.Zeroize.Blanket U32.Insts.ZeroizeDefaultIsZeroes) self.events
  ok { self with dhs_pub, dhr_pub, rk, cks, ckr, ns, nr, pn, skipped, events }

/-- Trait implementation: [tacenta_ratchet::{impl core::ops::drop::Drop for tacenta_ratchet::State}]
    Source: 'ratchet/src/lib.rs', lines 160:25-160:38 -/
@[reducible]
def State.Insts.CoreOpsDropDrop : core.ops.drop.Drop State := {
  drop := State.Insts.CoreOpsDropDrop.drop
}

/-- Trait implementation: [tacenta_ratchet::{impl zeroize::ZeroizeOnDrop for tacenta_ratchet::State}]
    Source: 'ratchet/src/lib.rs', lines 160:25-160:38 -/
@[reducible]
def State.Insts.ZeroizeZeroizeOnDrop : zeroize.ZeroizeOnDrop State := {
}

/-- [tacenta_ratchet::{tacenta_ratchet::State}::labels]:
    Source: 'ratchet/src/lib.rs', lines 218:4-220:5
    Visibility: public -/
def State.impl.labels (self : State) : Result LabelSet := do
  ok self.labels

/-- [tacenta_ratchet::{tacenta_ratchet::State}::skipped_len]:
    Source: 'ratchet/src/lib.rs', lines 224:4-226:5
    Visibility: public -/
def State.skipped_len (self : State) : Result Std.Usize := do
  ok (alloc.vec.Vec.len self.skipped)

/-- [tacenta_ratchet::{tacenta_ratchet::State}::evict_oldest]: loop body 1:
    Source: 'ratchet/src/lib.rs', lines 260:12-265:13
    Visibility: public -/
@[rust_loop_body]
def State.evict_oldest_loop0_loop0.body
  (v : alloc.vec.Vec SkippedKey) (oldest : Std.Usize) (i : Std.Usize) :
  Result (ControlFlow (Std.Usize × Std.Usize) Std.Usize)
  := do
  let i1 := alloc.vec.Vec.len v
  if i < i1
  then
    let sk ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice SkippedKey) v
        i
    let sk1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice SkippedKey) v
        oldest
    let oldest1 ← if sk.stored_at < sk1.stored_at
                    then ok i
                    else ok oldest
    let i2 ← i + 1#usize
    ok (cont (oldest1, i2))
  else ok (done oldest)

/-- [tacenta_ratchet::{tacenta_ratchet::State}::evict_oldest]: loop 1:
    Source: 'ratchet/src/lib.rs', lines 260:12-265:13
    Visibility: public -/
@[rust_loop]
def State.evict_oldest_loop0_loop0
  (v : alloc.vec.Vec SkippedKey) (oldest : Std.Usize) (i : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun (oldest1, i1) => State.evict_oldest_loop0_loop0.body v oldest1 i1)
    (oldest, i)

/-- [tacenta_ratchet::{tacenta_ratchet::State}::evict_oldest]: loop body 0:
    Source: 'ratchet/src/lib.rs', lines 1:0-268:9
    Visibility: public -/
@[rust_loop_body]
def State.evict_oldest_loop0.body
  (count : Std.Usize) (self : State) (evicted : Std.Usize) :
  Result (ControlFlow (State × Std.Usize) (Std.Usize × State))
  := do
  if evicted < count
  then
    let b ← alloc.vec.Vec.is_empty Global self.skipped
    if b
    then ok (done (evicted, self))
    else
      let oldest ←
        State.evict_oldest_loop0_loop0 self.skipped 0#usize 1#usize
      let (_, v) ← alloc.vec.Vec.remove Global self.skipped oldest
      let evicted1 ← evicted + 1#usize
      ok (cont ({ self with skipped := v }, evicted1))
  else ok (done (evicted, self))

/-- [tacenta_ratchet::{tacenta_ratchet::State}::evict_oldest]: loop 0:
    Source: 'ratchet/src/lib.rs', lines 1:0-268:9
    Visibility: public -/
@[rust_loop]
def State.evict_oldest_loop0
  (self : State) (count : Std.Usize) (evicted : Std.Usize) :
  Result (Std.Usize × State)
  := do
  loop
    (fun (self1, evicted1) => State.evict_oldest_loop0.body count self1
      evicted1)
    (self, evicted)

/-- [tacenta_ratchet::{tacenta_ratchet::State}::evict_oldest]:
    Source: 'ratchet/src/lib.rs', lines 255:4-270:5
    Visibility: public -/
@[reducible]
def State.evict_oldest
  (self : State) (count : Std.Usize) : Result (Std.Usize × State) := do
  State.evict_oldest_loop0 self count 0#usize

/-- [tacenta_ratchet::RatchetError]
    Source: 'ratchet/src/lib.rs', lines 275:0-293:1
    Visibility: public -/
@[discriminant isize]
inductive RatchetError where
| TooManySkipped : RatchetError
| SkippedStoreFull : RatchetError
| NoSendingChain : RatchetError
| NoReceivingChain : RatchetError
| OutOfOrder : RatchetError
| ChainExhausted : RatchetError

/-- [tacenta_ratchet::{impl core::clone::Clone for tacenta_ratchet::RatchetError}::clone]:
    Source: 'ratchet/src/lib.rs', lines 274:9-274:14
    Visibility: public -/
def RatchetError.Insts.CoreCloneClone.clone
  (self : RatchetError) : Result RatchetError := do
  ok self

/-- Trait implementation: [tacenta_ratchet::{impl core::clone::Clone for tacenta_ratchet::RatchetError}]
    Source: 'ratchet/src/lib.rs', lines 274:9-274:14 -/
@[reducible]
def RatchetError.Insts.CoreCloneClone : core.clone.Clone RatchetError := {
  clone := RatchetError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [tacenta_ratchet::{impl core::marker::Copy for tacenta_ratchet::RatchetError}]
    Source: 'ratchet/src/lib.rs', lines 274:16-274:20 -/
@[reducible]
def RatchetError.Insts.CoreMarkerCopy : core.marker.Copy RatchetError := {
  cloneInst := RatchetError.Insts.CoreCloneClone
}

/-- Trait implementation: [tacenta_ratchet::{impl core::marker::StructuralPartialEq for tacenta_ratchet::RatchetError}]
    Source: 'ratchet/src/lib.rs', lines 274:22-274:31 -/
@[reducible]
def RatchetError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq RatchetError := {
}

/-- [tacenta_ratchet::{impl core::cmp::PartialEq<tacenta_ratchet::RatchetError> for tacenta_ratchet::RatchetError}::eq]:
    Source: 'ratchet/src/lib.rs', lines 274:22-274:31
    Visibility: public -/
def RatchetError.Insts.CoreCmpPartialEqRatchetError.eq
  (self : RatchetError) (other : RatchetError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [tacenta_ratchet::{impl core::cmp::PartialEq<tacenta_ratchet::RatchetError> for tacenta_ratchet::RatchetError}]
    Source: 'ratchet/src/lib.rs', lines 274:22-274:31 -/
@[reducible]
impl_def RatchetError.Insts.CoreCmpPartialEqRatchetError : core.cmp.PartialEq
  RatchetError RatchetError := {
  eq := RatchetError.Insts.CoreCmpPartialEqRatchetError.eq
  ne := core.cmp.PartialEq.ne.trait_default
    RatchetError.Insts.CoreCmpPartialEqRatchetError
}

/-- [tacenta_ratchet::{impl core::cmp::Eq for tacenta_ratchet::RatchetError}::assert_fields_are_eq]:
    Source: 'ratchet/src/lib.rs', lines 274:33-274:35
    Visibility: public -/
def RatchetError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : RatchetError) : Result Unit := do
  ok ()

/-- Trait implementation: [tacenta_ratchet::{impl core::cmp::Eq for tacenta_ratchet::RatchetError}]
    Source: 'ratchet/src/lib.rs', lines 274:33-274:35 -/
@[reducible]
def RatchetError.Insts.CoreCmpEq : core.cmp.Eq RatchetError := {
  partialEqInst := RatchetError.Insts.CoreCmpPartialEqRatchetError
  assert_fields_are_eq := RatchetError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [tacenta_ratchet::{impl core::fmt::Debug for tacenta_ratchet::RatchetError}::fmt]:
    Source: 'ratchet/src/lib.rs', lines 274:37-274:42
    Visibility: public -/
def RatchetError.Insts.CoreFmtDebug.fmt
  (self : RatchetError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | RatchetError.TooManySkipped =>
    core.fmt.Formatter.write_str f (toStr "TooManySkipped")
  | RatchetError.SkippedStoreFull =>
    core.fmt.Formatter.write_str f (toStr "SkippedStoreFull")
  | RatchetError.NoSendingChain =>
    core.fmt.Formatter.write_str f (toStr "NoSendingChain")
  | RatchetError.NoReceivingChain =>
    core.fmt.Formatter.write_str f (toStr "NoReceivingChain")
  | RatchetError.OutOfOrder =>
    core.fmt.Formatter.write_str f (toStr "OutOfOrder")
  | RatchetError.ChainExhausted =>
    core.fmt.Formatter.write_str f (toStr "ChainExhausted")

/-- Trait implementation: [tacenta_ratchet::{impl core::fmt::Debug for tacenta_ratchet::RatchetError}]
    Source: 'ratchet/src/lib.rs', lines 274:37-274:42 -/
@[reducible]
def RatchetError.Insts.CoreFmtDebug : core.fmt.Debug RatchetError := {
  fmt := RatchetError.Insts.CoreFmtDebug.fmt
}

/-- [tacenta_ratchet::{tacenta_ratchet::State}::sending_public]:
    Source: 'ratchet/src/lib.rs', lines 300:4-302:5
    Visibility: public -/
def State.sending_public (self : State) : Result (Array Std.U8 32#usize) := do
  ok self.dhs_pub

/-- [tacenta_ratchet::{tacenta_ratchet::State}::send_count]:
    Source: 'ratchet/src/lib.rs', lines 305:4-307:5
    Visibility: public -/
def State.send_count (self : State) : Result Std.U32 := do
  ok self.ns

/-- [tacenta_ratchet::{tacenta_ratchet::State}::receive_count]:
    Source: 'ratchet/src/lib.rs', lines 310:4-312:5
    Visibility: public -/
def State.receive_count (self : State) : Result Std.U32 := do
  ok self.nr

/-- [tacenta_ratchet::{tacenta_ratchet::State}::started_as_sender]:
    Source: 'ratchet/src/lib.rs', lines 322:4-328:5
    Visibility: public -/
def State.started_as_sender (self : State) : Result (Option Bool) := do
  match self.cks with
  | none => match self.ckr with
            | none => ok (some false)
            | some _ => ok none
  | some _ => match self.ckr with
              | none => ok (some true)
              | some _ => ok none

/-- [tacenta_ratchet::{tacenta_ratchet::State}::invariant]: loop body 1:
    Source: 'ratchet/src/lib.rs', lines 1:0-386:13
    Visibility: public -/
@[rust_loop_body]
def State.invariant_loop0_loop0.body
  (v : alloc.vec.Vec SkippedKey) (i : Std.Usize) (store_ok : Bool)
  (j : Std.Usize) :
  Result (ControlFlow (Bool × Std.Usize) Bool)
  := do
  let i1 := alloc.vec.Vec.len v
  if j < i1
  then
    let sk ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice SkippedKey) v
        i
    let sk1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice SkippedKey) v
        j
    let b ←
      core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 sk.dh sk1.dh
    let store_ok1 ←
      if b
      then if sk.n = sk1.n
           then ok false
           else ok store_ok
      else ok store_ok
    let j1 ← j + 1#usize
    ok (cont (store_ok1, j1))
  else ok (done store_ok)

/-- [tacenta_ratchet::{tacenta_ratchet::State}::invariant]: loop 1:
    Source: 'ratchet/src/lib.rs', lines 1:0-386:13
    Visibility: public -/
@[rust_loop]
def State.invariant_loop0_loop0
  (v : alloc.vec.Vec SkippedKey) (store_ok : Bool) (i : Std.Usize)
  (j : Std.Usize) :
  Result Bool
  := do
  loop
    (fun (store_ok1, j1) => State.invariant_loop0_loop0.body v i store_ok1 j1)
    (store_ok, j)

/-- [tacenta_ratchet::{tacenta_ratchet::State}::invariant]: loop body 0:
    Source: 'ratchet/src/lib.rs', lines 1:0-388:9
    Visibility: public -/
@[rust_loop_body]
def State.invariant_loop0.body
  (self : State) (store_ok : Bool) (i : Std.Usize) :
  Result (ControlFlow (Bool × Std.Usize) ((Option (Array Std.U8 32#usize)) ×
    (Option (Array Std.U8 32#usize)) × (Option (Array Std.U8 32#usize)) ×
    (alloc.vec.Vec SkippedKey) × Std.U32 × Bool))
  := do
  let i1 := alloc.vec.Vec.len self.skipped
  if i < i1
  then
    let sk ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice SkippedKey)
        self.skipped i
    let store_ok1 ←
      if sk.stored_at > self.events
      then ok false
      else ok store_ok
    let j ← i + 1#usize
    let store_ok2 ← State.invariant_loop0_loop0 self.skipped store_ok1 i j
    let i2 ← i + 1#usize
    ok (cont (store_ok2, i2))
  else
    ok (done (self.dhr_pub, self.cks, self.ckr, self.skipped, self.events,
      store_ok))

/-- [tacenta_ratchet::{tacenta_ratchet::State}::invariant]: loop 0:
    Source: 'ratchet/src/lib.rs', lines 1:0-388:9
    Visibility: public -/
@[rust_loop]
def State.invariant_loop0
  (self : State) (store_ok : Bool) (i : Std.Usize) :
  Result ((Option (Array Std.U8 32#usize)) × (Option (Array Std.U8 32#usize))
    × (Option (Array Std.U8 32#usize)) × (alloc.vec.Vec SkippedKey) ×
    Std.U32 × Bool)
  := do
  loop
    (fun (store_ok1, i1) => State.invariant_loop0.body self store_ok1 i1)
    (store_ok, i)

/-- [tacenta_ratchet::{tacenta_ratchet::State}::invariant]:
    Source: 'ratchet/src/lib.rs', lines 371:4-396:5
    Visibility: public -/
def State.invariant (self : State) : Result Bool := do
  let (o, o1, o2, v, i, store_ok) ← State.invariant_loop0 self true 0#usize
  let chains_ok ←
    match o2 with
    | none => ok true
    | some _ =>
      match o1 with
      | none => ok false
      | some _ => match o with
                  | none => ok false
                  | some _ => ok true
  let i1 := alloc.vec.Vec.len v
  if i1 <= MAX_SKIPPED_STORE
  then
    if i < core.num.U32.MAX
    then if store_ok
         then ok chains_ok
         else ok false
    else ok false
  else ok false

/-- [tacenta_ratchet::STATE_VERSION]
    Source: 'ratchet/src/lib.rs', lines 404:0-404:31 -/
@[global_simps, irreducible] def STATE_VERSION : Std.U8 := 1#u8

/-- [tacenta_ratchet::RatchetDecodeError]
    Source: 'ratchet/src/lib.rs', lines 419:0-423:1
    Visibility: public -/
@[discriminant isize]
inductive RatchetDecodeError where
| UnknownVersion : RatchetDecodeError
| TooShort : RatchetDecodeError
| Malformed : RatchetDecodeError

/-- [tacenta_ratchet::{impl core::clone::Clone for tacenta_ratchet::RatchetDecodeError}::clone]:
    Source: 'ratchet/src/lib.rs', lines 418:9-418:14
    Visibility: public -/
def RatchetDecodeError.Insts.CoreCloneClone.clone
  (self : RatchetDecodeError) : Result RatchetDecodeError := do
  ok self

/-- Trait implementation: [tacenta_ratchet::{impl core::clone::Clone for tacenta_ratchet::RatchetDecodeError}]
    Source: 'ratchet/src/lib.rs', lines 418:9-418:14 -/
@[reducible]
def RatchetDecodeError.Insts.CoreCloneClone : core.clone.Clone
  RatchetDecodeError := {
  clone := RatchetDecodeError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [tacenta_ratchet::{impl core::marker::Copy for tacenta_ratchet::RatchetDecodeError}]
    Source: 'ratchet/src/lib.rs', lines 418:16-418:20 -/
@[reducible]
def RatchetDecodeError.Insts.CoreMarkerCopy : core.marker.Copy
  RatchetDecodeError := {
  cloneInst := RatchetDecodeError.Insts.CoreCloneClone
}

/-- Trait implementation: [tacenta_ratchet::{impl core::marker::StructuralPartialEq for tacenta_ratchet::RatchetDecodeError}]
    Source: 'ratchet/src/lib.rs', lines 418:22-418:31 -/
@[reducible]
def RatchetDecodeError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq RatchetDecodeError := {
}

/-- [tacenta_ratchet::{impl core::cmp::PartialEq<tacenta_ratchet::RatchetDecodeError> for tacenta_ratchet::RatchetDecodeError}::eq]:
    Source: 'ratchet/src/lib.rs', lines 418:22-418:31
    Visibility: public -/
def RatchetDecodeError.Insts.CoreCmpPartialEqRatchetDecodeError.eq
  (self : RatchetDecodeError) (other : RatchetDecodeError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [tacenta_ratchet::{impl core::cmp::PartialEq<tacenta_ratchet::RatchetDecodeError> for tacenta_ratchet::RatchetDecodeError}]
    Source: 'ratchet/src/lib.rs', lines 418:22-418:31 -/
@[reducible]
impl_def RatchetDecodeError.Insts.CoreCmpPartialEqRatchetDecodeError :
  core.cmp.PartialEq RatchetDecodeError RatchetDecodeError := {
  eq := RatchetDecodeError.Insts.CoreCmpPartialEqRatchetDecodeError.eq
  ne := core.cmp.PartialEq.ne.trait_default
    RatchetDecodeError.Insts.CoreCmpPartialEqRatchetDecodeError
}

/-- [tacenta_ratchet::{impl core::cmp::Eq for tacenta_ratchet::RatchetDecodeError}::assert_fields_are_eq]:
    Source: 'ratchet/src/lib.rs', lines 418:33-418:35
    Visibility: public -/
def RatchetDecodeError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : RatchetDecodeError) : Result Unit := do
  ok ()

/-- Trait implementation: [tacenta_ratchet::{impl core::cmp::Eq for tacenta_ratchet::RatchetDecodeError}]
    Source: 'ratchet/src/lib.rs', lines 418:33-418:35 -/
@[reducible]
def RatchetDecodeError.Insts.CoreCmpEq : core.cmp.Eq RatchetDecodeError := {
  partialEqInst := RatchetDecodeError.Insts.CoreCmpPartialEqRatchetDecodeError
  assert_fields_are_eq :=
    RatchetDecodeError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [tacenta_ratchet::{impl core::fmt::Debug for tacenta_ratchet::RatchetDecodeError}::fmt]:
    Source: 'ratchet/src/lib.rs', lines 418:37-418:42
    Visibility: public -/
def RatchetDecodeError.Insts.CoreFmtDebug.fmt
  (self : RatchetDecodeError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | RatchetDecodeError.UnknownVersion =>
    core.fmt.Formatter.write_str f (toStr "UnknownVersion")
  | RatchetDecodeError.TooShort =>
    core.fmt.Formatter.write_str f (toStr "TooShort")
  | RatchetDecodeError.Malformed =>
    core.fmt.Formatter.write_str f (toStr "Malformed")

/-- Trait implementation: [tacenta_ratchet::{impl core::fmt::Debug for tacenta_ratchet::RatchetDecodeError}]
    Source: 'ratchet/src/lib.rs', lines 418:37-418:42 -/
@[reducible]
def RatchetDecodeError.Insts.CoreFmtDebug : core.fmt.Debug RatchetDecodeError
  := {
  fmt := RatchetDecodeError.Insts.CoreFmtDebug.fmt
}

/-- [tacenta_ratchet::OPTIONAL_KEY_LEN]
    Source: 'ratchet/src/lib.rs', lines 429:0-429:39 -/
@[global_simps, irreducible]
def OPTIONAL_KEY_LEN : Result Std.Usize := 1#usize + 32#usize

/-- [tacenta_ratchet::FIXED_LEN]
    Source: 'ratchet/src/lib.rs', lines 431:0-440:8 -/
@[global_simps, irreducible]
def FIXED_LEN : Result Std.Usize := do
  let i ← 1#usize + 32#usize
  let i1 ← OPTIONAL_KEY_LEN
  let i2 ← i + i1
  let i3 ← i2 + 32#usize
  let i4 ← i3 + i1
  let i5 ← i4 + i1
  let i6 ← i5 + 4#usize
  let i7 ← i6 + 4#usize
  let i8 ← i7 + 4#usize
  let i9 ← i8 + 4#usize
  let i10 ← i9 + 1#usize
  i10 + 4#usize

/-- [tacenta_ratchet::read_key]:
    Source: 'ratchet/src/lib.rs', lines 442:0-446:1 -/
def read_key
  (bytes : Slice Std.U8) (pos : Std.Usize) :
  Result (Array Std.U8 32#usize)
  := do
  let k := Array.repeat 32#usize 0#u8
  let (s, to_slice_mut_back) ← lift (Array.to_slice_mut k)
  let i ← pos + 32#usize
  let s1 ←
    core.slice.index.Slice.index (core.slice.index.SliceIndexRangeUsizeSlice
      Std.U8) bytes { start := pos, «end» := i }
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  ok (to_slice_mut_back s2)

/-- [tacenta_ratchet::read_u32]:
    Source: 'ratchet/src/lib.rs', lines 448:0-452:1 -/
def read_u32 (bytes : Slice Std.U8) (pos : Std.Usize) : Result Std.U32 := do
  let b := Array.repeat 4#usize 0#u8
  let (s, to_slice_mut_back) ← lift (Array.to_slice_mut b)
  let i ← pos + 4#usize
  let s1 ←
    core.slice.index.Slice.index (core.slice.index.SliceIndexRangeUsizeSlice
      Std.U8) bytes { start := pos, «end» := i }
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let b1 := to_slice_mut_back s2
  ok (core.num.U32.from_be_bytes b1)

/-- [tacenta_ratchet::push_optional_key]:
    Source: 'ratchet/src/lib.rs', lines 454:0-465:1 -/
def push_optional_key
  (out : alloc.vec.Vec Std.U8) (key : Option (Array Std.U8 32#usize)) :
  Result (alloc.vec.Vec Std.U8)
  := do
  match key with
  | none =>
    let out1 ← alloc.vec.Vec.push out 0#u8
    let a := Array.repeat 32#usize 0#u8
    let s ← lift (Array.to_slice a)
    alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out1 s
  | some k =>
    let out1 ← alloc.vec.Vec.push out 1#u8
    let s ← lift (Array.to_slice k)
    alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out1 s

/-- [tacenta_ratchet::read_optional_key]: loop body 0:
    Source: 'ratchet/src/lib.rs', lines 479:12-484:13 -/
@[rust_loop_body]
def read_optional_key_loop.body
  (bytes : Slice Std.U8) (pos : Std.Usize) (clean : Bool) (i : Std.Usize) :
  Result (ControlFlow (Bool × Std.Usize) Bool)
  := do
  let i1 ← pos + 33#usize
  if i < i1
  then
    let i2 ← Slice.index_usize bytes i
    let clean1 ← if i2 != 0#u8
                   then ok false
                   else ok clean
    let i3 ← i + 1#usize
    ok (cont (clean1, i3))
  else ok (done clean)

/-- [tacenta_ratchet::read_optional_key]: loop 0:
    Source: 'ratchet/src/lib.rs', lines 479:12-484:13 -/
@[rust_loop]
def read_optional_key_loop
  (bytes : Slice Std.U8) (pos : Std.Usize) (clean : Bool) (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun (clean1, i1) => read_optional_key_loop.body bytes pos clean1 i1)
    (clean, i)

/-- [tacenta_ratchet::read_optional_key]:
    Source: 'ratchet/src/lib.rs', lines 467:0-494:1 -/
def read_optional_key
  (bytes : Slice Std.U8) (pos : Std.Usize) :
  Result (core.result.Result (Option (Array Std.U8 32#usize))
    RatchetDecodeError)
  := do
  let i ← Slice.index_usize bytes pos
  match i with
  | 0#uscalar =>
    let i1 ← pos + 1#usize
    let clean ← read_optional_key_loop bytes pos true i1
    if clean
    then ok (core.result.Result.Ok none)
    else ok (core.result.Result.Err RatchetDecodeError.Malformed)
  | 1#uscalar =>
    let i1 ← pos + 1#usize
    let a ← read_key bytes i1
    ok (core.result.Result.Ok (some a))
  | _ => ok (core.result.Result.Err RatchetDecodeError.Malformed)

/-- [tacenta_ratchet::{tacenta_ratchet::LabelSet}::to_byte]:
    Source: 'ratchet/src/lib.rs', lines 497:4-501:5 -/
def LabelSet.to_byte (self : LabelSet) : Result Std.U8 := do
  ok 0#u8

/-- [tacenta_ratchet::{tacenta_ratchet::LabelSet}::from_byte]:
    Source: 'ratchet/src/lib.rs', lines 503:4-508:5 -/
def LabelSet.from_byte (b : Std.U8) : Result (Option LabelSet) := do
  match b with
  | 0#uscalar => ok (some LabelSet.Tacenta)
  | _ => ok none

/-- [tacenta_ratchet::{tacenta_ratchet::SkippedKey}::ENCODED_LEN]
    Source: 'ratchet/src/lib.rs', lines 512:4-512:47 -/
@[global_simps, irreducible]
def SkippedKey.ENCODED_LEN : Result Std.Usize := do
  let i ← 32#usize + 4#usize
  let i1 ← i + 4#usize
  i1 + 32#usize

/-- [tacenta_ratchet::{tacenta_ratchet::SkippedKey}::encode_into]:
    Source: 'ratchet/src/lib.rs', lines 514:4-519:5 -/
def SkippedKey.encode_into
  (self : SkippedKey) (out : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let s ← lift (Array.to_slice self.dh)
  let out1 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s
  let a ← lift (core.num.U32.to_be_bytes self.n)
  let s1 ← lift (Array.to_slice a)
  let out2 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out1 s1
  let a1 ← lift (core.num.U32.to_be_bytes self.stored_at)
  let s2 ← lift (Array.to_slice a1)
  let out3 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out2 s2
  let s3 ← lift (Array.to_slice self.key)
  alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out3 s3

/-- [tacenta_ratchet::{tacenta_ratchet::SkippedKey}::decode]:
    Source: 'ratchet/src/lib.rs', lines 521:4-539:5 -/
def SkippedKey.decode (bytes : Slice Std.U8) : Result (Option SkippedKey) := do
  let i := Slice.len bytes
  let i1 ← SkippedKey.ENCODED_LEN
  if i != i1
  then ok none
  else
    let dh := Array.repeat 32#usize 0#u8
    let (s, to_slice_mut_back) ← lift (Array.to_slice_mut dh)
    let s1 ←
      core.slice.index.Slice.index (core.slice.index.SliceIndexRangeUsizeSlice
        Std.U8) bytes { start := 0#usize, «end» := 32#usize }
    let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
    let n_bytes := Array.repeat 4#usize 0#u8
    let (s3, to_slice_mut_back1) ← lift (Array.to_slice_mut n_bytes)
    let s4 ←
      core.slice.index.Slice.index (core.slice.index.SliceIndexRangeUsizeSlice
        Std.U8) bytes { start := 32#usize, «end» := 36#usize }
    let s5 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 s4
    let stored_at_bytes := Array.repeat 4#usize 0#u8
    let (s6, to_slice_mut_back2) ← lift (Array.to_slice_mut stored_at_bytes)
    let s7 ←
      core.slice.index.Slice.index (core.slice.index.SliceIndexRangeUsizeSlice
        Std.U8) bytes { start := 36#usize, «end» := 40#usize }
    let s8 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s6 s7
    let key := Array.repeat 32#usize 0#u8
    let (s9, to_slice_mut_back3) ← lift (Array.to_slice_mut key)
    let s10 ←
      core.slice.index.Slice.index (core.slice.index.SliceIndexRangeUsizeSlice
        Std.U8) bytes { start := 40#usize, «end» := 72#usize }
    let s11 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s9 s10
    let dh1 := to_slice_mut_back s2
    let n_bytes1 := to_slice_mut_back1 s5
    let i2 ← lift (core.num.U32.from_be_bytes n_bytes1)
    let stored_at_bytes1 := to_slice_mut_back2 s8
    let i3 ← lift (core.num.U32.from_be_bytes stored_at_bytes1)
    let key1 := to_slice_mut_back3 s11
    ok (some { dh := dh1, n := i2, stored_at := i3, key := key1 })

/-- [tacenta_ratchet::decode_skipped_entry]:
    Source: 'ratchet/src/lib.rs', lines 544:0-549:1 -/
def decode_skipped_entry
  (bytes : Slice Std.U8) (pos : Std.Usize) : Result (Option SkippedKey) := do
  let i := Slice.len bytes
  let i1 ← SkippedKey.ENCODED_LEN
  let i2 ← pos + i1
  if i < i2
  then ok none
  else
    let i3 ← pos + i1
    let s ←
      core.slice.index.Slice.index (core.slice.index.SliceIndexRangeUsizeSlice
        Std.U8) bytes { start := pos, «end» := i3 }
    SkippedKey.decode s

/-- [tacenta_ratchet::{tacenta_ratchet::State}::to_bytes]: loop body 0:
    Source: 'ratchet/src/lib.rs', lines 578:8-581:9
    Visibility: public -/
@[rust_loop_body]
def State.to_bytes_loop.body
  (v : alloc.vec.Vec SkippedKey) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := alloc.vec.Vec.len v
  if i < i1
  then
    let sk ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice SkippedKey) v
        i
    let out1 ← SkippedKey.encode_into sk out
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [tacenta_ratchet::{tacenta_ratchet::State}::to_bytes]: loop 0:
    Source: 'ratchet/src/lib.rs', lines 578:8-581:9
    Visibility: public -/
@[rust_loop]
def State.to_bytes_loop
  (v : alloc.vec.Vec SkippedKey) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => State.to_bytes_loop.body v out1 i1)
    (out, i)

/-- [tacenta_ratchet::{tacenta_ratchet::State}::to_bytes]:
    Source: 'ratchet/src/lib.rs', lines 563:4-583:5
    Visibility: public -/
def State.to_bytes
  (self : State) : Result (zeroize.Zeroizing (alloc.vec.Vec Std.U8)) := do
  let i := alloc.vec.Vec.len self.skipped
  let i1 ← SkippedKey.ENCODED_LEN
  let i2 ← i * i1
  let i3 ← FIXED_LEN
  let i4 ← i3 + i2
  let out := alloc.vec.Vec.with_capacity Std.U8 i4
  let out1 ← alloc.vec.Vec.push out STATE_VERSION
  let s ← lift (Array.to_slice self.dhs_pub)
  let out2 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out1 s
  let out3 ← push_optional_key out2 self.dhr_pub
  let s1 ← lift (Array.to_slice self.rk)
  let out4 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out3 s1
  let out5 ← push_optional_key out4 self.cks
  let out6 ← push_optional_key out5 self.ckr
  let a ← lift (core.num.U32.to_be_bytes self.ns)
  let s2 ← lift (Array.to_slice a)
  let out7 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out6 s2
  let a1 ← lift (core.num.U32.to_be_bytes self.nr)
  let s3 ← lift (Array.to_slice a1)
  let out8 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out7 s3
  let a2 ← lift (core.num.U32.to_be_bytes self.pn)
  let s4 ← lift (Array.to_slice a2)
  let out9 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out8 s4
  let a3 ← lift (core.num.U32.to_be_bytes self.events)
  let s5 ← lift (Array.to_slice a3)
  let out10 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out9 s5
  let i5 ← LabelSet.to_byte self.labels
  let out11 ← alloc.vec.Vec.push out10 i5
  let i6 := alloc.vec.Vec.len self.skipped
  let i7 ← lift (UScalar.cast .U32 i6)
  let a4 ← lift (core.num.U32.to_be_bytes i7)
  let s6 ← lift (Array.to_slice a4)
  let out12 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out11 s6
  let out13 ← State.to_bytes_loop self.skipped out12 0#usize
  zeroize.Zeroizing.new (alloc.vec.Vec.Insts.ZeroizeZeroize
    (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes)) out13

/-- [tacenta_ratchet::{tacenta_ratchet::State}::from_bytes]: loop body 0:
    Source: 'ratchet/src/lib.rs', lines 648:8-658:9
    Visibility: public -/
@[rust_loop_body]
def State.from_bytes_loop.body
  (i : Std.Usize) (bytes : Slice Std.U8)
  (iter : core.ops.range.Range Std.Usize) (pos : Std.Usize)
  (skipped : alloc.vec.Vec SkippedKey) (ok1 : Bool) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.Usize ×
    (alloc.vec.Vec SkippedKey) × Bool) (Std.Usize × (alloc.vec.Vec
    SkippedKey) × Bool))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (pos, skipped, ok1))
  | some _ =>
    let o1 ← decode_skipped_entry bytes pos
    match o1 with
    | none => ok (cont (iter1, pos, skipped, false))
    | some entry =>
      let skipped1 ← alloc.vec.Vec.push skipped entry
      let pos1 ← pos + i
      ok (cont (iter1, pos1, skipped1, ok1))

/-- [tacenta_ratchet::{tacenta_ratchet::State}::from_bytes]: loop 0:
    Source: 'ratchet/src/lib.rs', lines 648:8-658:9
    Visibility: public -/
@[rust_loop]
def State.from_bytes_loop
  (i : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (bytes : Slice Std.U8) (pos : Std.Usize) (skipped : alloc.vec.Vec SkippedKey)
  (ok1 : Bool) :
  Result (Std.Usize × (alloc.vec.Vec SkippedKey) × Bool)
  := do
  loop
    (fun (iter1, pos1, skipped1, ok2) => State.from_bytes_loop.body i bytes
      iter1 pos1 skipped1 ok2)
    (iter, pos, skipped, ok1)

/-- [tacenta_ratchet::{tacenta_ratchet::State}::from_bytes]:
    Source: 'ratchet/src/lib.rs', lines 588:4-686:5
    Visibility: public -/
def State.from_bytes
  (bytes : Slice Std.U8) :
  Result (core.result.Result State RatchetDecodeError)
  := do
  let i := Slice.len bytes
  let i1 ← FIXED_LEN
  if i < i1
  then ok (core.result.Result.Err RatchetDecodeError.TooShort)
  else
    let i2 ← Slice.index_usize bytes 0#usize
    if i2 != STATE_VERSION
    then ok (core.result.Result.Err RatchetDecodeError.UnknownVersion)
    else
      let dhs_pub ← read_key bytes 1#usize
      let pos ← 1#usize + 32#usize
      let r ← read_optional_key bytes pos
      match r with
      | core.result.Result.Ok v =>
        let i3 ← OPTIONAL_KEY_LEN
        let pos1 ← pos + i3
        let rk ← read_key bytes pos1
        let pos2 ← pos1 + 32#usize
        let r1 ← read_optional_key bytes pos2
        match r1 with
        | core.result.Result.Ok v1 =>
          let pos3 ← pos2 + i3
          let r2 ← read_optional_key bytes pos3
          match r2 with
          | core.result.Result.Ok v2 =>
            let pos4 ← pos3 + i3
            let ns ← read_u32 bytes pos4
            let pos5 ← pos4 + 4#usize
            let nr ← read_u32 bytes pos5
            let pos6 ← pos5 + 4#usize
            let pn ← read_u32 bytes pos6
            let pos7 ← pos6 + 4#usize
            let events ← read_u32 bytes pos7
            let pos8 ← pos7 + 4#usize
            let i4 ← Slice.index_usize bytes pos8
            let o ← LabelSet.from_byte i4
            match o with
            | none => ok (core.result.Result.Err RatchetDecodeError.Malformed)
            | some labels =>
              let pos9 ← pos8 + 1#usize
              let i5 ← read_u32 bytes pos9
              let skipped_count ← lift (UScalar.cast .Usize i5)
              let pos10 ← pos9 + 4#usize
              let i6 := Slice.len bytes
              let i7 ← SkippedKey.ENCODED_LEN
              let i8 ← i6 / i7
              if skipped_count > i8
              then ok (core.result.Result.Err RatchetDecodeError.Malformed)
              else
                let (pos11, skipped, ok1) ←
                  State.from_bytes_loop i7
                    { start := 0#usize, «end» := skipped_count } bytes pos10
                    (alloc.vec.Vec.new SkippedKey) true
                if ok1
                then
                  let i9 := Slice.len bytes
                  if pos11 != i9
                  then ok (core.result.Result.Err RatchetDecodeError.Malformed)
                  else
                    let b ←
                      State.invariant
                        {
                          dhs_pub,
                          dhr_pub := v,
                          rk,
                          cks := v1,
                          ckr := v2,
                          ns,
                          nr,
                          pn,
                          skipped,
                          events,
                          labels
                        }
                    if b
                    then
                      ok (core.result.Result.Ok
                        {
                          dhs_pub,
                          dhr_pub := v,
                          rk,
                          cks := v1,
                          ckr := v2,
                          ns,
                          nr,
                          pn,
                          skipped,
                          events,
                          labels
                        })
                    else
                      ok (core.result.Result.Err RatchetDecodeError.Malformed)
                else ok (core.result.Result.Err RatchetDecodeError.Malformed)
          | core.result.Result.Err e => ok (core.result.Result.Err e)
        | core.result.Result.Err e => ok (core.result.Result.Err e)
      | core.result.Result.Err e => ok (core.result.Result.Err e)

/-- [tacenta_ratchet::kdf_ck]:
    Source: 'ratchet/src/lib.rs', lines 691:0-695:1 -/
def kdf_ck
  (ck : Array Std.U8 32#usize) :
  Result ((Array Std.U8 32#usize) × (Array Std.U8 32#usize))
  := do
  let s ← lift (Array.to_slice ck)
  let s1 ← lift (Array.to_slice (Array.make 1#usize [ 1#u8 ]))
  let mk ← tacenta_kdf.hmac_sha256 s s1
  let s2 ← lift (Array.to_slice ck)
  let s3 ← lift (Array.to_slice (Array.make 1#usize [ 2#u8 ]))
  let next ← tacenta_kdf.hmac_sha256 s2 s3
  ok (next, mk)

/-- [tacenta_ratchet::kdf_rk]:
    Source: 'ratchet/src/lib.rs', lines 699:0-710:1 -/
def kdf_rk
  (rk : Array Std.U8 32#usize) (dh_out : Array Std.U8 32#usize)
  (labels : LabelSet) :
  Result ((Array Std.U8 32#usize) × (Array Std.U8 32#usize))
  := do
  let s ← lift (Array.to_slice rk)
  let s1 ← lift (Array.to_slice dh_out)
  let a ← tacenta_kdf.hkdf_sha256 64#usize s s1 RK_INFO
  let out ←
    zeroize.Zeroizing.new (Array.Insts.ZeroizeZeroize 64#usize
      (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes)) a
  let rk2 := Array.repeat 32#usize 0#u8
  let ck := Array.repeat 32#usize 0#u8
  let (s2, to_slice_mut_back) ← lift (Array.to_slice_mut rk2)
  let a1 ←
    zeroize.Zeroizing.Insts.CoreOpsDerefDeref.deref (Array.Insts.ZeroizeZeroize
      64#usize (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes)) out
  let s3 ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) a1
      { «end» := 32#usize }
  let s4 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s2 s3
  let (s5, to_slice_mut_back1) ← lift (Array.to_slice_mut ck)
  let s6 ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8)) a1
      { start := 32#usize }
  let s7 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s5 s6
  let rk21 := to_slice_mut_back s4
  let ck1 := to_slice_mut_back1 s7
  ok (rk21, ck1)

/-- [tacenta_ratchet::message_keys]:
    Source: 'ratchet/src/lib.rs', lines 715:0-728:1
    Visibility: public -/
def message_keys
  (mk : Array Std.U8 32#usize) (labels : LabelSet) :
  Result ((Array Std.U8 32#usize) × (Array Std.U8 32#usize) × (Array Std.U8
    16#usize))
  := do
  let a := Array.repeat 32#usize 0#u8
  let s ← lift (Array.to_slice a)
  let s1 ← lift (Array.to_slice mk)
  let a1 ← tacenta_kdf.hkdf_sha256 80#usize s s1 MK_INFO
  let out ←
    zeroize.Zeroizing.new (Array.Insts.ZeroizeZeroize 80#usize
      (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes)) a1
  let enc := Array.repeat 32#usize 0#u8
  let mac := Array.repeat 32#usize 0#u8
  let iv := Array.repeat 16#usize 0#u8
  let (s2, to_slice_mut_back) ← lift (Array.to_slice_mut enc)
  let a2 ←
    zeroize.Zeroizing.Insts.CoreOpsDerefDeref.deref (Array.Insts.ZeroizeZeroize
      80#usize (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes)) out
  let s3 ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) a2
      { «end» := 32#usize }
  let s4 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s2 s3
  let (s5, to_slice_mut_back1) ← lift (Array.to_slice_mut mac)
  let s6 ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) a2
      { start := 32#usize, «end» := 64#usize }
  let s7 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s5 s6
  let (s8, to_slice_mut_back2) ← lift (Array.to_slice_mut iv)
  let s9 ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8)) a2
      { start := 64#usize }
  let s10 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s8 s9
  let enc1 := to_slice_mut_back s4
  let mac1 := to_slice_mut_back1 s7
  let iv1 := to_slice_mut_back2 s10
  ok (enc1, mac1, iv1)

/-- [tacenta_ratchet::derive_chain]: loop body 0:
    Source: 'ratchet/src/lib.rs', lines 758:4-767:1 -/
@[rust_loop_body]
def derive_chain_loop.body
  (start_n : Std.U32) (iter : core.ops.range.Range Std.U32)
  (cur : Array Std.U8 32#usize)
  (keys : zeroize.Zeroizing (alloc.vec.Vec (Std.U32 × (Array Std.U8
  32#usize)))) :
  Result (ControlFlow ((core.ops.range.Range Std.U32) × (Array Std.U8
    32#usize) × (zeroize.Zeroizing (alloc.vec.Vec (Std.U32 × (Array Std.U8
    32#usize))))) (core.result.Result ((Array Std.U8 32#usize) ×
    (zeroize.Zeroizing (alloc.vec.Vec (Std.U32 × (Array Std.U8 32#usize)))))
    RatchetError))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU32 iter
  match o with
  | none => ok (done (core.result.Result.Ok (cur, keys)))
  | some i =>
    let o1 ← lift (U32.checked_add start_n i)
    match o1 with
    | none => ok (done (core.result.Result.Err RatchetError.ChainExhausted))
    | some n =>
      let (next, mk) ← kdf_ck cur
      let (v, deref_mut_back) ←
        zeroize.Zeroizing.Insts.CoreOpsDerefDerefMut.deref_mut
          (alloc.vec.Vec.Insts.ZeroizeZeroize (Pair.Insts.ZeroizeZeroize
          (zeroize.Zeroize.Blanket U32.Insts.ZeroizeDefaultIsZeroes)
          (Array.Insts.ZeroizeZeroize 32#usize (zeroize.Zeroize.Blanket
          U8.Insts.ZeroizeDefaultIsZeroes)))) keys
      let v1 ← alloc.vec.Vec.push v (n, mk)
      let keys1 := deref_mut_back v1
      ok (cont (iter1, next, keys1))

/-- [tacenta_ratchet::derive_chain]: loop 0:
    Source: 'ratchet/src/lib.rs', lines 758:4-767:1 -/
@[rust_loop]
def derive_chain_loop
  (iter : core.ops.range.Range Std.U32) (start_n : Std.U32)
  (cur : Array Std.U8 32#usize)
  (keys : zeroize.Zeroizing (alloc.vec.Vec (Std.U32 × (Array Std.U8
  32#usize)))) :
  Result (core.result.Result ((Array Std.U8 32#usize) × (zeroize.Zeroizing
    (alloc.vec.Vec (Std.U32 × (Array Std.U8 32#usize))))) RatchetError)
  := do
  loop
    (fun (iter1, cur1, keys1) => derive_chain_loop.body start_n iter1 cur1
      keys1)
    (iter, cur, keys)

/-- [tacenta_ratchet::derive_chain]:
    Source: 'ratchet/src/lib.rs', lines 755:0-767:1 -/
def derive_chain
  (ck : Array Std.U8 32#usize) (start_n : Std.U32) (count : Std.U32) :
  Result (core.result.Result ((Array Std.U8 32#usize) × (zeroize.Zeroizing
    (alloc.vec.Vec (Std.U32 × (Array Std.U8 32#usize))))) RatchetError)
  := do
  let i ← lift (UScalar.cast .Usize count)
  let v := alloc.vec.Vec.with_capacity (Std.U32 × (Array Std.U8 32#usize)) i
  let keys ←
    zeroize.Zeroizing.new (alloc.vec.Vec.Insts.ZeroizeZeroize
      (Pair.Insts.ZeroizeZeroize (zeroize.Zeroize.Blanket
      U32.Insts.ZeroizeDefaultIsZeroes) (Array.Insts.ZeroizeZeroize 32#usize
      (zeroize.Zeroize.Blanket U8.Insts.ZeroizeDefaultIsZeroes)))) v
  derive_chain_loop { start := 0#u32, «end» := count } start_n ck keys

/-- [tacenta_ratchet::purge_chain_range]: loop body 0:
    Source: 'ratchet/src/lib.rs', lines 928:4-934:5 -/
@[rust_loop_body]
def purge_chain_range_loop.body
  (dhr : Array Std.U8 32#usize) (from1 : Std.U32) (upto : Std.U32)
  (skipped : alloc.vec.Vec SkippedKey) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec SkippedKey) × Std.Usize) (alloc.vec.Vec
    SkippedKey))
  := do
  let i1 := alloc.vec.Vec.len skipped
  if i < i1
  then
    let sk ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice SkippedKey)
        skipped i
    let b ←
      core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 sk.dh dhr
    if b
    then
      if sk.n >= from1
      then
        if sk.n < upto
        then
          let (_, skipped1) ← alloc.vec.Vec.remove Global skipped i
          ok (cont (skipped1, i))
        else let i2 ← i + 1#usize
             ok (cont (skipped, i2))
      else let i2 ← i + 1#usize
           ok (cont (skipped, i2))
    else let i2 ← i + 1#usize
         ok (cont (skipped, i2))
  else ok (done skipped)

/-- [tacenta_ratchet::purge_chain_range]: loop 0:
    Source: 'ratchet/src/lib.rs', lines 928:4-934:5 -/
@[rust_loop]
def purge_chain_range_loop
  (skipped : alloc.vec.Vec SkippedKey) (dhr : Array Std.U8 32#usize)
  (from1 : Std.U32) (upto : Std.U32) (i : Std.Usize) :
  Result (alloc.vec.Vec SkippedKey)
  := do
  loop
    (fun (skipped1, i1) => purge_chain_range_loop.body dhr from1 upto skipped1
      i1)
    (skipped, i)

/-- [tacenta_ratchet::purge_chain_range]:
    Source: 'ratchet/src/lib.rs', lines 926:0-935:1 -/
@[reducible]
def purge_chain_range
  (skipped : alloc.vec.Vec SkippedKey) (dhr : Array Std.U8 32#usize)
  (from1 : Std.U32) (upto : Std.U32) :
  Result (alloc.vec.Vec SkippedKey)
  := do
  purge_chain_range_loop skipped dhr from1 upto 0#usize

/-- [tacenta_ratchet::skip_message_keys]: loop body 0:
    Source: 'ratchet/src/lib.rs', lines 790:16-798:17 -/
@[rust_loop_body]
def skip_message_keys_loop.body
  (dhr : Array Std.U8 32#usize) (i : Std.U32)
  (keys : zeroize.Zeroizing (alloc.vec.Vec (Std.U32 × (Array Std.U8
  32#usize)))) (v : alloc.vec.Vec SkippedKey) (i1 : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec SkippedKey) × Std.Usize) (alloc.vec.Vec
    SkippedKey))
  := do
  let v1 ←
    zeroize.Zeroizing.Insts.CoreOpsDerefDeref.deref
      (alloc.vec.Vec.Insts.ZeroizeZeroize (Pair.Insts.ZeroizeZeroize
      (zeroize.Zeroize.Blanket U32.Insts.ZeroizeDefaultIsZeroes)
      (Array.Insts.ZeroizeZeroize 32#usize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes)))) keys
  let i2 := alloc.vec.Vec.len v1
  if i1 < i2
  then
    let (i3, _) ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Std.U32 ×
        (Array Std.U8 32#usize))) v1 i1
    let (_, a) ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Std.U32 ×
        (Array Std.U8 32#usize))) v1 i1
    let v2 ←
      alloc.vec.Vec.push v ({ dh := dhr, n := i3, stored_at := i, key := a } :
        SkippedKey)
    let i4 ← i1 + 1#usize
    ok (cont (v2, i4))
  else ok (done v)

/-- [tacenta_ratchet::skip_message_keys]: loop 0:
    Source: 'ratchet/src/lib.rs', lines 790:16-798:17 -/
@[rust_loop]
def skip_message_keys_loop
  (dhr : Array Std.U8 32#usize) (v : alloc.vec.Vec SkippedKey) (i : Std.U32)
  (keys : zeroize.Zeroizing (alloc.vec.Vec (Std.U32 × (Array Std.U8
  32#usize)))) (i1 : Std.Usize) :
  Result (alloc.vec.Vec SkippedKey)
  := do
  loop
    (fun (v1, i2) => skip_message_keys_loop.body dhr i keys v1 i2)
    (v, i1)

/-- [tacenta_ratchet::skip_message_keys]:
    Source: 'ratchet/src/lib.rs', lines 772:0-806:1 -/
def skip_message_keys
  (state : State) (upto : Std.U32) :
  Result ((core.result.Result Unit RatchetError) × State)
  := do
  match state.ckr with
  | none => ok (core.result.Result.Ok (), state)
  | some ck =>
    match state.dhr_pub with
    | none => ok (core.result.Result.Ok (), state)
    | some dhr =>
      if upto <= state.nr
      then ok (core.result.Result.Ok (), state)
      else
        let i ← lift (core.num.U32.saturating_add state.nr MAX_SKIP)
        if upto > i
        then ok (core.result.Result.Err RatchetError.TooManySkipped, state)
        else
          let i1 := alloc.vec.Vec.len state.skipped
          let i2 ← upto - state.nr
          let i3 ← lift (UScalar.cast .Usize i2)
          let i4 ← i1 + i3
          if i4 > MAX_SKIPPED_STORE
          then ok (core.result.Result.Err RatchetError.SkippedStoreFull, state)
          else
            let r ← derive_chain ck state.nr i2
            match r with
            | core.result.Result.Ok v =>
              let (ck2, keys) := v
              let v1 ← purge_chain_range state.skipped dhr state.nr upto
              let v2 ←
                skip_message_keys_loop dhr v1 state.events keys 0#usize
              ok (core.result.Result.Ok (),
                { state with ckr := (some ck2), nr := upto, skipped := v2 })
            | core.result.Result.Err e => ok (core.result.Result.Err e, state)

/-- [tacenta_ratchet::init_sender]:
    Source: 'ratchet/src/lib.rs', lines 811:0-826:1
    Visibility: public -/
def init_sender
  (sk : Array Std.U8 32#usize) (our_pub : Array Std.U8 32#usize)
  (peer_pub : Array Std.U8 32#usize) (dh_out : Array Std.U8 32#usize)
  (labels : LabelSet) :
  Result State
  := do
  let (rk, cks) ← kdf_rk sk dh_out labels
  ok
    {
      dhs_pub := our_pub,
      dhr_pub := (some peer_pub),
      rk,
      cks := (some cks),
      ckr := none,
      ns := 0#u32,
      nr := 0#u32,
      pn := 0#u32,
      skipped := (alloc.vec.Vec.new SkippedKey),
      events := 0#u32,
      labels
    }

/-- [tacenta_ratchet::init_receiver]:
    Source: 'ratchet/src/lib.rs', lines 831:0-845:1
    Visibility: public -/
def init_receiver
  (sk : Array Std.U8 32#usize) (our_pub : Array Std.U8 32#usize)
  (labels : LabelSet) :
  Result State
  := do
  ok
    {
      dhs_pub := our_pub,
      dhr_pub := none,
      rk := sk,
      cks := none,
      ckr := none,
      ns := 0#u32,
      nr := 0#u32,
      pn := 0#u32,
      skipped := (alloc.vec.Vec.new SkippedKey),
      events := 0#u32,
      labels
    }

/-- [tacenta_ratchet::send]:
    Source: 'ratchet/src/lib.rs', lines 849:0-869:1
    Visibility: public -/
def send
  (state : State) :
  Result ((core.result.Result (Header × (Array Std.U8 32#usize)) RatchetError)
    × State)
  := do
  match state.cks with
  | none => ok (core.result.Result.Err RatchetError.NoSendingChain, state)
  | some ck =>
    let o ← lift (U32.checked_add state.ns 1#u32)
    match o with
    | none => ok (core.result.Result.Err RatchetError.ChainExhausted, state)
    | some next_ns =>
      let (ck2, mk) ← kdf_ck ck
      ok (core.result.Result.Ok
        ({ dh := state.dhs_pub, pn := state.pn, n := state.ns }, mk),
        { state with cks := (some ck2), ns := next_ns })

/-- [tacenta_ratchet::dh_ratchet]:
    Source: 'ratchet/src/lib.rs', lines 874:0-891:1 -/
def dh_ratchet
  (state : State) (header : Header) (dh_out_recv : Array Std.U8 32#usize)
  (dh_out_send : Array Std.U8 32#usize) (new_dhs_pub : Array Std.U8 32#usize) :
  Result State
  := do
  let (rk1, ckr) ← kdf_rk state.rk dh_out_recv state.labels
  let (rk2, cks) ← kdf_rk rk1 dh_out_send state.labels
  ok
    {
      state
        with
        dhs_pub := new_dhs_pub,
        dhr_pub := (some header.dh),
        rk := rk2,
        cks := (some cks),
        ckr := (some ckr),
        ns := 0#u32,
        nr := 0#u32,
        pn := state.ns
    }

/-- [tacenta_ratchet::age_store]: loop body 0:
    Source: 'ratchet/src/lib.rs', lines 971:4-982:5 -/
@[rust_loop_body]
def age_store_loop.body
  (now : Std.U32) (v : alloc.vec.Vec SkippedKey) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec SkippedKey) × Std.Usize) (alloc.vec.Vec
    SkippedKey))
  := do
  let i1 := alloc.vec.Vec.len v
  if i < i1
  then
    let sk ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice SkippedKey) v
        i
    let i2 ← lift (core.num.U32.saturating_sub now sk.stored_at)
    if i2 >= MAX_SKIPPED_AGE
    then let (_, v1) ← alloc.vec.Vec.remove Global v i
         ok (cont (v1, i))
    else let i3 ← i + 1#usize
         ok (cont (v, i3))
  else ok (done v)

/-- [tacenta_ratchet::age_store]: loop 0:
    Source: 'ratchet/src/lib.rs', lines 971:4-982:5 -/
@[rust_loop]
def age_store_loop
  (v : alloc.vec.Vec SkippedKey) (now : Std.U32) (i : Std.Usize) :
  Result (alloc.vec.Vec SkippedKey)
  := do
  loop
    (fun (v1, i1) => age_store_loop.body now v1 i1)
    (v, i)

/-- [tacenta_ratchet::age_store]:
    Source: 'ratchet/src/lib.rs', lines 962:0-983:1 -/
def age_store (state : State) : Result State := do
  let stepped ← lift (core.num.U32.saturating_add state.events 1#u32)
  let now ← if stepped = core.num.U32.MAX
              then ok MAX_EVENTS
              else ok stepped
  let v ← age_store_loop state.skipped now 0#usize
  ok { state with skipped := v, events := now }

/-- [tacenta_ratchet::try_skipped]: loop body 0:
    Source: 'ratchet/src/lib.rs', lines 1:0-999:1 -/
@[rust_loop_body]
def try_skipped_loop.body
  (state : State) (header : Header) (i : Std.Usize) :
  Result (ControlFlow Std.Usize ((Option (Array Std.U8 32#usize)) × (Array
    Std.U8 32#usize) × (Option (Array Std.U8 32#usize)) × (Array Std.U8
    32#usize) × (Option (Array Std.U8 32#usize)) × (Option (Array Std.U8
    32#usize)) × Std.U32 × Std.U32 × Std.U32 × (alloc.vec.Vec SkippedKey)
    × Std.U32 × LabelSet))
  := do
  let i1 := alloc.vec.Vec.len state.skipped
  if i < i1
  then
    let sk ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice SkippedKey)
        state.skipped i
    let b ←
      core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 sk.dh
        header.dh
    if b
    then
      if sk.n = header.n
      then
        let (_, v) ← alloc.vec.Vec.remove Global state.skipped i
        ok (done (some sk.key, state.dhs_pub, state.dhr_pub, state.rk,
          state.cks, state.ckr, state.ns, state.nr, state.pn, v, state.events,
          state.labels))
      else let i2 ← i + 1#usize
           ok (cont i2)
    else let i2 ← i + 1#usize
         ok (cont i2)
  else
    ok (done (none, state.dhs_pub, state.dhr_pub, state.rk, state.cks,
      state.ckr, state.ns, state.nr, state.pn, state.skipped, state.events,
      state.labels))

/-- [tacenta_ratchet::try_skipped]: loop 0:
    Source: 'ratchet/src/lib.rs', lines 1:0-999:1 -/
@[rust_loop]
def try_skipped_loop
  (state : State) (header : Header) (i : Std.Usize) :
  Result ((Option (Array Std.U8 32#usize)) × (Array Std.U8 32#usize) ×
    (Option (Array Std.U8 32#usize)) × (Array Std.U8 32#usize) × (Option
    (Array Std.U8 32#usize)) × (Option (Array Std.U8 32#usize)) × Std.U32 ×
    Std.U32 × Std.U32 × (alloc.vec.Vec SkippedKey) × Std.U32 × LabelSet)
  := do
  loop
    (fun i1 => try_skipped_loop.body state header i1)
    i

/-- [tacenta_ratchet::try_skipped]:
    Source: 'ratchet/src/lib.rs', lines 985:0-999:1 -/
def try_skipped
  (state : State) (header : Header) :
  Result ((Option (Array Std.U8 32#usize)) × State)
  := do
  let (o, a, o1, a1, o2, o3, i, i1, i2, v, i3, ls) ←
    try_skipped_loop state header 0#usize
  ok (o,
    {
      dhs_pub := a,
      dhr_pub := o1,
      rk := a1,
      cks := o2,
      ckr := o3,
      ns := i,
      nr := i1,
      pn := i2,
      skipped := v,
      events := i3,
      labels := ls
    })

/-- [tacenta_ratchet::receive]:
    Source: 'ratchet/src/lib.rs', lines 1022:0-1068:1
    Visibility: public -/
def receive
  (state : State) (header : Header) (dh_out_recv : Array Std.U8 32#usize)
  (dh_out_send : Array Std.U8 32#usize) (new_dhs_pub : Array Std.U8 32#usize) :
  Result ((core.result.Result (Array Std.U8 32#usize) RatchetError) × State)
  := do
  let (o, state1) ← try_skipped state header
  match o with
  | none =>
    let (o1, header1, needs_ratchet) ←
      match state1.dhr_pub with
      | none => ok (none, header, true)
      | some dhr =>
        do
        let needs_ratchet1 ←
          core.array.equality.PartialEqArray.ne core.cmp.PartialEqU8 dhr
            header.dh
        ok (state1.dhr_pub, header, needs_ratchet1)
    if needs_ratchet
    then
      let (r, state2) ←
        skip_message_keys { state1 with dhr_pub := o1 } header1.pn
      match r with
      | core.result.Result.Ok _ =>
        let state3 ←
          dh_ratchet state2 header1 dh_out_recv dh_out_send new_dhs_pub
        let (r1, state4) ← skip_message_keys state3 header1.n
        match r1 with
        | core.result.Result.Ok _ =>
          if header1.n < state4.nr
          then ok (core.result.Result.Err RatchetError.OutOfOrder, state4)
          else
            match state4.ckr with
            | none =>
              ok (core.result.Result.Err RatchetError.NoReceivingChain, state4)
            | some ck =>
              let o2 ← lift (U32.checked_add state4.nr 1#u32)
              match o2 with
              | none =>
                ok (core.result.Result.Err RatchetError.ChainExhausted, state4)
              | some next_nr =>
                let (ck2, mk) ← kdf_ck ck
                let state5 ←
                  age_store { state4 with ckr := (some ck2), nr := next_nr }
                ok (core.result.Result.Ok mk, state5)
        | core.result.Result.Err e => ok (core.result.Result.Err e, state4)
      | core.result.Result.Err e => ok (core.result.Result.Err e, state2)
    else
      let (r, state2) ←
        skip_message_keys { state1 with dhr_pub := o1 } header1.n
      match r with
      | core.result.Result.Ok _ =>
        if header1.n < state2.nr
        then ok (core.result.Result.Err RatchetError.OutOfOrder, state2)
        else
          match state2.ckr with
          | none =>
            ok (core.result.Result.Err RatchetError.NoReceivingChain, state2)
          | some ck =>
            let o2 ← lift (U32.checked_add state2.nr 1#u32)
            match o2 with
            | none =>
              ok (core.result.Result.Err RatchetError.ChainExhausted, state2)
            | some next_nr =>
              let (ck2, mk) ← kdf_ck ck
              let state3 ←
                age_store { state2 with ckr := (some ck2), nr := next_nr }
              ok (core.result.Result.Ok mk, state3)
      | core.result.Result.Err e => ok (core.result.Result.Err e, state2)
  | some mk =>
    let state2 ← age_store state1
    ok (core.result.Result.Ok mk, state2)

end tacenta_ratchet
